const sheet=new Image(),sprites=new Map();
export const battlefieldArtReady=new Promise(resolve=>{sheet.onload=()=>{
 const c=document.createElement('canvas');c.width=sheet.naturalWidth;c.height=sheet.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(sheet,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;
 ['aa','ship'].forEach((name,i)=>{const start=Math.round(c.width*i/2),end=Math.round(c.width*(i+1)/2);let l=end,r=start,t=c.height,b=0;for(let y=0;y<c.height;y++)for(let x=start;x<end;x++)if(data[(y*c.width+x)*4+3]>100){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}if(r>=l)sprites.set(name,{sheet,x:l,y:t,w:r-l+1,h:b-t+1})});resolve(true)
 };sheet.onerror=()=>resolve(false);sheet.src='./hazards53.webp?v=3188&b=318'});
export function drawBattlefieldSprite(c,name,x,y,size,a=0){const f=sprites.get(name);if(!f)return;const k=size/Math.max(f.w,f.h);c.save();c.translate(Math.round(x),Math.round(y));c.rotate(a);c.imageSmoothingEnabled=false;c.drawImage(f.sheet,f.x,f.y,f.w,f.h,-f.w*k/2,-f.h*k/2,f.w*k,f.h*k);c.restore()}

export const fieldUnitsReady=new Promise(resolve=>{const sheet=new Image();sheet.onload=()=>{const c=document.createElement('canvas');c.width=sheet.naturalWidth;c.height=sheet.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(sheet,0,0);const d=ctx.getImageData(0,0,c.width,c.height).data;
 ['drachen','caquot','railgun'].forEach((name,i)=>{const start=Math.round(c.width*i/3),end=Math.round(c.width*(i+1)/3);let l=end,r=start,t=c.height,b=0;for(let y=0;y<c.height;y++)for(let x=start;x<end;x++)if(d[(y*c.width+x)*4+3]>100){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}if(r>=l)sprites.set(name,{sheet,x:l,y:t,w:r-l+1,h:b-t+1})});resolve(true)};sheet.onerror=()=>resolve(false);sheet.src='./units56.webp?v=3188&b=318'});
