import {drawGrenade,drawGrenadeBlast,drawAmatolBlast,drawFxExplosion} from './weapon-effects156.js?v=283&b=283';
import {fx,fxReady,fxTint} from './fx-art.js?v=282';
import {playerPose,drawPlayerAura,drawPetalParticle,drawRedGhosts162} from './player-effects129.js?v=283&b=283';
import {drawStageBoss} from './stageboss-view.js?v=285&b=285';
import {planeSprite,aircraftKey} from './aircraft.js?v=283&b=283';
import {drawEquipment} from './equipment.js?v=215&b=211';
import {drawEnemyProjectile,drawCannonProjectile,drawBattlefieldFire,friendlyTracerColor} from './projectiles.js?v=279&b=279';
import {drawBattlefieldSprite} from './battlefield-art.js?v=215&b=211';
import {drawSpecialAmmoIcon} from './icons.js?v=216';
import {SUN_STRIKE,TAILING_BALANCE,SPECIAL_AMMO,enemyAircraftScale} from './engine.js?v=283&b=283';

// Every combat layer uses the same world transform; rendering never edits the session.
const xpGem=null;const ballCloudSprite=new Image();ballCloudSprite.src='./fx-ball-cloud.webp?v=257&b=215';
export function drawCoop(c,g,W,H,{terrain,drawZeppelin,drawFieldArt,fieldArt}){
 const t=g.t,z=g.camera.zoom;c.save();c.scale(z,z);terrain(g.x,g.y,W/z,H/z);c.restore();drawStageBoss(c,g,W,H,{drawZeppelin,drawFieldArt,layer:'bodies'});c.save();c.translate(W/2,H/2);c.scale(z,z);c.translate(-g.x,-g.y);
 drawBattlefieldFire(c,g);for(const e of g.enemyAirshipPasses||[])drawZeppelin(c,e.x,e.y,e.a,.72,false,'central');
 for(const p of g.players)for(const d of p.vossAfterimages||[]){c.save();c.globalAlpha=.4*d.life/d.maxLife;planeSprite(c,d.x,d.y,d.a,aircraftKey(p.plane,false,p.pilot),1);c.restore();}
 for(const e of g.enemies)for(const d of e.vossTrails||[]){c.save();c.globalAlpha=.4*d.life/d.maxLife;planeSprite(c,d.x,d.y,d.a,e.bossPlane,enemyAircraftScale(e),true);c.restore();}
 for(const d of g.revisionDecoys||[]){c.save();c.globalAlpha=Math.min(.45,d.life*.4);planeSprite(c,d.x,d.y,d.a,aircraftKey(d.plane,false,d.pilot),1);c.restore()}
 const ring=(x,y,r,color,width=2)=>{c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.stroke()};
 const heart=(x,y,size,color)=>{const s=Math.max(1,Math.round(size/4));c.fillStyle=color;c.fillRect(x-2*s,y-s,s,s);c.fillRect(x+s,y-s,s,s);c.fillRect(x-3*s,y,6*s,s);c.fillRect(x-2*s,y+s,4*s,s);c.fillRect(x-s,y+2*s,2*s,s)};
 const sprite=(p,key,scale=1,enemy=false)=>{const q=playerPose(p,p.x,p.y);if(!enemy){drawRedGhosts162(c,p,p.x,p.y,planeSprite,key);drawPlayerAura(c,p,q.x,q.y);}planeSprite(c,q.x+14,q.y+20,p.a,key,scale*q.scale,enemy,true);planeSprite(c,q.x,q.y,p.a,key,scale*q.scale,enemy,false,p.hitFlash||0)};
 for(const gas of g.gasZones){c.fillStyle=gas.warning>0?'#d6b74722':'#72842e55';c.beginPath();c.arc(gas.x,gas.y,gas.r,0,Math.PI*2);c.fill();ring(gas.x,gas.y,gas.r,'#d6c66b');c.fillStyle='#f8ebae';c.font='14px sans-serif';c.textAlign='center';c.fillText(gas.warning>0?'독가스 살포 '+gas.warning.toFixed(1)+'초':'독가스 · 조종 저하 / 지속 피해',gas.x,gas.y-gas.r-12)}
 for(const field of g.hostileMinefields){ring(field.x,field.y,field.radius,field.warning>0?'#ffe0a199':'#e58b6c88');for(const m of field.mines)if(!m.dead){if(!fx(c,'mine',m.x,m.y,60,60))drawEquipment(c,'mine',m.x,m.y,0,56);ring(m.x,m.y,18,'#ff876e')}}
 for(const d of g.drops){if(d.dead)continue;if(d.specialAmmo){ring(d.x,d.y,24+Math.sin(t*6)*3,SPECIAL_AMMO[d.specialAmmo]?.color||'#ffd36f',2);drawSpecialAmmoIcon(c,d.specialAmmo,d.x,d.y+Math.sin(t*4)*2,42)}else if(d.heal||d.supply){ring(d.x,d.y,22+Math.sin(t*5)*3,'#9cffb4');drawEquipment(c,'repair',d.x,d.y+Math.sin(t*3)*2,0,40)}else{if(xpGem?.naturalWidth)c.drawImage(xpGem,d.x-9,d.y-9,18,18);else{c.fillStyle='#63d5ec';c.fillRect(d.x-3,d.y-3,6,6)}}}
 for(const grenade of g.grenades||[])drawGrenade(c,grenade,grenade.x,grenade.y);for(const m of g.mines){if(!fx(c,'mine',m.x,m.y,60,60))drawEquipment(c,'mine',m.x,m.y,0,60);if(m.legendary||m.arm===0)ring(m.x,m.y,22+Math.sin(t*5)*3,m.legendary?'#ffd56f99':'#ffcc6677')}
 for(const e of g.enemies){
  if(e.stageBossBody)continue;
  if(e.crashing){const key=e.escortPlane||e.bossPlane||(e.faction==='entente'?(e.type==='hunter'?'nieuport':'camel'):(e.type==='hunter'?'fokker_standard':'albatros'));sprite(e,key,enemyAircraftScale(e),true);continue}
  if(e.hp<=0)continue;
  if(e.groundEscort)drawBattlefieldSprite(c,'aa',e.x,e.y,96,e.a+Math.PI/2);
  else if(e.fieldUnit){if(e.rail){const r=e.rail;c.save();c.translate(r.x,r.y);c.rotate(r.angle);c.strokeStyle='#bec1ab';c.lineWidth=3;for(const off of [-8,8]){c.beginPath();c.moveTo(-r.half-25,off);c.lineTo(r.half+25,off);c.stroke()}c.restore()}drawBattlefieldSprite(c,e.fieldSprite,e.x,e.y,e.rail?210:354,e.rail?e.rail.angle+Math.PI/2:0)}
  else if(e.navalVessel)drawBattlefieldSprite(c,'ship',e.x,e.y,320,e.a+Math.PI/2);
  else if(e.heavyBomber){const im=fieldArt[e.airframe],w=e.airframe==='staaken'?178:158;if(im?.naturalWidth)drawFieldArt(e.airframe,e.x,e.y,w,w*im.naturalHeight/im.naturalWidth,e.a+Math.PI/2,e.hitFlash>0?.65:1)}
  else if(e.type==='zeppelin')drawZeppelin(c,e.x,e.y,e.a,.92,e.hitFlash>0,e.faction);
  else{const key=e.escortPlane||e.bossPlane||(e.faction==='entente'?(e.type==='hunter'?'nieuport':'camel'):(e.type==='hunter'?'fokker_standard':'albatros'));sprite(e,key,enemyAircraftScale(e),true)}
  if(e.aceInvuln124>0)ring(e.x,e.y,42+Math.sin(t*20)*4,'#35253d',2);
  if(e.vossSurge){const n2=Math.min(7,Math.max(3,e.vossSurgeCount||3));ring(e.x,e.y,50,'rgba(255,222,140,.4)',1.5);for(let i=0;i<n2;i++){const ga=t*2.3+i*Math.PI*2/n2;c.fillStyle=i%2?'#ffe6a2':'#cfe6ff';c.beginPath();c.arc(e.x+Math.cos(ga)*50,e.y+Math.sin(ga)*50,3,0,Math.PI*2);c.fill()}}
  if(e.bossPilot||e.fieldUnit||e.heavyBomber||e.type==='zeppelin'){const offset=e.fieldUnit?e.rail?125:190:e.type==='zeppelin'?70:e.bossPilot?42:65;c.fillStyle='#172b23';c.fillRect(e.x-42,e.y-offset,84,5);c.fillStyle='#ed9d66';c.fillRect(e.x-42,e.y-offset,84*Math.max(0,e.hp/e.maxHp),5);c.font='14px sans-serif';c.textAlign='center';c.fillStyle='#ffe3aa';c.fillText(e.name||'비행선',e.x,e.y-offset-8)}
 }
 for(const a of g.allies){sprite(a,a.plane,.78);if(g.player(a.ownerId)?.wingBoost>0)ring(a.x,a.y,28,'#f5e7ad',2)}
 for(const patrol of g.patrols){if(patrol.hp<=0)continue;sprite(patrol,patrol.plane,.9);c.fillStyle='#83dce9';c.fillRect(patrol.x-16,patrol.y+34,32*patrol.hp/patrol.maxHp,3)}
 for(const p of g.players){for(const wing of p.formationWings||[]){c.globalAlpha=wing.alpha||0;sprite(wing,'collishaw_sopwith');c.globalAlpha=1}for(const wing of p.divingSquadron||[])sprite(wing,'se5a');for(const gh of p.immelmannGhosts||[]){const al=Math.min(1,gh.life/gh.maxLife*1.4)*.85;c.save();c.translate(gh.x,gh.y);c.rotate(gh.a);c.globalAlpha=al;c.strokeStyle='#2b3442';c.lineWidth=4.5;c.lineCap='round';c.beginPath();c.moveTo(-21,-7);c.quadraticCurveTo(-7,-22,16,-8);c.moveTo(-21,7);c.quadraticCurveTo(-7,22,16,8);c.moveTo(-21,-7);c.lineTo(-21,7);c.stroke();c.fillStyle='#2b3442';c.beginPath();c.ellipse(-9,0,12,3.6,0,0,Math.PI*2);c.fill();c.restore()}
   if(p.pilot==='rickenbacker'&&(p.rickActive||p.skillTime)>0){const ph=t*3.1,ea=.32;c.save();c.globalAlpha=.8;c.strokeStyle='rgba(255,226,140,.85)';c.lineWidth=2;c.beginPath();c.ellipse(p.x,p.y,58,30,ea,0,Math.PI*2);c.stroke();c.globalAlpha=.22;c.lineWidth=1;c.beginPath();c.ellipse(p.x,p.y,58,30,ea,0,Math.PI*2);c.stroke();c.restore()}
   if(p.loewenhardtEngaged){const pulse=.55+.35*Math.sin(t*9);c.save();c.globalAlpha=.85;c.strokeStyle=`rgba(255,214,74,${pulse})`;c.lineWidth=2.5;c.beginPath();c.arc(p.x,p.y,36,p.a-Math.PI/2.8,p.a+Math.PI/2.8);c.stroke();c.lineWidth=1.4;c.beginPath();c.arc(p.x,p.y,44,p.a-Math.PI/4,p.a+Math.PI/4);c.stroke();c.restore()}
   if(p.fxOverheat>0){c.save();c.globalAlpha=.55*p.fxOverheat;const nx=p.x+Math.cos(p.a)*14,ny=p.y+Math.sin(p.a)*14;c.fillStyle='#ff8a3c';c.beginPath();c.arc(nx,ny,7+Math.sin(t*30)*2.4,0,Math.PI*2);c.fill();c.fillStyle='#ffd27a';c.beginPath();c.arc(nx,ny,3.4,0,Math.PI*2);c.fill();c.restore()}
   if(p.ballCloak>0&&ballCloudSprite.naturalWidth){const fade=Math.min(1,p.ballCloak*3);c.save();for(let i=0;i<7;i++){const ga=t*.5+i*.9,rr=10+((i*53)%26),sc=.16+(i*29)%10*.014;c.globalAlpha=.5*fade*(i%2?.85:1);c.save();c.translate(p.x+Math.cos(ga)*rr,p.y+Math.sin(ga)*rr*.75);c.rotate(ga*.4);c.drawImage(ballCloudSprite,-160*sc,-100*sc,320*sc,200*sc);c.restore()}c.restore()}
   if(p.pilot==='fonck'&&p.muzzleFlash>0){c.save();const nx=p.x+Math.cos(p.a)*30,ny=p.y+Math.sin(p.a)*30;c.globalAlpha=.85;c.strokeStyle='#ffe08a';c.lineWidth=1.5;c.beginPath();c.arc(nx,ny,6.5,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(nx-10,ny);c.lineTo(nx+10,ny);c.moveTo(nx,ny-10);c.lineTo(nx,ny+10);c.stroke();c.restore()}
   if(p.pilot==='baracca'&&(g.enemies||[]).some(e=>{if(e.hp<=0)return false;const d=(e.x-p.x)**2+(e.y-p.y)**2;return d<520*520&&Math.abs(Math.atan2(Math.sin(Math.atan2(e.y-p.y,e.x-p.x)-p.a),Math.cos(Math.atan2(e.y-p.y,e.x-p.x)-p.a)))<Math.PI/3})){c.save();const pulse=.6+.3*Math.sin(t*10);c.globalAlpha=.8;c.strokeStyle=`rgba(224,58,42,${pulse})`;c.lineWidth=2.6;c.beginPath();c.arc(p.x,p.y,44,p.a-Math.PI/3,p.a+Math.PI/3);c.stroke();c.lineWidth=1.2;c.strokeStyle=`rgba(255,214,150,${pulse})`;c.beginPath();c.arc(p.x,p.y,52,p.a-Math.PI/4,p.a+Math.PI/4);c.stroke();c.restore()}
   if(p.pilot==='immelmann'&&p.weapon?.guns===1&&p.muzzleFlash>0){c.save();const nx=p.x+Math.cos(p.a)*30,ny=p.y+Math.sin(p.a)*30;c.globalAlpha=.9;c.fillStyle='#ff9a3c';c.beginPath();c.arc(nx,ny,9+Math.sin(t*40)*2,0,Math.PI*2);c.fill();c.fillStyle='#fff1c0';c.beginPath();c.arc(nx,ny,4,0,Math.PI*2);c.fill();c.restore()}
   if(p.pilot==='immelmann'&&(p.eagleTime||0)>0){c.save();const f=Math.min(1,p.eagleTime);c.globalAlpha=.5+.3*Math.sin(t*14);c.strokeStyle='#7fd4ff';c.lineWidth=2.4;c.beginPath();c.arc(p.x,p.y,40,p.a-Math.PI/2-.9,p.a-Math.PI/2+.9);c.stroke();c.globalAlpha=.85*f;c.strokeStyle='#cfeeff';c.lineWidth=1.3;c.beginPath();c.arc(p.x,p.y,34,p.a-Math.PI/2-.65,p.a-Math.PI/2+.65);c.stroke();c.restore()}
   if(p.pilot==='jacobs'&&(p.jacobsStacks||0)>0){c.save();for(let i=0;i<p.jacobsStacks;i++){const ga=t*2.4+i*Math.PI*2/3+.6,ox=p.x+Math.cos(ga)*34,oy=p.y+Math.sin(ga)*34+Math.sin(t*6+i)*2;c.globalAlpha=.92;c.save();c.translate(ox,oy);c.rotate(ga+Math.PI/2);c.fillStyle='#1c1410';c.beginPath();c.arc(0,-2,4.4,0,Math.PI*2);c.fill();c.beginPath();c.moveTo(-3.6,-4.5);c.lineTo(-6.5,-10.5);c.lineTo(-1,-6.5);c.closePath();c.moveTo(3.6,-4.5);c.lineTo(6.5,-10.5);c.lineTo(1,-6.5);c.closePath();c.fill();c.beginPath();c.moveTo(-3.4,1.5);c.quadraticCurveTo(-7.5,5,-5,9);c.lineTo(0,6.5);c.lineTo(5,9);c.quadraticCurveTo(7.5,5,3.4,1.5);c.closePath();c.fill();c.fillStyle='#ff4a3a';c.beginPath();c.arc(-1.5,-2.6,1,0,Math.PI*2);c.arc(1.5,-2.6,1,0,Math.PI*2);c.fill();c.restore()}c.restore()}
   if(p.pilot==='bishop'&&(g.enemies||[]).some(e=>e.hp>0&&(e.x-p.x)**2+(e.y-p.y)**2<300*300)){c.save();c.globalAlpha=.55;c.setLineDash([7,7]);c.strokeStyle='#e04a3a';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,300,0,Math.PI*2);c.stroke();c.setLineDash([]);c.restore()}
   if(p.pilot==='mannock'){const wings=(g.allies||[]).filter(a=>a.life>0);if(wings.length){c.save();c.globalAlpha=.75;wings.forEach((a,i)=>{const ga=t*3+i*2.1;c.fillStyle=i%2?'#9ff0b0':'#6fd08a';c.beginPath();c.arc(a.x+Math.cos(ga)*20,a.y+Math.sin(ga)*20,2.6,0,Math.PI*2);c.fill();c.strokeStyle='rgba(140,240,170,.5)';c.lineWidth=1;c.beginPath();c.arc(a.x,a.y,14+Math.sin(t*5+i)*3,0,Math.PI*2);c.stroke()});c.restore()}}
   if(p.pilot==='barker'&&(p.barkerStacks||0)>0){c.save();const n=p.barkerStacks;c.globalAlpha=.9;for(let i=0;i<n;i++){const oy=p.y-34-i*9;c.fillStyle=i%2?'#ff7a5a':'#e0442e';c.beginPath();c.moveTo(p.x-8,oy);c.lineTo(p.x,oy-6);c.lineTo(p.x+8,oy);c.lineTo(p.x+8,oy+4);c.lineTo(p.x,oy-2);c.lineTo(p.x-8,oy+4);c.closePath();c.fill()}c.restore()}
   if(p.pilot==='boelcke'){const near=(g.allies||[]).filter(a=>a.life>0&&(a.x-p.x)**2+(a.y-p.y)**2<360*360);if(near.length){c.save();c.globalAlpha=.5;c.setLineDash([4,9]);c.strokeStyle='#a8e6c8';c.lineWidth=1.6;c.beginPath();c.arc(p.x,p.y,360,0,Math.PI*2);c.stroke();c.setLineDash([]);near.forEach((a,i)=>{c.globalAlpha=.85;c.strokeStyle='#cfe8d8';c.lineWidth=1.6;c.beginPath();c.moveTo(a.x-4.5,a.y);c.lineTo(a.x+4.5,a.y);c.moveTo(a.x,a.y-6);c.lineTo(a.x,a.y+6);c.stroke();c.strokeStyle='#24302a';c.lineWidth=.8;c.beginPath();c.moveTo(a.x-4.5,a.y-1.5);c.lineTo(a.x+4.5,a.y-1.5);c.moveTo(a.x-4.5,a.y+1.5);c.lineTo(a.x+4.5,a.y+1.5);c.stroke()});c.restore()}}
   if(p.pilot==='voss'){const n=(g.enemies||[]).filter(e=>e.hp>0&&(e.x-p.x)**2+(e.y-p.y)**2<400*400).length;if(n>=2){c.save();const m=Math.min(6,n);c.globalAlpha=.75;for(let i=0;i<m;i++){const ga=t*2.6+i*Math.PI*2/m+.4;c.fillStyle=i%2?'#ff9a7a':'#e0523a';c.beginPath();c.arc(p.x+Math.cos(ga)*44,p.y+Math.sin(ga)*44,2.8,0,Math.PI*2);c.fill()}c.restore()}}
   if(p.pilot==='luke'||p.pilot==='gontermann'){const heavy=(g.enemies||[]).filter(e=>e.hp>0&&(e.heavyBomber||e.zeppelin||e.boss||e.ace||e.big||e.stageBossBody||e.navalVessel||e.fieldUnit||e.type==='boss')&&(e.x-p.x)**2+(e.y-p.y)**2<700*700);if(heavy.length){c.save();heavy.slice(0,4).forEach((e,i)=>{const r=(e.r||18)+13+Math.sin(t*6+i)*3;if(p.pilot==='luke'){c.globalAlpha=.85;c.strokeStyle='#ffb43c';c.lineWidth=2;c.save();c.translate(e.x,e.y);c.rotate(t*1.5);c.beginPath();c.moveTo(0,-r);c.lineTo(r,0);c.lineTo(0,r);c.lineTo(-r,0);c.closePath();c.stroke();c.restore()}else{c.globalAlpha=.8;for(let j=0;j<3;j++){const ga=t*2+j*2.1;c.fillStyle=j%2?'#ff8a3c':'#ffce6a';c.beginPath();c.arc(e.x+Math.cos(ga)*r*.7,e.y+Math.sin(ga)*r*.7,2.4,0,Math.PI*2);c.fill()}}});c.restore()}}
   for(const ship of p.airshipFleet||[])if(ship.age>=0&&ship.age<6)drawZeppelin(c,ship.x,ship.y,ship.a,ship.scale||.825,false,'central')}
 for(const b of g.friendlyBombers){const im=fieldArt[b.airframe];if(im?.naturalWidth)drawFieldArt(b.airframe,b.x,b.y,150,150*im.naturalHeight/im.naturalWidth,b.a+Math.PI/2)}
 for(const b of g.friendlyBombs){const f=1-b.life/b.maxLife;if(!fx(c,'bomb',b.sx+(b.x-b.sx)*f,b.sy+(b.y-b.sy)*f,40,20,Math.atan2(b.y-b.sy,b.x-b.sx)))drawEquipment(c,'rocket',b.sx+(b.x-b.sx)*f,b.sy+(b.y-b.sy)*f,Math.atan2(b.y-b.sy,b.x-b.sx)+Math.PI/2,38);ring(b.x,b.y,22,'#a2eddb70')}
 for(const b of g.bullets){if(b.life<=0)continue;if(b.enemy){drawEnemyProjectile(c,b,b.x,b.y,t);if(b.hostileRocket){c.save();c.translate(b.x,b.y);c.rotate(Math.atan2(b.vy,b.vx));c.fillStyle='#f2a144';c.beginPath();c.moveTo(-14,0);c.lineTo(-26,-4);c.lineTo(-26,4);c.closePath();c.fill();c.fillStyle='#4a3f30';c.beginPath();c.ellipse(0,0,14,4.5,0,0,Math.PI*2);c.fill();c.fillStyle='#8a2f22';c.beginPath();c.ellipse(9,0,4.5,3.4,0,0,Math.PI*2);c.fill();c.restore()}}else if(b.rocket){if(!fx(c,'rocket',b.x,b.y,52,16,Math.atan2(b.vy,b.vx)))drawEquipment(c,'rocket',b.x,b.y,Math.atan2(b.vy,b.vx)+Math.PI/2,48)}else if(b.motorCannon||b.cow37){drawCannonProjectile(c,b,b.x,b.y)}else if(b.fonckSeeker){c.save();c.translate(b.x,b.y);c.rotate(Math.atan2(b.vy,b.vx));if(!fx(c,'tracerCream',-6,0,46,10)){c.fillStyle='#fff0ad';c.fillRect(-22,b.motorCannon?-7:-3,b.motorCannon?45:30,b.motorCannon?14:6);c.fillStyle='#bd8745';c.fillRect(-15,-7,6,b.motorCannon?14:6)}c.restore()}else{const bc=(b.mauserRound?'#a98cff':b.eagle?'#9fdcff':b.specialColor)||(b.formation||b.ally?'#b9f2de':b.pierce?'#f8f5cd':friendlyTracerColor(b,g.gunUpgradeBonus)),bw=b.specialAmmo?4:b.formation||b.ally?4:2;c.strokeStyle=bc;c.lineWidth=bw;c.beginPath();c.moveTo(b.x,b.y);c.lineTo(b.x-b.vx*(b.specialAmmo==='tracer'?.032:.018),b.y-b.vy*(b.specialAmmo==='tracer'?.032:.018));c.stroke()}}
 for(const zone of g.bombZones){const progress=1-zone.delay/zone.maxDelay;c.fillStyle='#ff3c202a';c.beginPath();c.arc(zone.x,zone.y,zone.radius,0,Math.PI*2);c.fill();ring(zone.x,zone.y,zone.radius,'#ff855a');ring(zone.x,zone.y,Math.max(0,zone.radius*(1-progress)),'#ff855a')}
 for(const fxf of g.combatFX){const f=1-fxf.life/fxf.maxLife;if(fxf.amatol){drawAmatolBlast(c,fxf,fxf.x,fxf.y);continue}if(fxf.grenade){drawGrenadeBlast(c,fxf,fxf.x,fxf.y);continue}if(!drawFxExplosion(c,fxf,fxf.x,fxf.y))drawFieldArt('flak',fxf.x,fxf.y,fxf.radius*(1+f)*2,fxf.radius*(1+f)*2,0,Math.min(1,fxf.life*3))}
 for(const f of g.flakBursts)drawBattlefieldSprite(c,'aa',f.x,f.y,66);
 for(const gust of g.gusts)drawFieldArt('gust',gust.x,gust.y,gust.radius*2.6,gust.radius*2.6,gust.a+t*.15,Math.max(0,Math.min(.85,gust.life,6-gust.life)));
 for(const particle of g.particles){const smokeLife=particle.smoke?Math.max(0,particle.life/particle.maxLife):0;c.globalAlpha=particle.smoke?smokeLife*(particle.muzzleSmoke?.88:.65):Math.min(1,particle.life*3);if(particle.petal){drawPetalParticle(c,particle,particle.x,particle.y);continue}if(particle.heart){heart(particle.x,particle.y,particle.size,particle.color);continue}c.fillStyle=particle.color;const size=particle.smoke?particle.size+(1-smokeLife)*(particle.muzzleSmoke?15:10):3;
  if(!particle.smoke&&fxReady('spark')){fxTint(c,'spark',particle.color,particle.x,particle.y,size*4,size*4);continue}
  if(particle.smoke){const lum=parseInt(particle.color?.slice(1,3)||'88',16),sKey=particle.muzzleSmoke?'smokePuff':lum<110?'smokeDark':lum>170?'smokeWisp':'smokeGray';if(fx(c,sKey,particle.x,particle.y,size*2.4,size*2.4)){c.globalAlpha=1;continue}}
  c.fillRect(particle.x-size/2,particle.y-size/2,size,size)}c.globalAlpha=1;
 for(const p of g.players){if(p.status!=='alive')continue;
  if(p.isRedHunter()&&p.skillTime>0){c.save();c.translate(p.x,p.y);c.rotate(p.a);if(fxReady('sunshaft')){for(let i=0;i<5;i++){const a=(i/4*2-1)*SUN_STRIKE.halfAngle*.9,L=SUN_STRIKE.range*.8;fx(c,'sunshaft',Math.cos(a)*L*.5-30,Math.sin(a)*L*.5,L,140+((i*53)%80),a,.5);}}else{c.fillStyle='#ffe8b330';c.beginPath();c.moveTo(0,0);c.arc(0,0,SUN_STRIKE.range,-SUN_STRIKE.halfAngle,SUN_STRIKE.halfAngle);c.closePath();c.fill();}c.restore()}
  if(p.skillTime>0&&!['nungesser','berthold','wolff'].includes(p.pilot))ring(p.x,p.y,35+Math.sin(t*10)*4,'#ffe2a4',1);
  if(p.chargeTime>0||p.upgrades.redScarf){c.strokeStyle=p.chargeTime>0?'#ffe3a680':'#d6f6efa8';c.lineWidth=2;for(const off of [-24,24]){const x=p.x-Math.sin(p.a)*off,y=p.y+Math.cos(p.a)*off,len=p.chargeTime>0?150:70;c.beginPath();c.moveTo(x,y);c.lineTo(x-Math.cos(p.a)*len,y-Math.sin(p.a)*len);c.stroke()}}
  c.globalAlpha=p.invuln>0&&Math.floor(t*15)%2?.55:1;sprite(p,aircraftKey(p.plane,false,p.pilot));c.globalAlpha=1;const color=p.id==='p1'?'#74d9fb':'#ffcd78';ring(p.x,p.y,39,color,1.5);c.fillStyle=color;c.textAlign='center';c.font='bold 14px sans-serif';c.fillText(p.id.toUpperCase(),p.x,p.y+54);
 if(p.muzzleFlash>0&&p.reloadTime===0)for(let gun=0;gun<p.weapon.guns;gun++){const ga=p.gunDirection(gun),mx=p.x+Math.cos(ga)*27,my=p.y+Math.sin(ga)*27;if(!fx(c,'muzzle',mx+Math.cos(ga)*6,my+Math.sin(ga)*6,16,16,ga)){c.fillStyle='#fff4ca';c.fillRect(mx-2,my-2,5,5)}}
 }
 for(const p of g.players){if(p.status!=='alive'||!p.tailTargetId)continue;const e=g.enemies.find(e=>e.hp>0&&e.tailId===p.tailTargetId);if(!e)continue;const progress=p.tailLockFraction(),color=p.id==='p1'?'#74d9fb':'#ffcd78';c.strokeStyle=p.tailLocked?'#ff7258':color;c.lineWidth=p.tailLocked?3:2;c.beginPath();c.arc(e.x,e.y,38,-Math.PI/2,-Math.PI/2+Math.PI*2*progress);c.stroke();c.fillStyle=p.tailLocked?'#fff0c0':color;c.font='bold 12px sans-serif';c.textAlign='center';c.fillText(p.tailLocked?'꼬리 우위 ×'+TAILING_BALANCE.damageMultiplier.toFixed(2):p.id.toUpperCase()+' 후방 '+Math.round(progress*100)+'%',e.x,e.y-48)}
 c.restore();c.font='14px sans-serif';c.textAlign='left';c.fillStyle='#f1edd0';c.fillText(['전원 지대','아드리아해','참호 전선','도심','고공 전역'][g.region]+' · 팀 비행 '+(g.distance/1000).toFixed(1)+' km',14,H-14);
}
