import {preparePersonalRound1918,barkerDamage1918,advancePersonal1918,advanceBurns1918} from './pilot-lifecycle196.js?v=331';
import {Game,PLANES,PILOTS,PILOT_PLANES,UPGRADES,LEGENDARIES,WEAPONS,angleDiff,highRiskDamage,PILOT_BALANCE,DURABILITY_BALANCE,LEGENDARY_BALANCE,GOERING_WING_BOOST,ENEMY_BOSS_BALANCE,SUN_STRIKE,SPECIAL_AMMO,tickLegendaryDefenses,COW37_BALANCE,ENEMY_MOVEMENT_BALANCE} from './engine.js?v=331&b=326';

import {enableStageBoss,beginStageBossFrame,endStageBossFrame,stageBossSpeed,stageSpawnInterval,damageStageBoss} from './stageboss-host.js?v=331&b=326';
import {attachAircraftPersonality} from './aircraft-personality164.js?v=331';
import {installCloudCover} from './cloud-cover1.js?v=331&b=326';

// A single world owns simulation time, entities and deaths. PlayerState never calls Game.update.
export const COOP_BALANCE=Object.freeze({spawn:1,ordinaryHp:1.15,heavyHp:1.65,enemyCap:28,xp:.6,revive:15,reviveHp:1,reviveAmmo:.5,reviveInvuln:2,minZoom:.75});
export const coopPlane=pilot=>({baron:'fokker',voss:'fokker',...PILOT_PLANES}[pilot]||'fokker').replace('fokker_red','fokker').replace('fokker_voss','fokker').replace('fokker_jacobs','fokker');
const live=p=>p?.status==='alive'&&p.hp>0;
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const stepTimer=(p,key,dt)=>p[key]=Math.max(0,(p[key]||0)-dt);
const squared=(a,b)=>(a.x-b.x)**2+(a.y-b.y)**2;
const segmentDistance=(x,y,x0,y0,x1,y1)=>{const dx=x1-x0,dy=y1-y0,t=clamp(((x-x0)*dx+(y-y0)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(x-x0-dx*t,y-y0-dy*t)};

export class PlayerState {
 constructor(world,id,{nickname,pilot,plane=coopPlane(pilot)}){
  const fit=PLANES[plane];this.world=world;this.id=id;this.nickname=String(nickname||id.toUpperCase()).trim().slice(0,12)||id.toUpperCase();this.pilot=pilot;this.plane=plane;
  Object.assign(this,{status:'alive',x:id==='p1'?-55:55,y:0,a:-Math.PI/2,speed:fit.speed*1.18,turn:fit.turn*1.12*.72,maxHp:fit.hp,hp:fit.hp,weapon:{...WEAPONS[plane]},damage:12,shots:1,rockets:0,mineCount:0,rocketFire:1.8,mineTimer:3,magnet:120,cooldownMult:1,level:1,xp:0,baseLevelNeed:6,xpCostMultiplier:fit.xpCostMultiplier??1,upgrades:{},reloadTime:0,roundsFired:0,muzzleFlash:0,fire:0,cooldown:0,evadeCooldown:0,evadeTime:0,evadeDirection:1,skillTime:0,invuln:1.5,hitFlash:0,smokeTimer:0,respawnRemaining:0,distance:0,kills:0,formationWings:[],divingSquadron:[],airshipFleet:[]});
  this.rate=60/this.weapon.rpm;this.ammo=Array(this.weapon.guns).fill(this.weapon.belt);this.need=this.levelRequirement(6);
  this.doctrine=['강습 편대','고속 정찰','장기 초계'][Math.floor(this.rng()*3)];
  if(this.doctrine==='강습 편대'){this.damage*=1.15;this.reloadPenalty=1.15}else if(this.doctrine==='고속 정찰'){this.speed*=1.12;this.maxHp*=.9;this.hp=this.maxHp}else{this.maxHp+=15;this.hp=this.maxHp;this.rate*=1.08}
  if(pilot==='bishop')this.damage*=1.8;
  this.permanentWingman=pilot==='goering'?1:0;this.allyPlane=fit.faction==='central'?'fokker_standard':'camel';this.baseSpeed=this.speed;this.enemyCruiseReference=this.speed;this.ensureRevisionPilot();
 }
 get rng(){return this.world.rng} get t(){return this.world.t}
 get state(){return this.world.state} set state(_value){/* A personal upgrade cannot resume the shared world. */}
 get bullets(){return this.world.bullets} set bullets(value){this.world.bullets=value}
 get enemies(){return this.world.enemies} get viewWidth(){return this.world.viewWidth/this.world.camera.zoom} get viewHeight(){return this.world.viewHeight/this.world.camera.zoom}
 get shake(){return this.world.shake} set shake(value){this.world.shake=value}
 event(type,text){this.world.events.push({type,text,ownerId:this.id,pilot:this.pilot,plane:this.plane,nickname:this.nickname})}
 burst(...args){this.world.burst(...args)} smoke(...args){this.world.smoke(...args)} combatBlast(...args){this.world.combatBlast(...args)}
 checkLevel(){/* Growth is committed once by the world's ordered queue. */}
}
// Reuse authored abilities and upgrade rules, not any legacy world-update wrapper.
for(const method of ['launchUpgradeRocket','ensureRevisionPilot','beginRevisionFrame','endRevisionFrame','incomingDamageMultiplier','skill','evade','reload','upgrade','addGunBonus','addMobility','rollChoices','rerollChoices','canRerollChoices','rerollLegendaryChoices','legendaryChance','legendaryCount','levelRequirement','payloadPower','supportPower','skillCooldown','skillDuration','skillRecovery','normalGunMultiplier','blackFlightAim','isRedHunter','shotLifetime','healthSpeedFactor','flyAirframe','duoVolley','legendaryDamageMultiplier','sunStrikeContains','combatWorld','inSmoke','tailEligible','tailIdFor','updateTailLock','tailLockFraction','giveSpecialAmmo','consumeSpecialRound','specialAmmoStatus','applySpecialRound','roundDamageMultiplier','specialRoundImpact','tickAugmentationSystems','augmentationDescription','guideTelescope','gunDirection','throwGrenades','tickGrenades','ordnanceInterval','explosionRadius','explosionDamage','queueExplosionDamage','spawnAmatolSecondary','cannonMuzzleSmoke','permanentWingPlane','permanentWingCount','lufberyDamageMultiplier','wingFormationOffset','wingFormationTarget','applyFighterSupplyToWings','isDreideckerPilot','huntTargetAlive','huntTier','pickHuntTarget','patchEliteHuntDamage'])PlayerState.prototype[method]=Game.prototype[method];

export class CoopGame {
 constructor(config,{rng=Math.random,runId=globalThis.crypto?.randomUUID?.()||`coop-${Date.now()}-${Math.random().toString(36).slice(2)}`}={}){
  if(!Array.isArray(config)||config.length!==2||config.some(p=>!PILOTS[p.pilot]))throw Error('파일럿 두 명을 선택하세요.');
  const faction=PILOTS[config[0].pilot].faction;if(config.some(p=>PILOTS[p.pilot].faction!==faction||!PLANES[p.plane||coopPlane(p.pilot)]||PLANES[p.plane||coopPlane(p.pilot)].faction!==faction))throw Error('같은 진영만 함께 출격할 수 있습니다.');
  Object.defineProperty(this,'mode',{value:'coop2',enumerable:true});this.teamFaction=faction;this.runId=runId;this.rng=rng;this.state='playing';this.manualPaused=false;
  this.t=0;this.distance=0;this.kills=0;this.priorityKills=0;this.score=0;this.worldTicks=0;this.shake=0;this.nextEntityId=1;
  for(const key of ['enemies','bullets','drops','mines','allies','particles','events','patrols','bombZones','friendlyBombers','friendlyBombs','combatFX','gusts','flakBursts','hostileMinefields','gasZones','pendingLevelUps'])this[key]=[];
  this.activeUpgrade=null;this.upgradeSequence=0;this.spawnBudget=0;this.spawn=0;this.flakTimer=24;this.supplyTimer=62;this.eventTimer=18+rng()*10;this.nextBossAt=80;this.nextHeavyAt=65;this._zeppelinSchedule=65;this.regionThreat=20;this.fieldUnitTimer=34;this.gasTimer=12;this.gustTimer=36+rng()*18;this.region=0;this.wave=0;
  this.viewWidth=960;this.viewHeight=700;this.camera={x:0,y:0,zoom:1};this.players=config.map((p,i)=>new PlayerState(this,`p${i+1}`,p));
  this.plane=this.players[0].plane;this.enemyCruiseReference=Math.min(...this.players.map(p=>p.enemyCruiseReference));
  this.events.push({type:'wave',text:'2인 협동 출격 · 서로의 꼬리를 지켜주세요'});this.ensureWingmen();
 }
 get x(){return this.camera.x} get y(){return this.camera.y} get a(){return this.players.find(live)?.a??-Math.PI/2} get speed(){return this.enemyCruiseReference}
 get teamKills(){return this.kills} get teamPriorityKills(){return this.priorityKills} get teamDistance(){return this.distance}
 event(type,text){this.events.push({type,text})}
 player(id){return this.players.find(p=>p.id===id)}
 living(){return this.players.filter(live)}
 action(id,action){const p=this.player(id);if(this.state!=='playing'||!p||!live(p)||!['skill','evade','reload'].includes(action))return false;const used=p[action]();this.tagSummons(p);return used}
 pause(){if(this.state==='lost')return;this.manualPaused=true;if(!this.activeUpgrade)this.state='paused'}
 resume(){if(this.state==='lost'||this.activeUpgrade||this.pendingLevelUps.length)return false;this.manualPaused=false;this.state='playing';return true}
 tagSummons(p){for(const key of ['formationWings','divingSquadron','airshipFleet'])for(const unit of p[key]||[])unit.ownerId=p.id}
 emit(p,b){preparePersonalRound1918(p,b);b.ownerId=p.id;b.enemy=false;b.hit??=new Set();if(p.longRange&&!b.rangeExtended&&Math.hypot(b.vx,b.vy)>0){b.life=Math.max(b.life,p.shotLifetime(Math.hypot(b.vx,b.vy)));b.rangeExtended=true}this.bullets.push(b);return b}
 blast(p,x,y,radius,damage){p?.queueExplosionDamage(x,y,radius,damage)}
 ensureWingmen(){for(const p of this.players){if(!live(p))continue;let active=p.permanentWingCount();while(active<(p.permanentWingman||0)){const slot=active++,target=p.wingFormationTarget({slot},p.permanentWingman);this.allies.push({ownerId:p.id,slot,permanent:true,life:1e9,x:target.x,y:target.y,a:p.a,fire:.18,plane:p.permanentWingPlane()})}}for(const a of this.allies)attachAircraftPersonality(PLANES,a,a.plane)}
 hitPlayer(p,damage,{gas=false}={}){
  if(!live(p)||p.invuln>0||this.state==='lost')return false;p.hp=Math.max(0,p.hp-barkerDamage1918(p,damage*p.incomingDamageMultiplier(p.damageSource)));p.invuln=gas?0:.75;p.hitFlash=.16;this.shake=7;p.smoke(p.x,p.y,true);p.burst(p.x,p.y,'#ffce8e',9);p.event('hit','');
  if(p.hp<=0)this.downPlayer(p);return true;
 }
 downPlayer(p){
  if(p.status==='downed')return;p.status='downed';p.hp=0;p.respawnRemaining=COOP_BALANCE.revive;p.downedCooldown=Math.max(p.cooldown,5);
  for(const key of ['skillTime','chargeTime','bishopTime','bishopDrops','salvoWaves','udetBoost','wingBoost','evadeTime','invuln','muzzleFlash','crossfireFlash','barkerStacks','barkerStackTime','ballCloak','ballAmbush'])p[key]=0;p.ballGhost=null;
  p.formationWings=[];p.divingSquadron=[];p.airshipFleet=[];p.mannockPass=0;p.mannockPassTimer=Infinity;
  this.allies=this.allies.filter(a=>a.ownerId!==p.id);this.friendlyBombers=this.friendlyBombers.filter(b=>b.ownerId!==p.id);
  p.event('downed',`${p.id.toUpperCase()} 격추 · 동료가 15초 생존하면 복귀`);if(!this.living().length)this.finish();
 }
 finish(){if(this.state==='lost')return;this.state='lost';this.stageBoss?.dispose();this.pendingLevelUps=[];this.activeUpgrade=null;this.score=this.priorityKills;this.event('end','두 기체 모두 격추 · 협동 작전 종료')}
 revive(p){const partner=this.living()[0];if(!partner||this.state==='lost')return;const side=p.id==='p1'?-1:1;p.x=partner.x-Math.sin(partner.a)*55*side;p.y=partner.y+Math.cos(partner.a)*55*side;p.a=partner.a;p.status='alive';p.hp=p.maxHp*COOP_BALANCE.reviveHp;p.ammo.fill(Math.floor(p.weapon.belt*COOP_BALANCE.reviveAmmo));p.invuln=COOP_BALANCE.reviveInvuln;p.cooldown=Math.max(p.downedCooldown,5);p.reloadTime=0;p.fire=.1;p.respawnRemaining=0;p.gasExposure=0;p.gustDisorient=0;p.event('revived',`${p.id.toUpperCase()} 전선 복귀`);this.ensureWingmen()}
 awardXp(value){if(this.state==='lost'||!Number.isFinite(value)||value<=0)return;for(const p of this.players)p.xp+=value*COOP_BALANCE.xp*(p.xpGainMult||1);this.queueLevels()}
 queueLevels(){
  if(this.state==='lost')return;let advanced=true;
  while(advanced){advanced=false;for(const p of this.players)if(p.xp+1e-9>=p.need){p.xp=Math.max(0,p.xp-p.need);p.level++;p.baseLevelNeed=Math.ceil(p.baseLevelNeed*1.28);p.need=p.levelRequirement(p.baseLevelNeed);this.pendingLevelUps.push({id:++this.upgradeSequence,playerId:p.id,level:p.level,choices:null});advanced=true}}
  if(this.pendingLevelUps.length&&!this.activeUpgrade)this.openUpgrade();
 }
 openUpgrade(){if(this.state==='lost')return;this.activeUpgrade=this.pendingLevelUps[0]||null;if(!this.activeUpgrade){this.state=this.manualPaused?'paused':'playing';return}this.state='upgrade';const item=this.activeUpgrade,p=this.player(item.playerId);if(!item.choices){const level=p.level;p.level=item.level;try{item.choices=p.rollChoices()}finally{p.level=level}}this.events.push({type:'upgrade',item})}
 chooseUpgrade(itemId,id){const item=this.activeUpgrade;if(this.state!=='upgrade'||!item||item.id!==itemId)return false;const choice=item.choices.find(c=>c.id===id);if(!choice)return false;const p=this.player(item.playerId),prior=p.upgrades[id]||0;p.upgrade(id,choice.rarity);if((p.upgrades[id]||0)===prior)return false;if(!live(p))p.hp=0;this.pendingLevelUps.shift();this.activeUpgrade=null;this.openUpgrade();return true}
 cameraBounds(){const z=this.camera.zoom;return {left:this.x+(-this.viewWidth/2+55)/z, right:this.x+(this.viewWidth/2-55)/z,top:this.y+(-this.viewHeight/2+160)/z,bottom:this.y+(this.viewHeight/2-65)/z}}
 updateCamera(dt){const alive=this.living();if(!alive.length)return;const x=alive.reduce((n,p)=>n+p.x,0)/alive.length,y=alive.reduce((n,p)=>n+p.y,0)/alive.length;const spanX=alive.length===2?Math.abs(alive[0].x-alive[1].x):0,spanY=alive.length===2?Math.abs(alive[0].y-alive[1].y):0;const zoom=clamp(Math.min(this.viewWidth/(spanX+240),this.viewHeight/(spanY+300)),COOP_BALANCE.minZoom,1);this.camera.zoom=zoom<this.camera.zoom?zoom:Math.min(zoom,this.camera.zoom+dt*.6);const k=1-Math.exp(-dt*12);this.camera.x+=(x-this.camera.x)*k;this.camera.y+=(y-this.camera.y)*k;
  // Clamp the camera, never teleport players, when smoothing or zooming in.
  const halfW=this.viewWidth/(2*this.camera.zoom),halfH=this.viewHeight/(2*this.camera.zoom);
  this.camera.x=clamp(this.camera.x,Math.max(...alive.map(p=>p.x))-halfW+55/this.camera.zoom,Math.min(...alive.map(p=>p.x))+halfW-55/this.camera.zoom);
  this.camera.y=clamp(this.camera.y,Math.max(...alive.map(p=>p.y))-halfH+65/this.camera.zoom,Math.min(...alive.map(p=>p.y))+halfH-160/this.camera.zoom);
 }
 constrainMove(p,x0,y0){const bounds=this.cameraBounds();p.x=clamp(p.x,Math.min(bounds.left,x0),Math.max(bounds.right,x0));p.y=clamp(p.y,Math.min(bounds.top,y0),Math.max(bounds.bottom,y0));}
 screenPoint(x,y,width=this.viewWidth,height=this.viewHeight){return [(x-this.x)*this.camera.zoom+width/2,(y-this.y)*this.camera.zoom+height/2]}
 offscreen(){const a=this.a+(this.rng()-.5)*Math.PI*1.4,dx=Math.cos(a),dy=Math.sin(a),w=this.viewWidth/(2*this.camera.zoom)+85,h=this.viewHeight/(2*this.camera.zoom)+85,d=Math.min(w/(Math.abs(dx)||1e-6),h/(Math.abs(dy)||1e-6));return {x:this.x+dx*d,y:this.y+dy*d,a:a+Math.PI}}
 spawnEnemy(type,{scale=true}={}){if(this.enemies.length>=COOP_BALANCE.enemyCap)return null;const before=this.enemies.length;Game.prototype.spawnEnemy.call(this,type);if(this.enemies.length===before)return null;const e=this.enemies.at(-1);e.id=this.nextEntityId++;Object.assign(e,this.offscreen());if(scale)this.scaleEnemyHp(e);return e}
 scaleEnemyHp(e){if(!e||e.coopHpApplied)return e;const mult=e.heavyBomber||e.bossPilot||['boss','zeppelin'].includes(e.type)?COOP_BALANCE.heavyHp:e.surface||e.fieldUnit?1:COOP_BALANCE.ordinaryHp;e.hp*=mult;e.maxHp*=mult;e.coopHpApplied=mult;return e}
 spawnRegular(type){return this.spawnEnemy(type)}
 spawnFlak(){
  if(this.worldRegion()===4)return;
  if(this.t-(this.lastRegionalHazard??-Infinity)<8)return;this.lastRegionalHazard=this.t;const region=this.worldRegion();
  if(region===0){this.spawnMinefield();return}if(region===1){this.spawnFleet();return}
  const origin=this.offscreen();if(this.sunStrikeContains({...origin,hp:1}))return;const target=this.enemyCombatTarget(origin),aim=Math.atan2(target.y-origin.y,target.x-origin.x);
  for(let i=-3;i<=3;i++){const a=aim+i*.12;this.bullets.push({x:origin.x,y:origin.y,vx:Math.cos(a)*190,vy:Math.sin(a)*190,life:4.2,enemy:true,flak:true,hazardRegion:2,targetPlayerId:target.id,damage:Math.round(13*(1+this.t/260))})}
  this.flakBursts.push({x:origin.x,y:origin.y,a:aim,life:7,maxLife:7});this.burst(origin.x,origin.y,'#efb35d',12);this.event('flak','대공포 발사! 탄막을 피하세요');
 }
 reserveEnemySlots(){/* Do not delete existing enemies. */}
 enemyCombatTarget(e){const decoy=this.revisionDecoyTarget(e);if(decoy)return decoy;const patrol=e.patrolTarget;if(patrol?.hp>0&&patrol.life>0&&this.patrols.includes(patrol)&&this.patrolCanEngage(e,patrol))return patrol;const alive=this.living().filter(p=>(p.kaiserFogTime||0)<=0),current=this.player(e.targetPlayerId);let closest=alive.reduce((best,p)=>!best||squared(p,e)<squared(best,e)?p:best,null);if(current&&live(current)&&(current.kaiserFogTime||0)<=0&&closest&&squared(current,e)<squared(closest,e)*1.6)closest=current;e.targetPlayerId=closest?.id;return (closest?.pilot==='ball'&&closest.ballCloak>0&&closest.ballGhost?closest.ballGhost:closest)||{x:e.x+Math.cos(e.a)*420,y:e.y+Math.sin(e.a)*420,a:e.a,fogHidden:true}}
 sunStrikeContains(e){return this.players.some(p=>live(p)&&p.sunStrikeContains(e))}
 resolveHostileRound(b,x0,y0){const dx=b.x-x0,dy=b.y-y0,length=dx*dx+dy*dy;let first=Infinity,hit=null;for(const target of [...this.living(),...this.patrols.filter(p=>p.hp>0&&p.life>0)]){const radius=(target.id?10:16)+(b.flak?6:0),ox=x0-target.x,oy=y0-target.y,c=ox*ox+oy*oy-radius*radius;let t=0;if(c>0){if(!length)continue;const dot=ox*dx+oy*dy,disc=dot*dot-length*c;if(disc<0)continue;t=(-dot-Math.sqrt(disc))/length;if(t<0||t>1)continue}if(t<first){first=t;hit=target}}if(hit){if(hit.id){hit.damageSource={x:x0,y:y0,bullet:b};this.hitPlayer(hit,highRiskDamage(b.damage,hit.maxHp,b));hit.damageSource=null;}else this.hitPatrol(hit,b.damage);b.life=0}}
 handleDeath(e,b){if(e.stageBossBody||e.deathHandled||e.hp>0)return;e.deathHandled=true;const credited=!b.patrol||e.playerHit,owner=this.player(b.ownerId);owner?.spawnAmatolSecondary(e,b);if(credited){this.kills++;if(owner)owner.kills++;if(!e.surface&&!e.fieldUnit&&(e.bossPilot||['boss','zeppelin','bomber'].includes(e.type)))this.priorityKills++}else this.patrolKills=(this.patrolKills||0)+1;if(e.type==='zeppelin')this.wreckGust(e);this.burst(e.x,e.y,'#f2aa52',30);this.smoke(e.x,e.y,true);this.event('kill','');if(e.type==='boss'){this.bossKilled=true;if(owner&&live(owner))owner.hp=Math.min(owner.maxHp,owner.hp+owner.maxHp*DURABILITY_BALANCE.repairPickupFraction)}if(credited){const big=e.bossPilot||e.type==='boss';if(big)for(let gi=0;gi<5;gi++)this.drops.push({id:this.nextEntityId++,x:e.x+Math.cos(gi*1.26)*44,y:e.y+Math.sin(gi*1.26)*44,value:14,heal:false});this.drops.push({id:this.nextEntityId++,x:e.x,y:e.y,value:big?30:e.heavyBomber?16:e.type==='bomber'?3:(e.xpValue||1),heal:big||this.rng()<.03});Game.prototype.dropObservationRepair.call(this,e)}}
 updateSchedules(dt){
  const wave=this.t<60?1:this.t<120?2:3;if(wave!==this.wave){this.wave=wave;this.event('wave',wave===1?'2인 협동 · 서로의 꼬리를 지켜주세요':wave===2?'제2파 · 추격기 접근':'제3파 · 전선 돌파')}
  this.eventTimer-=dt;if(this.eventTimer<=0){this.eventTimer=22+this.rng()*20;const roll=this.rng(),quiet=this.mobSpawnsSuppressed();if(roll<.35&&!quiet){for(let i=0;i<3;i++)this.spawnRegular('hunter');this.event('wave','기습! 고속 추격 편대')}else if(roll<.6&&!quiet){this.spawnRegular('bomber');this.spawnRegular('bomber');this.event('wave','폭격 편대 통과')}else if(roll<.8||quiet){this.drops.push({x:this.x+Math.cos(this.a)*180,y:this.y+Math.sin(this.a)*180,value:0,heal:true,supply:true,vx:0,vy:0,life:14});this.event('wave','전방 수리 보급품!')}}
  this.flakTimer-=dt;if(this.t>28&&this.flakTimer<=0){this.flakTimer=(Math.max(10,27-this.t*.028)+this.rng()*6)*(this.region===2?.6:this.region===1?1.4:1);this.spawnFlak()}
  this.spawn-=dt;if(this.spawn<=0&&this.enemies.length<COOP_BALANCE.enemyCap&&!this.mobSpawnsSuppressed()){this.spawn=this.regularSpawnInterval();this.spawnRegular(this.spawnComposition())}else if(this.mobSpawnsSuppressed())this.spawn=Math.max(this.spawn,.5)
  this.supplyTimer-=dt;if(this.supplyTimer<=0){this.supplyTimer=Math.max(30+this.rng()*24,68+this.rng()*42);const a=this.rng()*Math.PI*2;this.drops.push({x:this.x+Math.cos(a)*520,y:this.y+Math.sin(a)*520,value:0,heal:true,supply:true,vx:-Math.cos(a)*78,vy:-Math.sin(a)*78,life:18})}
  this.runScheduledAces();
  if(this.t>=this._zeppelinSchedule){this.spawnEnemy('zeppelin');this._zeppelinSchedule=this.t+135+this.rng()*35;this.event('wave','적 비행선 강습')}
  if(this.t>=this.nextHeavyAt&&this.enemies.length<COOP_BALANCE.enemyCap-1&&!this.enemies.some(e=>e.heavyBomber)){const e=this.spawnEnemy('heavyBomber');if(e){this.nextHeavyAt=this.t+100+this.rng()*25;this.event('wave',e.name+' 출현 · 중기관총 탄막 주의')}}
  this.regionThreat-=dt;if(this.regionThreat<=0){this.regionThreat=24;if(this.region===1&&this.enemies.length<COOP_BALANCE.enemyCap-5)this.spawnRegular(this.rng()<.12?'zeppelin':'bomber');this.spawnFlak()}
  this.fieldUnitTimer-=dt;if(this.fieldUnitTimer<=0){this.fieldUnitTimer=55;if(this.region!==1){this.fieldUnitWave=(this.fieldUnitWave||0)+1;this.spawnFieldUnit(this.fieldUnitWave%2===0?'railgun':'balloon')}}
  this.gasTimer-=dt;if(this.gasTimer<=0){this.gasTimer=28;if(this.region===2)this.spawnGas()}
  this.gustTimer-=dt;if(this.gustTimer<=0){this.gustTimer=42+this.rng()*30;const a=this.rng()*Math.PI*2,d=430+this.rng()*150;this.gusts.push({x:this.x+Math.cos(a)*d,y:this.y+Math.sin(a)*d,vx:-Math.cos(a)*150,vy:-Math.sin(a)*150,a:a+Math.PI/2,life:6,maxLife:6,radius:55+this.rng()*18,hitPlayers:new Set()});this.event('flak','돌풍 발생! 풍압을 피하세요')}
  for(const boss of [...this.enemies].filter(e=>e.encounterPending&&e.hp>0)){
   boss.encounterPending=false;this.events.push({type:'bossArrival',pilot:boss.bossPilot,name:boss.name,airframe:boss.bossPlane});if(!['goering','mannock','collishaw'].includes(boss.bossPilot))continue;
   const collie=boss.bossPilot==='collishaw',count=collie?ENEMY_BOSS_BALANCE.collishawEscorts:8,plane=collie?'sopwith':boss.bossPilot==='goering'?'white-fokkerdv55':'se5a',slots=count%2?[0,-1,1,-2,2,-3,3]:[-.5,.5,-1.5,1.5,-2.5,2.5,-3.5,3.5];this.reserveEnemySlots(count);
   for(let i=0;i<count;i++){const e=this.spawnEnemy('hunter',{scale:false});if(!e)break;const slot=slots[i],back=(Math.abs(slot)+1)*54,off=slot*62;Object.assign(e,{type:'hunter',heavyBomber:false,x:boss.x-Math.cos(boss.a)*back-Math.sin(boss.a)*off,y:boss.y-Math.sin(boss.a)*back+Math.cos(boss.a)*off,a:boss.a,hp:collie?78:65,maxHp:collie?78:65,speed:boss.speed,fire:1.5+i*.16,ace:false,escortPlane:plane,blackFlightEscort:collie,formationLeader:boss,formationBack:back,formationOffset:off});attachAircraftPersonality(PLANES,e,plane);this.scaleEnemyHp(e)}
  }
 }
 spawnFleet(){const count=Math.min(3-this.enemies.filter(e=>e.navalVessel&&e.hp>0).length,COOP_BALANCE.enemyCap-this.enemies.length);for(let i=0;i<count;i++){const e=this.spawnEnemy('bomber',{scale:false});if(!e)break;Object.assign(e,{a:-Math.PI/2,speed:0,stationary:true,surface:true,navalVessel:true,hitRadius:65,hullLength:150,hullWidth:38,hp:230,maxHp:230,fire:2+i*.7,ace:false,escortPlane:undefined,life:55,coopHpApplied:1})}if(count>0)this.event('flak','적 함대 접근 · 함선의 대공 탄막을 피하세요')}
 spawnFieldUnit(kind){if(this.region===1||this.region===4||this.enemies.some(e=>e.hp>0&&e.fieldUnit===kind))return null;const e=this.spawnEnemy('scout',{scale:false});if(!e)return null;const rail=kind==='railgun',sprite=rail?'railgun':e.faction==='central'?'drachen':'caquot';Object.assign(e,{type:kind,fieldUnit:kind,fieldSprite:sprite,name:rail?'중열차포':sprite==='drachen'?'드라헨 관측기구':'캉코 관측기구',a:-Math.PI/2,speed:0,stationary:true,surface:rail,ace:false,escortPlane:undefined,hp:rail?600:780,maxHp:rail?600:780,hitRadius:rail?74:114,hullLength:rail?92:170,hullWidth:rail?52:72,fire:2.5,fieldRegion:this.region,coopHpApplied:1});if(rail){e.rail={x:e.x,y:e.y,angle:Math.floor(this.rng()*4)*Math.PI/4,half:180,progress:0,direction:1,speed:42};e.a=e.rail.angle}this.event('flak',e.name+' 출현');return e}
 enemyVolley(e,followup=false){if(this.sunStrikeContains(e)||this.living().every(p=>(p.kaiserFogTime||0)>0))return;const heavy=e.heavyBomber,bomber=e.type==='bomber',n=heavy?7:e.type==='boss'?7:e.type==='zeppelin'?15:bomber?3:1,contact=this.enemyCombatTarget(e);const aimed=e.type==='zeppelin'?Math.atan2(contact.y-e.y,contact.x-e.x):bomber?Math.atan2(contact.y+Math.sin(contact.a)*22-e.y,contact.x+Math.cos(contact.a)*22-e.x):e.a,aim=followup?(e.gunAim??aimed):aimed,speed=heavy?235:bomber?210:185,power=1+this.t/240,offsets=e.type==='zeppelin'?[-95,0,95]:heavy?[-42,42]:[0];e.muzzleFlash=.14;e.gunAim=aim;for(let j=0;j<n;j++){const offset=offsets[j%offsets.length],a=aim+(j-(n-1)/2)*(heavy?.13:.15)+(followup?.035:0);this.bullets.push({x:e.x+(e.type==='zeppelin'?Math.cos(e.a)*offset:Math.cos(e.a)*22-Math.sin(e.a)*offset),y:e.y+(e.type==='zeppelin'?Math.sin(e.a)*offset:Math.sin(e.a)*22+Math.cos(e.a)*offset),vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:4,enemy:true,heavy,visualType:e.type==='boss'||e.bossPilot?'boss':heavy?'heavyBomber':e.type,damage:Math.round((heavy?14:9)*power*(e.aceDamageMultiplier||1)),targetPlayerId:contact.id})}this.event(heavy?'heavyShot':'enemyShot','')}
 fireEnemy(e){if(this.sunStrikeContains(e)||this.living().every(p=>(p.kaiserFogTime||0)>0)){e.fire=.35;return}const target=this.enemyCombatTarget(e);if(e.fieldUnit){const rail=e.fieldUnit==='railgun';e.fire=rail?5.8:6.6;e.fieldSalvoAim=Math.atan2(target.y-e.y,target.x-e.x);e.fieldBurstIndex=0;e.fieldSalvoLeft=2;e.fieldSalvoDelay=rail?.26:.38;this.fieldVolley(e);return}if(e.navalVessel){e.fire=3.4;const aim=Math.atan2(target.y-e.y,target.x-e.x);e.gunAim=aim;e.muzzleFlash=.16;for(const along of [-95,0,95])for(let i=-2;i<=2;i++){const a=aim+i*.17;this.bullets.push({x:e.x+Math.cos(e.a)*along,y:e.y+Math.sin(e.a)*along,vx:Math.cos(a)*205,vy:Math.sin(a)*205,life:4.2,enemy:true,heavy:true,naval:true,hazardRegion:1,damage:Math.round(13*(1+this.t/260))})}this.event('enemyShot','');return}e.fire=e.heavyBomber?2.8:e.type==='boss'?.65/(e.aceAttackRate||1):e.type==='zeppelin'?3.2:e.type==='bomber'?1.5:2.5;this.enemyVolley(e);if(e.heavyBomber){e.burstLeft=2;e.burstDelay=.2}else if(e.type==='zeppelin'){e.burstLeft=1;e.burstDelay=.3}}
 aceAttack(e){if(this.sunStrikeContains(e))return;if(e.bossPilot==='berthold'){e.ironWillUntil=this.t+5;return}if(e.bossPilot==='hawker'){e.rapidFireUntil=this.t+5;this.enemyVolley(e);return}const id=e.bossPilot,p=this.enemyCombatTarget(e),aim=Math.atan2(p.y-e.y,p.x-e.x);if(['baron','voss','baracca','immelmann'].includes(id)){e.a=aim;e.bossDash=1.1}if(id==='goering')for(let i=0;i<2;i++){const wing=this.spawnEnemy('hunter',{scale:false});if(!wing)break;Object.assign(wing,{hp:80*(1+this.t/180),maxHp:80*(1+this.t/180),escortPlane:'white-fokkerdv55',fire:.3});attachAircraftPersonality(PLANES,wing,wing.escortPlane,{retuneCruise:true});this.scaleEnemyHp(wing)}if(id==='bishop'){const f=Math.max(80,(p.baseSpeed||this.speed)*.8),ca=Math.cos(p.a),sa=Math.sin(p.a);for(let i=0;i<8;i++){const row=Math.floor(i/4),lane=i%4-1.5,delay=.9+(i%4)*.16+row*.18;this.bombZones.push({x:p.x+ca*(f+row*92)-sa*lane*72,y:p.y+sa*(f+row*92)+ca*lane*72,sx:e.x,sy:e.y,delay,maxDelay:delay,radius:50,damage:25*(e.aceDamageMultiplier||1),maxHpFraction:.04})}}if(id==='guynemer'){for(let i=0;i<9;i++){const a=aim+(i-4)*.05;this.bullets.push({x:e.x,y:e.y,vx:Math.cos(a)*230,vy:Math.sin(a)*230,life:3,enemy:true,hostileRocket:true,aceSpecial:true,damage:20*(e.aceDamageMultiplier||1)})}}else if(id==='fonck')this.bullets.push({x:e.x,y:e.y,vx:Math.cos(aim)*360,vy:Math.sin(aim)*360,life:2,enemy:true,heavy:true,visualType:'boss',aceSpecial:true,damage:30*(e.aceDamageMultiplier||1)});else{this.enemyVolley(e);if(['udet','boelcke','goering'].includes(id)){e.burstLeft=3;e.burstDelay=.18}}this.event('wave',e.name+' · '+PILOTS[id].skill)}
 updateEnemies(dt){
  for(const e of this.enemies){if(this.state==='lost')return;if(e.stageBossBody||e.bossMinion)continue;if(e.crashing){e.crashT-=dt;e.a+=e.crashSpin*dt;e.x+=Math.cos(e.crashDir)*e.crashSpeed*dt;e.y+=Math.sin(e.crashDir)*e.crashSpeed*dt;e.crashSpeed=Math.max(30,e.crashSpeed*(1-.7*dt));e.crashSmoke-=dt;if(e.crashSmoke<=0){e.crashSmoke=.045;this.smoke(e.x+(this.rng()-.5)*10,e.y+(this.rng()-.5)*10,true)}if(e.crashT<=0){e.crashed=true;this.burst(e.x,e.y,'#f2aa52',36);for(let k=0;k<9;k++)this.smoke(e.x+(this.rng()-.5)*26,e.y+(this.rng()-.5)*26,true);this.event('kill','')}continue}if(e.hp<=0)continue;stepTimer(e,'hitFlash',dt);stepTimer(e,'muzzleFlash',dt);e.smokeTimer=(e.smokeTimer||0)-dt;if(e.hp<e.maxHp&&e.smokeTimer<=0){this.smoke(e.x,e.y,e.hp/e.maxHp<.4);e.smokeTimer=e.hp/e.maxHp<.4?.07:.16}
   const sun=this.sunStrikeContains(e),p=this.enemyCombatTarget(e),energySpeed=e.energySpeed??1,turn=sun||e.stationary||e.bossDash>0?0:e.heavyBomber?.3:e.type==='boss'?2:e.type==='hunter'?1.7:e.type==='zeppelin'?.42:.85,steering=e.type==='bomber'?{turn:turn>0?(e.heavyBomber?.12:.16):0,delta:0}:this.dogfightSteering(e,p,dt,turn);if(e.type==='bomber')steering.delta=Math.cos(this.t*.6+e.wobble)*steering.turn*dt;e.a+=clamp(steering.delta,-steering.turn*dt,steering.turn*dt);e.x+=Math.cos(e.a)*e.speed*energySpeed*(e.bossDash>0?ENEMY_MOVEMENT_BALANCE.dashMultiplier:1)*(sun?SUN_STRIKE.speedMultiplier:1)*dt;e.y+=Math.sin(e.a)*e.speed*energySpeed*(e.bossDash>0?ENEMY_MOVEMENT_BALANCE.dashMultiplier:1)*(sun?SUN_STRIKE.speedMultiplier:1)*dt;
   if(e.rail){const r=e.rail;r.progress+=r.direction*r.speed*dt*(sun?SUN_STRIKE.speedMultiplier:1);if(r.progress>r.half){r.progress=2*r.half-r.progress;r.direction=-1}else if(r.progress< -r.half){r.progress=-2*r.half-r.progress;r.direction=1}e.x=r.x+Math.cos(r.angle)*r.progress;e.y=r.y+Math.sin(r.angle)*r.progress}
   if(!sun){const start=this.bullets.length;e.fire-=dt;if(e.fire<0){this.fireEnemy(e);if(e.rapidFireUntil>this.t)e.fire=Math.min(e.fire,.22)};const pressure=clamp((this.t-30)/120,0,1);for(const b of this.bullets.slice(start)){b.damage=Math.round(b.damage*(1+pressure*.16));b.vx*=1+pressure*.05;b.vy*=1+pressure*.05}if(e.burstLeft>0){e.burstDelay-=dt;if(e.burstDelay<=0){e.burstLeft--;e.burstDelay=.2;this.enemyVolley(e,true)}}if(e.fieldSalvoLeft>0){e.fieldSalvoDelay-=dt;if(e.fieldSalvoDelay<=0){e.fieldSalvoLeft--;e.fieldSalvoDelay=e.fieldUnit==='railgun'?.26:.38;this.fieldVolley(e)}}
    if(e.heavyBomber){e.bombTimer=(e.bombTimer??3)-dt;if(e.bombTimer<=0&&Math.hypot(e.x-p.x,e.y-p.y)<650){e.bombTimer=6;for(let i=0;i<3;i++){const delay=1.5+i*.22;this.bombZones.push({x:p.x+Math.cos(p.a)*(i-1)*95,y:p.y+Math.sin(p.a)*(i-1)*95,sx:e.x,sy:e.y,delay,maxDelay:delay,radius:52,damage:22+Math.floor(this.t/90)})}this.event('bombWarning','폭격 투하! 붉은 표적을 벗어나세요')}}
    if(e.bossPilot){stepTimer(e,'bossDash',dt);e.abilityTimer-=dt;if(e.abilityTimer<=0){e.abilityTimer=e.bossPilot==='bishop'?ENEMY_BOSS_BALANCE.bishopAbilityMin+this.rng()*ENEMY_BOSS_BALANCE.bishopAbilityVariance:7+this.rng()*3;this.aceAttack(e)}}
   }
   if(!e.surface){for(const player of this.living())if(Math.hypot(e.x-player.x,e.y-player.y)<(e.contactRadius??(e.heavyBomber?48:e.type==='boss'?ENEMY_MOVEMENT_BALANCE.aceContactRadius:e.type==='zeppelin'?42:19)))this.hitPlayer(player,e.type==='boss'?22:e.type==='zeppelin'?18:15);for(const patrol of this.patrols)if(patrol.hp>0&&Math.hypot(e.x-patrol.x,e.y-patrol.y)<24)this.hitPatrol(patrol,18)}
   const leader=e.formationLeader;if(leader?.hp>0&&this.enemies.includes(leader)&&!sun){e.x+=(leader.x-Math.cos(leader.a)*e.formationBack-Math.sin(leader.a)*e.formationOffset-e.x)*Math.min(1,dt*3);e.y+=(leader.y-Math.sin(leader.a)*e.formationBack+Math.cos(leader.a)*e.formationOffset-e.y)*Math.min(1,dt*3);e.a=leader.a}if(e.navalVessel){e.life-=dt;if(e.life<=0)e.expired=true}
  }
 }
 updateHazards(dt){
  for(const z of this.bombZones){z.delay-=dt;if(z.delay<=0){this.combatBlast(z.x,z.y,z.radius,'enemy','bomb');for(const p of this.living())if(Math.hypot(p.x-z.x,p.y-z.y)<z.radius)this.hitPlayer(p,highRiskDamage(z.damage,p.maxHp,z))}}this.bombZones=this.bombZones.filter(z=>z.delay>0);
  for(const f of this.hostileMinefields){f.warning-=dt;f.life-=dt;for(const m of f.mines){if(m.dead)continue;for(const b of this.bullets){if(b.enemy||b.life<=0)continue;if(Math.hypot(b.x-m.x,b.y-m.y)<20){m.hp-=b.damage;if(!b.pierce)b.life=0;if(m.hp<=0){m.dead=true;this.combatBlast(m.x,m.y,32,'friendly','mine');break}}}if(!m.dead&&f.warning<=0){const targets=this.living().filter(p=>Math.hypot(p.x-m.x,p.y-m.y)<25);if(targets.length){m.dead=true;for(const p of targets)this.hitPlayer(p,22);this.combatBlast(m.x,m.y,58,'enemy','mine')}}}}this.hostileMinefields=this.hostileMinefields.filter(f=>f.life>0&&f.region===this.region&&f.mines.some(m=>!m.dead));
  if(this.region!==2)this.gasZones=[];for(const z of this.gasZones){z.warning-=dt;z.life-=dt}this.gasZones=this.gasZones.filter(z=>z.life>0);for(const p of this.living()){p.inGas=this.gasZones.some(z=>z.warning<=0&&Math.hypot(p.x-z.x,p.y-z.y)<z.r);if(p.inGas&&!p.grunkreuz){p.gasExposure=(p.gasExposure||0)+dt;if(p.gasExposure>=1){p.gasExposure-=1;this.hitPlayer(p,6,{gas:true})}}else p.gasExposure=0}
  for(const g of this.gusts){g.life-=dt;g.x+=g.vx*dt;g.y+=g.vy*dt;g.hitPlayers??=new Set();for(const p of this.living())if(!g.hitPlayers.has(p.id)&&Math.hypot(g.x-p.x,g.y-p.y)<g.radius){g.hitPlayers.add(p.id);p.gustDisorient=1.35;p.gustOffset=(this.rng()-.5)*2.2;p.a+=p.gustOffset*.35;this.shake=9;p.event('flak','돌풍에 휘말렸다! 조준이 흔들린다')}}this.gusts=this.gusts.filter(g=>g.life>0);
  for(const f of this.flakBursts)f.life-=dt;this.flakBursts=this.flakBursts.filter(f=>f.life>0);for(const fx of this.combatFX)fx.life-=dt;this.combatFX=this.combatFX.filter(f=>f.life>0).slice(-35);
 }
 updatePlayer(p,dt,input){
  const previousRounds=p.roundsFired;const revisionPrior=p.beginRevisionFrame(dt,input);
  const oldX=p.x,oldY=p.y,active=p.skillTime,charge=p.chargeTime>0,duo=['mckeever','huffzky'].includes(p.pilot),boost=p.udetBoost>0;
  for(const key of ['muzzleFlash','hitFlash','cooldown','evadeCooldown','evadeTime','skillTime','invuln','wingBoost','crossfireFlash'])stepTimer(p,key,dt);
  p.smokeTimer-=dt;if(p.hp<p.maxHp*.6&&p.smokeTimer<=0){p.smoke(p.x-Math.cos(p.a)*12,p.y-Math.sin(p.a)*12,p.hp<p.maxHp*.3);p.smokeTimer=.12}
  let control={...input};if(p.gustDisorient>0){p.gustDisorient=Math.max(0,p.gustDisorient-dt);if(Number.isFinite(control.angle))control.angle+=p.gustOffset||0;else control.steer=(control.steer||0)+(p.gustOffset||0)*.65}
  const inGas=this.region===2&&this.gasZones.some(z=>z.warning<=0&&z.life>0&&Math.hypot(p.x-z.x,p.y-z.y)<z.r),turn=p.turn;
  if(inGas){p.turn*=.55;const drift=Math.sin(this.t*2.4)*.22;if(Number.isFinite(control.angle))control.angle+=drift;else control.steer=(control.steer||0)+drift}
  p.duoSpinStep=duo?Math.min(dt,active):0;p.flyAirframe(dt,control);p.duoSpinStep=0;p.turn=turn;
  const velocity=p.baseSpeed*p.healthSpeedFactor()*stageBossSpeed(p)*(boost?1.7:1)*(charge?4.6:p.evadeTime>0?2.35:p.airframeSpeed??1)*(p.pursuitSpeedFactor??1);
  p.x+=Math.cos(p.a)*velocity*dt;p.y+=Math.sin(p.a)*velocity*dt;this.constrainMove(p,oldX,oldY);p.distance+=Math.hypot(p.x-oldX,p.y-oldY);
  p.updateTailLock(dt);
  if(charge){p.invuln=Math.max(p.invuln,dt+.02);p.a=p.chargeAngle;p.chargeTime=Math.max(0,p.chargeTime-dt);for(const e of this.enemies)if(e.hp>0&&!p.chargeHits.has(e)&&segmentDistance(e.x,e.y,oldX,oldY,p.x,p.y)<(e.heavyBomber?85:52)){p.chargeHits.add(e);this.emit(p,{x:e.x,y:e.y,vx:0,vy:0,life:.15,damage:p.damage*18,blast:true});this.combatBlast(e.x,e.y,48,'friendly','charge')}}
  if(p.bishopTime>0){p.invuln=Math.max(p.invuln,dt+.05);p.bishopTime=Math.max(0,p.bishopTime-dt);p.bishopBombTimer-=dt;if(p.bishopDrops>0&&p.bishopBombTimer<=0){p.bishopDrops--;p.bishopBombTimer=.23;const target=this.enemies.filter(e=>e.hp>0).sort((a,b)=>squared(a,p)-squared(b,p))[0];this.blast(p,target?.x??p.x+Math.cos(p.a)*120,target?.y??p.y+Math.sin(p.a)*120,110,p.payloadPower(90))}if(p.bishopTime===0){p.bishopEmptyPending=true}}
  tickLegendaryDefenses(p,this,dt);
  if(p.cow37){p.cow37Timer=(p.cow37Timer??.15)-dt;if(p.reloadTime<=0&&p.cow37Timer<=0){if((p.ammo[0]||0)<=0)p.reload();else{p.cow37Timer+=p.ordnanceInterval(COW37_BALANCE.interval);p.ammo[0]--;p.roundsFired++;this.emit(p,{x:p.x+Math.cos(p.a)*38,y:p.y+Math.sin(p.a)*38,vx:Math.cos(p.a)*COW37_BALANCE.speed,vy:Math.sin(p.a)*COW37_BALANCE.speed,life:2.5,cow37:true,collisionRadius:20,damage:p.payloadPower(COW37_BALANCE.damage)*(p.damage/12)*p.normalGunMultiplier()});p.muzzleFlash=.2;this.shake=Math.max(this.shake,6);p.burst(p.x+Math.cos(p.a)*32,p.y+Math.sin(p.a)*32,'#e8d39a',16);p.cannonMuzzleSmoke('cow');p.event('shot','')}}}
  if(p.unlimitedAmmo){p.reloadTime=0;p.ammo.fill(p.weapon.belt)}
  if(p.reloadTime>0){p.reloadTime=Math.max(0,p.reloadTime-dt);p.fire=0;if(p.reloadTime===0){p.ammo.fill(p.weapon.belt);p.event('loaded','재장전 완료')}}
  else if(!p.cow37){p.fire-=dt;if(p.bishopTime>0)p.fire=Math.max(p.fire,.1);let volleys=0;while(p.fire<=0&&p.reloadTime===0&&volleys++<8){
   if(p.ammo.every(n=>n===0)){p.reload();break}p.fire+=Math.max(.02,p.rate/(boost?2.4:1));
   for(let gun=0;gun<p.weapon.guns;gun++){const rounds=Math.min(p.shots,p.ammo[gun]),offset=p.weapon.bidirectional?0:(gun-(p.weapon.guns-1)/2)*8,ga=p.gunDirection(gun);for(let i=0;i<rounds;i++){const a=ga+(i-(rounds-1)/2)*.11,tailTargetId=p.tailLocked?p.tailTargetId:null,round={x:p.x+Math.cos(ga)*23-Math.sin(ga)*offset,y:p.y+Math.sin(ga)*23+Math.cos(ga)*offset,vx:Math.cos(a)*520,vy:Math.sin(a)*520,life:['bishop','mannock'].includes(p.pilot)?.6:1.35,gun,damage:p.damage*p.normalGunMultiplier()/Math.sqrt(p.shots),tailBonus:!!tailTargetId,tailTargetId};this.emit(p,p.applySpecialRound(round,null))}if(!p.unlimitedAmmo)p.ammo[gun]-=rounds?Math.max(1,rounds-(p.freeVolleyShots||0)):0;p.roundsFired+=rounds}p.muzzleFlash=.055;p.event('shot','');if(p.ammo.every(n=>n===0))p.reload();
  }}
  if(p.bishopEmptyPending){p.bishopEmptyPending=false;if(!p.unlimitedAmmo)p.ammo.fill(0);p.reloadTime=0;p.fire=.1;p.muzzleFlash=0}
  if(boost)stepTimer(p,'udetBoost',dt);
  if(p.salvoWaves>0){p.salvoTimer-=dt;if(p.salvoTimer<=0){p.salvoTimer+=.36;p.salvoWaves--;for(let j=0;j<6;j++){const side=j<3?-1:1,a=p.a+(j-2.5)*.16;this.emit(p,{x:p.x+Math.cos(p.a)*12-Math.sin(p.a)*side*23,y:p.y+Math.sin(p.a)*12+Math.cos(p.a)*side*23,vx:Math.cos(a)*330,vy:Math.sin(a)*330,life:3.2,damage:p.payloadPower(32.4),rocket:true,special:true})}p.event('rocketSalvo','')}}
  if(p.rockets>0){p.rocketFire-=dt;if(p.rocketFire<=0)p.launchUpgradeRocket()}
  if(p.mineCount>0){p.mineTimer-=dt;if(p.mineTimer<=0){p.mineTimer=p.ordnanceInterval(3.6/(1+p.mineCount*.3));p.throwGrenades()}}p.tickGrenades(dt);
  if(p.legendaryMineTrail){p.legendaryMineTimer=(p.legendaryMineTimer??0)-dt;if(p.legendaryMineTimer<=0){p.legendaryMineTimer+=LEGENDARY_BALANCE.mineInterval;this.mines.push({ownerId:p.id,x:oldX-Math.cos(p.a)*22,y:oldY-Math.sin(p.a)*22,life:LEGENDARY_BALANCE.mineLife,arm:.25,damage:p.payloadPower(LEGENDARY_BALANCE.mineDamage),special:true,legendary:true})}}
  if(p.motorCannon){p.motorCannonTimer=(p.motorCannonTimer??0)-dt;if(p.motorCannonTimer<=0){p.motorCannonTimer+=p.ordnanceInterval(LEGENDARY_BALANCE.motorCannonInterval);this.emit(p,{x:p.x+Math.cos(p.a)*38,y:p.y+Math.sin(p.a)*38,vx:Math.cos(p.a)*460,vy:Math.sin(p.a)*460,life:2.8,motorCannon:true,pierce:true,collisionRadius:22,damage:p.payloadPower(LEGENDARY_BALANCE.motorCannonDamage)});p.muzzleFlash=.18;p.cannonMuzzleSmoke('motor')}}
  if(duo&&active>0){p.crossfireTimer-=Math.min(dt,active);while(p.crossfireTimer<=1e-9){p.crossfireTimer+=.08;p.duoVolley()}}
  if(p.pilot==='collishaw'&&p.skillTime>0){p.formationClock=(p.formationClock||0)+dt;for(const wing of p.formationWings){const sweep=Math.sin(p.formationClock*1.55+wing.phase)*190,forward=145+Math.cos(p.formationClock*1.2+wing.phase)*35;wing.x=p.x+Math.cos(p.a)*forward-Math.sin(p.a)*(sweep+wing.slot*20);wing.y=p.y+Math.sin(p.a)*forward+Math.cos(p.a)*(sweep+wing.slot*20);wing.a=p.a;wing.alpha=Math.min(1,wing.alpha+dt*8);wing.fire-=dt;while(wing.fire<=0){wing.fire+=PILOT_BALANCE.blackFlightInterval/(1+(p.commandRateBonus||0));const aim=p.blackFlightAim(wing,p.a);this.emit(p,{x:wing.x+Math.cos(p.a)*28,y:wing.y+Math.sin(p.a)*28,vx:Math.cos(aim)*500,vy:Math.sin(aim)*500,life:1.6,damage:p.supportPower(PILOT_BALANCE.blackFlightDamage),pierce:true,formation:true,blackFlight:true})}}}else for(const wing of p.formationWings)wing.alpha=Math.max(0,wing.alpha-dt*5);
  p.mannockPassTimer=(p.mannockPassTimer??Infinity)-dt;if(p.mannockPass===1&&p.mannockPassTimer<=0){p.mannockPass=2;const w=p.viewWidth,h=p.viewHeight;p.divingSquadron.push(...Array.from({length:7},(_,i)=>{const slot=i-3;return {ownerId:p.id,x:p.x+w*.68+Math.abs(slot)*w*.08,y:p.y+slot*h*.11,a:Math.PI,age:0,speed:w*.58,fire:Math.abs(slot)*.04,pass:'horizontal',hit:new Set()}}))}
  for(const wing of p.divingSquadron){const ox=wing.x,oy=wing.y;wing.age+=dt;wing.x+=Math.cos(wing.a)*wing.speed*dt;wing.y+=Math.sin(wing.a)*wing.speed*dt;wing.fire-=dt;if(wing.fire<=0){wing.fire=PILOT_BALANCE.mannockInterval/(1+(p.commandRateBonus||0));this.emit(p,{x:wing.x+Math.cos(wing.a)*25,y:wing.y+Math.sin(wing.a)*25,vx:Math.cos(wing.a)*620,vy:Math.sin(wing.a)*620,life:1.5,formation:true,pierce:true,damage:p.supportPower(PILOT_BALANCE.mannockDamage)})}for(const e of this.enemies)if(e.hp>0&&!wing.hit.has(e)&&segmentDistance(e.x,e.y,ox,oy,wing.x,wing.y)<40){wing.hit.add(e);this.emit(p,{x:e.x,y:e.y,vx:0,vy:0,life:.15,damage:p.supportPower(PILOT_BALANCE.mannockContact),blast:true})}}p.divingSquadron=p.divingSquadron.filter(w=>w.age<4.6);
  for(const ship of p.airshipFleet){ship.age+=dt;if(ship.age<=0||ship.age>6)continue;const step=Math.min(dt,ship.age);ship.x+=Math.cos(ship.a)*ship.speed*step;ship.y+=Math.sin(ship.a)*ship.speed*step;ship.fire-=step;ship.pulse-=step;ship.flash=Math.max(0,ship.flash-step);if(ship.fire<=0){ship.fire+=.7;ship.flash=.12;for(const side of [-1,1])for(const spread of [-.2,0,.2]){const a=ship.a+side*Math.PI/2+spread;this.emit(p,{x:ship.x+Math.cos(a)*38,y:ship.y+Math.sin(a)*38,vx:Math.cos(a)*360,vy:Math.sin(a)*360,life:1.15,ally:true,airshipSupport:true,damage:p.supportPower(8)})}}if(ship.pulse<=0){ship.pulse+=.5;for(const e of this.enemies){if(e.hp<=0)continue;const dx=e.x-ship.x,dy=e.y-ship.y,u=dx*Math.cos(ship.a)+dy*Math.sin(ship.a),v=-dx*Math.sin(ship.a)+dy*Math.cos(ship.a);if((u/110)**2+(v/48)**2<=1)this.emit(p,{x:e.x,y:e.y,vx:0,vy:0,life:.1,ally:true,airshipSupport:true,blast:true,damage:p.supportPower(20)})}}}p.airshipFleet=p.airshipFleet.filter(s=>s.age<6);
  if(p.bomberLevel){p.bomberTimer=(p.bomberTimer??2)-dt;if(p.bomberTimer<=0){p.bomberTimer=Math.max(10,18-(p.bomberLevel-1)*2);this.friendlyBombers.push({ownerId:p.id,ox:p.x,oy:p.y,x:p.x-Math.cos(p.a)*650,y:p.y-Math.sin(p.a)*650,a:p.a,age:0,drop:.8,left:5,airframe:this.teamFaction==='central'?'staaken':'handley-page'})}}
  const regen=Math.min(DURABILITY_BALANCE.regenCap,p.regen||0)+(p.legendaryRegen||0);p.hp=Math.min(p.maxHp,p.hp+(DURABILITY_BALANCE.baseRegenHpPerSecond+p.maxHp*regen)*dt);
  this.tagSummons(p);p.endRevisionFrame(revisionPrior);advancePersonal1918(p,dt,previousRounds);
 }
 updateSupport(dt){
  for(const a of this.allies){const p=this.player(a.ownerId);if(!p||!live(p)){a.life=0;continue}a.life-=dt;const target=p.wingFormationTarget(a,p.permanentWingCount()),response=2.6*Math.max(.75,Math.min(1.25,a.personality?.acceleration??1));a.a=p.a;a.x+=(target.x-a.x)*Math.min(1,dt*response);a.y+=(target.y-a.y)*Math.min(1,dt*response);a.fire-=dt;if(a.fire<=0){a.fire=.42*(p.upgrades.fighterSupply?.9:1)/((p.wingBoost>0?GOERING_WING_BOOST.fireRateMultiplier:1)*(1+(p.commandRateBonus||0)));let nearest=null,best=Infinity;for(const e of this.enemies)if(e.hp>0){const d=squared(e,a);if(d<best){best=d;nearest=e}}if(nearest){const aim=Math.atan2(nearest.y-a.y,nearest.x-a.x);this.emit(p,{x:a.x+Math.cos(aim)*23,y:a.y+Math.sin(aim)*23,vx:Math.cos(aim)*470,vy:Math.sin(aim)*470,life:1.5,ally:true,damage:p.supportPower(7.44)*(p.wingmanDamageMult||1)*(p.wingBoost>0?GOERING_WING_BOOST.damageMultiplier:1)*(p.upgrades.fighterSupply?1.2:1)})}}}
  this.allies=this.allies.filter(a=>a.life>0);for(let i=0;i<this.allies.length;i++)for(let j=i+1;j<this.allies.length;j++){const a=this.allies[i],b=this.allies[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<42){const nx=d?dx/d:1,ny=d?dy/d:0,push=(42-d)*.5;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push}}
  for(const b of this.friendlyBombers){const p=this.player(b.ownerId);if(!p||!live(p))continue;b.age+=dt;const d=-650+b.age*480;b.x=b.ox+Math.cos(b.a)*d;b.y=b.oy+Math.sin(b.a)*d;b.drop-=dt;if(b.left>0&&b.drop<=0){b.drop=.42;b.left--;const targets=this.enemies.filter(e=>e.hp>0&&Math.hypot(e.x-b.x,e.y-b.y)<650),target=targets[Math.floor(this.rng()*targets.length)];this.friendlyBombs.push({ownerId:b.ownerId,sx:b.x,sy:b.y,x:target?.x??b.x+Math.cos(b.a)*120,y:target?.y??b.y+Math.sin(b.a)*120,life:.55,maxLife:.55,damage:p.payloadPower(80),radius:100})}}this.friendlyBombers=this.friendlyBombers.filter(b=>b.age<3.6&&live(this.player(b.ownerId)));
  for(const b of this.friendlyBombs){b.life-=dt;if(b.life<=0)this.blast(this.player(b.ownerId),b.x,b.y,b.radius,b.damage)}this.friendlyBombs=this.friendlyBombs.filter(b=>b.life>0);
 }
 updateOrdnance(dt){
  for(const m of this.mines){if(m.grenade){m.x+=(m.vx||0)*dt;m.y+=(m.vy||0)*dt;m.vx*=.985;m.vy*=.985}m.life-=dt;m.arm=Math.max(0,m.arm-dt);if(m.life>0&&m.arm===0&&this.enemies.some(e=>e.hp>0&&Math.hypot(e.x-m.x,e.y-m.y)<(m.special?48:72))){this.blast(this.player(m.ownerId),m.x,m.y,m.special?90:110,m.damage);m.life=0}}this.mines=this.mines.filter(m=>m.life>0);
  for(const b of this.bullets){if(this.state==='lost')return;if(b.life<=0)continue;const owner=this.player(b.ownerId);if(owner?.longRange&&!b.rangeExtended&&Math.hypot(b.vx,b.vy)>0){b.life=Math.max(b.life,owner.shotLifetime(Math.hypot(b.vx,b.vy)));b.rangeExtended=true}
   if(b.fonckSeeker){const target=this.enemies.filter(e=>e.hp>0&&!b.hit.has(e)).sort((a,c)=>squared(a,b)-squared(c,b))[0];if(target){const a=Math.atan2(target.y-b.y,target.x-b.x);b.vx=Math.cos(a)*680;b.vy=Math.sin(a)*680}}
   const x=b.x,y=b.y;b.previousX=x;b.previousY=y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;if(b.enemy){this.resolveHostileRound(b,x,y);continue}
   b.hit??=new Set();for(const e of this.enemies){if(e.hp<=0||e.deathHandled||b.hit.has(e)||b.patrol&&!b.fireZone&&!this.patrolCanEngage(e,b))continue;if(this.targetCollision(e,b.x,b.y,b)){damageStageBoss(this,e,b,b.damage*(b.patrol?1:(owner?.globalDamageMult||1)*(owner?.legendaryDamageMultiplier()||1)*(owner?.roundDamageMultiplier(b,e)||1)));if(!b.patrol)e.playerHit=true;e.hitFlash=.24;b.hit.add(e);owner?.specialRoundImpact(b,e);this.event('impact','');this.burst(b.x,b.y,b.specialColor||'#fff0bb',3);if(!b.pierce)b.life=0;this.handleDeath(e,b);if(!b.pierce||b.life<=0)break}}if(b.actualExplosion)b.life=0
  }
  this.bullets=this.bullets.filter(b=>b.life>0);this.enemies=this.enemies.filter(e=>{if(e.crashed)return false;if(e.crashing)return Math.hypot(e.x-this.x,e.y-this.y)<1300;if(e.hp<=0&&(e.bossPilot||e.type==='boss')&&!e.stageBossBody&&!e.bossMinion&&Math.hypot(e.x-this.x,e.y-this.y)<1300){e.crashing=true;e.crashT=1.15;e.crashDir=e.a+Math.PI/2+(this.rng()-.5)*.9;e.crashSpeed=Math.max(120,e.speed*1.2);e.crashSpin=(this.rng()<.5?-1:1)*(2.4+this.rng()*2.2);e.crashSmoke=0;e.hp=0;return true}return e.hp>0&&!e.expired&&(e.stageBossBody||e.type==='boss'||Math.hypot(e.x-this.x,e.y-this.y)<Math.max(1100,Math.hypot(this.viewWidth,this.viewHeight)/this.camera.zoom))});
 }
 updateDrops(dt){let xp=0;for(const d of this.drops){if(d.dead)continue;if(d.supply){d.x+=(d.vx||0)*dt;d.y+=(d.vy||0)*dt;d.life-=dt}const p=this.living().reduce((best,p)=>!best||squared(p,d)<squared(best,d)?p:best,null);if(!p)continue;const dist=Math.hypot(d.x-p.x,d.y-p.y);if(!d.supply&&dist<p.magnet){const a=Math.atan2(p.y-d.y,p.x-d.x),travel=Math.min(dist,330*(1+Math.max(0,Math.min(360,p.magnet-120))/360)*dt);d.x+=Math.cos(a)*travel;d.y+=Math.sin(a)*travel}if(dist<20){d.dead=true;xp+=d.value||0;if(d.heal)p.hp=Math.min(p.maxHp,p.hp+p.maxHp*(d.healFraction??DURABILITY_BALANCE.repairPickupFraction));if(d.specialAmmo)p.giveSpecialAmmo(d.specialAmmo,d.rounds)}}this.drops=this.drops.filter(d=>!d.dead&&(d.life===undefined||d.life>0)&&Math.hypot(d.x-this.x,d.y-this.y)<1800).slice(-250);if(xp)for(const p of this.players)p.xp+=xp*COOP_BALANCE.xp*(p.xpGainMult||1);}
 update(dt,inputs={}){
  if(this.state!=='playing')return;const step=clamp(dt,0,.04);if(!step)return;this.resolveBossLevels();this.queueLevels();if(this.state!=='playing')return;
  enableStageBoss(this,{teamFaction:this.teamFaction,heavyHp:COOP_BALANCE.heavyHp});beginStageBossFrame(this,step);if(this.state!=='playing')return;
  const aliveAtStart=this.living(),downAtStart=this.players.filter(p=>!live(p)),origins=new Map(aliveAtStart.map(p=>[p,{x:p.x,y:p.y}]));this.tickRevisionWorld(step);this.t+=step;this.worldTicks++;this.shake=Math.max(0,this.shake-step*22);
  let distance=0;for(const p of aliveAtStart){const {x,y}=origins.get(p);this.updatePlayer(p,step,inputs[p.id]||{});distance+=Math.hypot(p.x-x,p.y-y)}this.distance+=distance/(aliveAtStart.length||1);
  const region=this.worldRegion();if(region!==this.region){this.region=region;this.clearRegionalHazards();this.event('wave',['전원 지대 · 기뢰지대','아드리아해 · 적 함대','참호 전선 · 대공포'][region]+' 진입')}
  this.tickBattleDirector(step);this.tickBattlefieldEvents();if(this.state!=='playing')return;this.updateSchedules(step);this.ensureWingmen();this.updateSupport(step);this.updatePatrols(step);this.updateEnemies(step);if(this.state==='lost')return;for(const e of advanceBurns1918(this,step))this.handleDeath(e,{ownerId:e.burnOwnerId,burn:true});this.updateOrdnance(step);this.tickRivalAce(step);if(this.state==='lost')return;this.updateHazards(step);
  if(!this.living().length){this.finish();return}
  // Loss takes precedence over rescue and upgrades in the same simulation tick.
  for(const p of downAtStart){p.respawnRemaining=Math.max(0,p.respawnRemaining-step);if(p.respawnRemaining<=1e-9)this.revive(p)}
  this.updateCamera(step);this.updateDrops(step);
  for(const p of this.particles){p.x+=p.vx*step;p.y+=p.vy*step;p.life-=step}this.particles=this.particles.filter(p=>p.life>0).slice(-450);
  this.score=this.priorityKills;this.queueLevels();endStageBossFrame(this,step);this.resolveBossLevels();
 }
}

// Share ace specials as well as player specials; keep co-op ownership/targeting.
CoopGame.prototype.aceAttack=Game.prototype.aceAttack;
const _coopVoss113=CoopGame.prototype.updatePlayer;
CoopGame.prototype.updatePlayer=function(p,dt,input){
 const active=p.vossReverse>0,base=p.baseSpeed;
 if(active)p.baseSpeed*=2.35;
 try{return _coopVoss113.call(this,p,dt,input)}finally{p.baseSpeed=base;if(active){p.vossReverse=Math.max(0,p.vossReverse-dt);p.vossAfterimages??=[];p.vossAfterimageClock=(p.vossAfterimageClock||0)+dt;if(p.vossAfterimageClock>=0){p.vossAfterimageClock=-1;for(let i=0;i<6;i++){const d=p.a+i*Math.PI/3;p.vossAfterimages.push({x:p.x+Math.cos(d)*14,y:p.y+Math.sin(d)*14,a:d,drift:d,life:2.4,maxLife:2.4})}}}p.vossAfterimages=(p.vossAfterimages||[]).filter(d=>d.life>0).slice(-6);}
};

// Read-only world helpers reuse the current single-player combat catalog and hazards.
for(const method of ['runScheduledAces','supportAuraAt','enemyCapacity','isOpeningCountryside','regularEnemyLimit','regularSpawnInterval','aircraftMix','friendlyAircraftMix','queueBossLevel','resolveBossLevels','spawnComposition','canSpawnRevision','tickRevisionWorld','revisionDecoyTarget','burst','smoke','combatBlast','aceWaveCount','nextAceWaveAt','prepareBossWave','worldRegion','clearRegionalHazards','spawnMinefield','spawnGas','wreckGust','patrolCanEngage','spawnPatrol','hitPatrol','updatePatrols','targetCollision','canHitTarget','fieldVolley','combatWorld','dropSpecialAmmo','dropObservationRepair','dogfightSteering','tickBattleDirector','beginBattleDirectorPattern','canOfferBattlefieldEvent','offerBattlefieldEvent','acceptBattlefieldEvent','declineBattlefieldEvent','tickBattlefieldEvents','tickRivalAce','mobSpawnsSuppressed','_pickHeavy'])CoopGame.prototype[method]=Game.prototype[method];

// Cloud concealment: per-player conceal timers + enemy lock-breaking, same rules as solo.
installCloudCover(CoopGame);
