import {fx} from './fx-art.js?v=perf538';
import {GALLIPOLI_PARTS} from './gallipoli-boss.js?v=perf538';
import {GALLIPOLI_ROUTE} from './gallipoli-route.js?v=perf538';
import {periodicSandPixels,maanGroundTiles} from './maan-ground.js?v=perf538';
export const GALLIPOLI_ASSETS=Object.freeze({atlas:'gallipoli-fortress-atlas.webp',coast:'asset-bank/terrain/gallipoli_coast.webp',sea:'terrain-sea359r2.webp',central:'gallipoli-overlay-central.webp',entente:'gallipoli-overlay-entente.webp'});
const images=new Map(),tiles=new Map(),pending=new Map();
function load(k){if(!GALLIPOLI_ASSETS[k])return null;if(images.has(k))return images.get(k);const im=new Image();images.set(k,im);im.decoding='async';im.crossOrigin='anonymous';pending.set(k,new Promise((resolve,reject)=>{im.onload=()=>im.naturalWidth?resolve(im):reject(new Error('Gallipoli empty asset '+k));im.onerror=()=>reject(new Error('Gallipoli asset '+k));}));im.src='./'+GALLIPOLI_ASSETS[k]+'?v=perf538';return im;}
function canvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function bake(im,key,sy=0,sh=im.naturalHeight){if(tiles.has(key))return tiles.get(key);const c=canvas(im.naturalWidth,sh),ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,sy,im.naturalWidth,sh,0,0,c.width,sh);const p=periodicSandPixels(ctx.getImageData(0,0,c.width,sh).data,c.width,sh),t=canvas(p.width,p.height),tc=t.getContext('2d'),data=tc.createImageData(p.width,p.height);data.data.set(p.data);tc.putImageData(data,0,0);tiles.set(key,t);return t;}
export function prepareGallipoliAssets(region){if(region!==14){images.clear();pending.clear();tiles.clear();return Promise.resolve();}const sea=load('sea'),coast=load('coast');for(const k of Object.keys(GALLIPOLI_ASSETS))load(k);return Promise.all([...pending.values()]).then(()=>{if(images.get('coast')!==coast)return;bake(sea,'sea');bake(coast,'land',0,820);bakeCoast(coast);});}
function tile(c,im,x,y,w,h){for(const q of maanGroundTiles(x+w/2,y+h/2,w,h,im.width,im.height))c.drawImage(im,q.x+x,q.y+y,q.width,q.height);}
export function paintGallipoli(c,g,cx,cy,w,h){const r=g?.gallipoliRoute;if(!r)return;c.save();c.translate(w/2-cx,h/2-cy);c.translate(r.x,r.y);c.rotate(r.a+Math.PI/2);const dx=cx-r.x,dy=cy-r.y,n=-Math.sin(r.a)*dx+Math.cos(r.a)*dy,s=Math.cos(r.a)*dx+Math.sin(r.a)*dy,span=Math.hypot(w,h)/2+160,left=n-span,top=-s-span,width=span*2,height=span*2;const sea=tiles.get('sea'),land=tiles.get('land');if(sea)tile(c,sea,left,top,width,height);if(land){c.save();c.beginPath();c.rect(left,top,width,Math.max(0,-GALLIPOLI_ROUTE.shore-top));c.clip();tile(c,land,left,top,width,height);c.restore();}
 // A continuous horizontal strip with normalized edge samples and soft end masks.
 const coast=tiles.get('coast');if(coast){const pw=coast.width,ph=coast.height,shoreY=-GALLIPOLI_ROUTE.shore;for(let ix=Math.floor(left/pw);ix<Math.ceil((left+width)/pw);ix++)c.drawImage(coast,ix*pw,shoreY-1000,pw,ph);}
 c.restore();
 if(!g.stageBoss?.stages.encounter&&s>GALLIPOLI_ROUTE.fort-span-300){const body={x:r.x+Math.cos(r.a)*GALLIPOLI_ROUTE.fort,y:r.y+Math.sin(r.a)*GALLIPOLI_ROUTE.fort,phase:'coastal-defense',coreAngle:Math.PI/2,hp:1,maxHp:1,faction:g.stageBoss?.stages.teamFaction==='central'?'entente':'central',parts:new Map(GALLIPOLI_PARTS.map(p=>[p.id,{...p,hp:1,maxHp:1,angle:Math.PI/2}]))};c.save();c.translate(w/2-cx,h/2-cy);drawGallipoliBoss(c,body);c.restore();}
}
// Measured fixed rectangles: state changes keep the same mounting pivot.
const rows=[[0,270],[268,290],[558,238],[790,234]];
function sprite(c,row,state,x,y,w,angle=0,pivotY=.5){const im=load('atlas');if(!im.naturalWidth)return;const [sy,sh]=rows[row],sx=state*512;c.save();c.translate(x,y);c.rotate(angle);c.imageSmoothingEnabled=true;const h=w*sh/512;c.drawImage(im,sx,sy,512,sh,-w*.555,-h*pivotY,w,h);c.restore();}
export function drawGallipoliBoss(c,b){const state=p=>b.dead||p?.destroyed?2:p&&p.hp<p.maxHp*.55?1:0;c.save();const foundation=b.dead?2:b.phase==='central-fortress'?1:0;sprite(c,0,foundation,b.x,b.y,710,0,.56);for(const p of b.parts.values()){const row=p.id==='observer'?2:p.id==='left'||p.id==='right'?1:3;sprite(c,row,state(p),b.x+p.x,b.y+p.y,p.size*(row===1?1.8:1.7),row===1?p.angle+Math.PI/2:0,row===1?.63:.5);if(p.destroyed)fx(c,'smokeDark',b.x+p.x,b.y+p.y,42,55,0,.2);}
 sprite(c,1,b.dead?2:b.hp<b.maxHp*.55?1:0,b.x,b.y,410,b.coreAngle+Math.PI/2,.63);
 const im=load(b.faction);if(im?.naturalWidth){for(const side of [-1,1]){const p=b.parts.get(side<0?'left':'right');if(!p.destroyed&&!b.dead)c.drawImage(im,b.x+side*236-22,b.y-85,44,48);}}
 if(b.lane?.remaining>0){c.strokeStyle='#b9c6a5';c.lineWidth=1.5;c.setLineDash([8,9]);for(const side of [-1,1]){c.beginPath();c.moveTo(b.lane.x+side*55,b.lane.y-120);c.lineTo(b.lane.x+side*55,b.lane.y+270);c.stroke();}c.setLineDash([]);}c.restore();}

function bakeCoast(im){const w=im.naturalWidth,h=im.naturalHeight,b=80,pw=w-2*b,src=canvas(w,h),sc=src.getContext('2d',{willReadFrequently:true});sc.drawImage(im,0,0);const data=sc.getImageData(0,0,w,h).data,t=canvas(pw,h),tc=t.getContext('2d'),out=tc.createImageData(pw,h);for(let y=0;y<h;y++)for(let x=0;x<pw;x++){const q=Math.min(1,x/(2*b)),a=q*q*(3-2*q),i=(y*pw+x)*4,j=(y*w+x)*4,k=(y*w+x+pw)*4;for(let c=0;c<3;c++)out.data[i+c]=x<2*b?data[j+c]*a+data[k+c]*(1-a):data[j+c];out.data[i+3]=255*Math.min(1,y/180,(h-1-y)/110);}for(let y=0;y<h;y++)out.data.set(out.data.subarray(y*pw*4,y*pw*4+4),(y*pw+pw-1)*4);tc.putImageData(out,0,0);tiles.set('coast',t);}
