import {NAVAL_BOSS_STATIONS} from './naval-faction-atlas.js?v=splash1';
import {separateBossFleet} from './naval-spacing.js?v=splash1';
import {recordShipWake} from './naval-water.js?v=splash1';
import {BaseBoss,BossPart,BossEncounter} from './headon-stageboss-core.js?v=splash1';
import {segmentDistance} from './alps-geometry117.js?v=splash1';
export const JUTLAND_CYCLE=48;
export const angleDelta=(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a));
export const turnToward=(a,b,rate,dt)=>a+Math.max(-rate*dt,Math.min(rate*dt,angleDelta(a,b)));
export const jutlandRotate=(x,y,a)=>({x:x*Math.cos(a)-y*Math.sin(a),y:x*Math.sin(a)+y*Math.cos(a)});
const gun=(id,x,y,row=0)=>({id,localX:x,localY:y,row,kind:'gun',radius:row?25:37,fraction:.08,size:row?85:112});
export const JUTLAND_PARTS=Object.freeze({
 battleship:[gun('bow-port',-64,-302),gun('bow-starboard',64,-302),gun('aft-port',-92,-54),gun('aft-starboard',92,-54),{id:'director',localX:0,localY:-235,row:3,kind:'director',radius:36,fraction:.1,size:98},{id:'boilers',localX:0,localY:-114,kind:'engine',radius:44,fraction:.12},{id:'seaplane-deck',localX:0,localY:145,kind:'launch',radius:36,fraction:.08}],
 cruiser:[gun('bow',0,-178,1),gun('aft',0,159,1),{id:'torpedo-port',localX:-38,localY:-42,row:2,kind:'torpedo',radius:22,fraction:.12,size:54},{id:'torpedo-starboard',localX:38,localY:-42,row:2,kind:'torpedo',radius:22,fraction:.12,size:54},{id:'boilers',localX:0,localY:-20,kind:'engine',radius:33,fraction:.15}],
 observer:[{id:'gondola',localX:0,localY:100,kind:'observer',radius:35,fraction:.5}]
});
export function jutlandMuzzle(b,p){return{x:b.x+p.x+Math.cos(p.angle)*(p.kind==='torpedo'?50:p.row===1?85:128),y:b.y+p.y+Math.sin(p.angle)*(p.kind==='torpedo'?50:p.row===1?85:128)};}
export class JutlandVessel extends BaseBoss{
 constructor(o){o={...o,faction:o.faction||'central'};const mounts=NAVAL_BOSS_STATIONS[o.faction]?.[o.role]||{},width=o.role==='battleship'?254:137,height=o.role==='battleship'?940:610;const specs=JUTLAND_PARTS[o.role].map(p=>mounts[p.id]?{...p,localX:mounts[p.id][0]*width,localY:(mounts[p.id][1]-.5)*height}:p);super({...o,maxHp:o.tuning.maxHp,coreRadius:o.role==='observer'?40:65,parts:specs.map(p=>new BossPart({id:p.id,maxHp:o.tuning.maxHp*p.fraction,radius:p.radius,kind:p.kind}))});
 Object.assign(this,{t:o.tuning,faction:o.faction,role:o.role,slot:o.slot||0,fleet:o.fleet,jutlandBoss:true,jutlandAirship:o.role==='observer',kind:'jutland-'+o.role,ownsMotion129:true,hullYaw:0,entryAge:0,shotClock:0,launchClock:0,driveVelocity:0,anchorX:o.x,anchorY:o.y,width:o.role==='battleship'?254:o.role==='cruiser'?137:143,height:o.role==='battleship'?940:o.role==='cruiser'?610:430});
 for(const spec of specs)Object.assign(this.parts.get(spec.id),spec,{angle:-Math.PI/2,recoil:0});this.updateParts();}
 command(type,spec={}){this.emit({...spec,type,bossId:this.id,faction:this.faction});}
 updateParts(){for(const p of this.parts.values())Object.assign(p,jutlandRotate(p.localX,p.localY,this.hullYaw));}
 locateHit(s){if(this.entryAge<5||this.dead)return null;const x0=(s.previousX??s.x)-this.x,y0=(s.previousY??s.y)-this.y,x1=s.x-this.x,y1=s.y-this.y,r=s.radius||0;
 for(const p of this.parts.values())if(!p.destroyed&&segmentDistance(p.x,p.y,x0,y0,x1,y1)<=p.radius+r)return{partId:p.id};
 const a=jutlandRotate(x0,y0,-this.hullYaw),b=jutlandRotate(x1,y1,-this.hullYaw);return segmentDistance(0,0,a.x/(this.width*.43+r),a.y/(this.height*.46+r),b.x/(this.width*.43+r),b.y/(this.height*.46+r))<=1?{partId:null}:null;}
 hitAt(s){const h=this.locateHit(s);return h?this.hit({...h,damage:s.damage}):{damage:0,miss:true};}
 hit(a){if(!Number.isFinite(a.damage)||a.damage<0)throw new Error('Invalid damage');if(this.dead||this.entryAge<5)return{damage:0,blocked:true};const r=super.hit(a);if(a.partId&&r.damage){this.hp=Math.max(0,this.hp-r.damage);if(this.hp<=0)this.finish();}if(this.dead)this.finishCleanup();return{...r,bodyDefeated:this.dead};}
 finish(){if(this.dead)return;this.hp=0;this.dead=true;this.phase='defeated';this.command('body-defeated');this.finishCleanup();}
 finishCleanup(){if(this.deathHandled)return;this.deathHandled=true;this.destroyedAt=this.fleet.clock;this.pending=null;for(const p of this.parts.values()){p.aimTarget=null;this.command('cancel-hazards',{tag:this.id+':'+p.id});}this.command('cancel-hazards',{tag:this.id+':recon'});this.checkObserverRetreat();}
 checkObserverRetreat(){const bodies=this.fleet.bodies;if(bodies?.filter(b=>!b.jutlandAirship).every(b=>b.dead)){const observer=bodies.find(b=>b.jutlandAirship);if(observer&&!observer.dead){observer.retreating=true;observer.finish();}}}
 onPartDestroyed(p){this.command('cancel-hazards',{tag:this.id+':'+p.id});p.aimTarget=null;if(this.pending?.partId===p.id)this.pending=null;const phase={director:'jutland-director-lost',observer:'jutland-observer-lost',launch:'jutland-recon-disabled',torpedo:'jutland-tubes-lost',engine:'jutland-boilers-lost'}[p.kind];if(phase)this.command('phase-change',{phase});if(p.kind==='launch'){this.command('cancel-hazards',{tag:this.id+':recon'});this.reconPending=null;}}
 observed(){const b=this.fleet.bodies.find(b=>b.jutlandAirship);return b&&!b.dead&&!b.parts.get('gondola').destroyed;}
 coordinated(){const b=this.fleet.bodies.find(b=>b.role==='battleship');return b&&!b.dead&&!b.parts.get('director').destroyed;}
 updateFleet(dt){if(this.fleet.bodies.find(b=>!b.dead)!==this)return;const f=this.fleet;f.clock+=dt;const age=Math.max(0,f.clock-5)%JUTLAND_CYCLE,phase=age<10?'ranging':age<18?'crossing-turn':age<25?'crossing-fire':age<34?'turn-away':'reform';if(phase!==f.phase){f.phase=phase;this.command('phase-change',{phase:'jutland-'+phase});}this.checkObserverRetreat();}
 move(dt){const phase=this.fleet.phase,turn=phase==='crossing-turn'||phase==='crossing-fire'?Math.PI/2:phase==='turn-away'?Math.PI:0,edge=Math.abs(this.x-this.anchorX)>1050||Math.abs(this.y-this.anchorY)>900;
 const target=edge?Math.atan2(this.anchorY-this.y,this.anchorX-this.x)+Math.PI/2:turn;this.hullYaw=turnToward(this.hullYaw,target,this.jutlandAirship?.32:this.role==='battleship'?.12:.16,dt);const speed=this.jutlandAirship?19:this.parts.get('boilers')?.destroyed?11:this.role==='battleship'?52:64;
 const desired=this.entryAge<5?0:speed;this.driveVelocity+=Math.max(-10*dt,Math.min(8*dt,desired-this.driveVelocity));this.x+=Math.sin(this.hullYaw)*this.driveVelocity*dt;this.y-=Math.cos(this.hullYaw)*this.driveVelocity*dt;this.updateParts();if(!this.jutlandAirship)recordShipWake(this,dt,this.height);}
 plan(target,kind){const weapons=[...this.parts.values()].filter(p=>!p.destroyed&&p.kind===(kind==='torpedo'?'torpedo':'gun'));if(!weapons.length)return;const p=weapons[this.fleet.cursor++%weapons.length],point={x:target.x,y:target.y},side=this.slot%2?-1:1;p.aimTarget=point;this.pending={partId:p.id,target:point,kind};
 if(kind==='shell'){const count=this.fleet.phase==='crossing-fire'&&this.coordinated()?2:1;this.pending.shots=Array.from({length:count},(_,i)=>({x:point.x+(i?side*220:side*170),y:point.y+(i?140:0),radius:this.role==='battleship'?64:45,warning:this.observed()?2:2.7,delay:i*.35,damage:this.t.damage,tag:this.id+':'+p.id}));}}
 fire(dt){const a=this.pending;if(!a)return;const p=this.parts.get(a.partId);if(!p||p.destroyed){this.pending=null;return;}const aim=Math.atan2(a.target.y-this.y-p.y,a.target.x-this.x-p.x);p.angle=turnToward(p.angle,aim,p.kind==='torpedo'?1:.85,dt);if(Math.abs(angleDelta(p.angle,aim))>.065)return;const m=jutlandMuzzle(this,p);p.recoil=.22;p.aimTarget=null;this.command('muzzle',{...m});
 if(a.kind==='shell'){for(const shot of a.shots)this.command('hazard',{kind:'circle',duration:.55,once:true,visual:'jutland-shell',...shot});}
 else{const direction=p.angle;this.command('hazard',{kind:'beam',x:m.x,y:m.y,angle:direction,length:1250,thickness:22,damage:0,warning:2,duration:.05,visual:'jutland-track',tag:this.id+':'+p.id});this.command('hazard',{kind:'projectile',x:m.x,y:m.y,vx:Math.cos(direction)*170,vy:Math.sin(direction)*170,radius:13,damage:this.t.damage*1.15,warning:2,duration:7,once:true,visual:'jutland-torpedo',tag:this.id+':'+p.id});}this.pending=null;this.shotClock=0;}
 recon(dt,players){if(this.role!=='battleship'||this.parts.get('seaplane-deck').destroyed)return;this.launchClock+=dt;if(this.reconPending){this.reconPending.age+=dt;const present=(this.formationStatus129?.()||[]).some(p=>p.role==='jutland-recon');if(this.reconPending.age>=2){if(present)this.command('hazard',{kind:'circle',x:this.reconPending.x,y:this.reconPending.y,radius:52,damage:this.t.damage*.65,warning:2.5,duration:.4,once:true,visual:'jutland-shell',tag:this.id+':recon'});this.reconPending=null;}}
 if(this.launchClock<19||(this.countMinions129?.()||0)>=2)return;const target=players.find(p=>p.alive);if(!target)return;this.launchClock=0;const p=this.parts.get('seaplane-deck'),m={x:this.x+p.x,y:this.y+p.y};this.command('phase-change',{phase:'jutland-recon-pass'});this.command('spawn-minion',{minion:'jutland-recon',plane:this.faction==='central'?'ff33':'macchi_m3',behavior:'attack-pass',formationRole:'jutland-recon',x:m.x,y:m.y,a:Math.atan2(target.y-m.y,target.x-m.x),passTargetX:target.x,passTargetY:target.y,hp:42,life:7,fire:Infinity});this.reconPending={age:0,x:target.x,y:target.y};}
 update(dt,{players}){if(this.dead)return;this.updateFleet(dt);this.entryAge=Math.min(5,this.entryAge+dt);this.move(dt);for(const p of this.parts.values())p.recoil=Math.max(0,p.recoil-dt);if(this.entryAge<5||this.jutlandAirship)return;this.recon(dt,players);const phase=this.fleet.phase;if(phase==='crossing-turn'||phase==='turn-away'&&this.role==='battleship'){this.pending=null;return;}const live=players.filter(p=>p.alive),target=live[this.slot%Math.max(1,live.length)];if(!target)return;this.shotClock+=dt*Math.min(1.5,this.t.patternMultiplier||1);if(!this.pending&&this.shotClock>=(phase==='turn-away'?4.5:phase==='crossing-fire'?4:6))this.plan(target,phase==='turn-away'?'torpedo':'shell');this.fire(dt);}
}
export function createJutlandEncounter(o){const fleet={clock:0,phase:'ranging',cursor:0,bodies:[]},specs=[['battleship',0,0,.5],['cruiser',-780,100,.2],['cruiser',780,-80,.2],['observer',380,-800,.1]];const bodies=specs.map(([role,dx,dy,fraction],slot)=>new JutlandVessel({...o,id:o.id+':'+slot,role,slot,fleet,tuning:{...o.tuning,maxHp:o.tuning.maxHp*fraction},x:o.x+dx,y:o.y+dy}));fleet.bodies=bodies;const fleetShips=bodies.filter(b=>b.jutlandBoss&&!b.jutlandAirship);const encounter=new BossEncounter({id:o.id,bossId:o.bossId,bodies}),update=encounter.update.bind(encounter);encounter.update=(dt,frame)=>{update(dt,frame);if(!frame.paused)separateBossFleet(fleetShips);};return encounter;}
