CREATE TABLE IF NOT EXISTS priority_scores_49 (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, score INTEGER NOT NULL, pilot TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS priority_scores_49_order ON priority_scores_49(score DESC, created_at ASC);
