import test from 'node:test';
import assert from 'node:assert/strict';
import {CITY_DEFENSE,spawnCityDefense,tickCityDefense} from '../city-defense.js?v=480';
import {DrachenMineNet,LondonApron,createBossEncounter} from '../headon-stageboss-patterns.js?v=somme20261001';
import {CityFlakCell} from '../city-flak-combat.js?v=480';
import {DRACHEN_MINES,CITY_GUNS} from '../city-airship-combat378.js?v=480';
import {fixture,step} from './stageboss-fixture94.mjs';
const tuning={maxHp:2400,partHp:288,damage:18,bulletSpeed:270,geometryScale:2.025,regionalViewWidth:960,regionalViewHeight:700};
const frame={players:[{id:'p1',alive:true,x:-80,y:260,vx:0,vy:0},{id:'p2',alive:true,x:100,y:260,vx:0,vy:0}],bounds:{left:-480,right:480,top:-350,bottom:350}};
function ambient(){const p1={id:'p1',x:0,y:0,hp:100,status:'alive',a:0,speed:0},p2={id:'p2',x:0,y:600,hp:100,status:'alive',a:0,speed:0};return{x:0,y:0,a:0,t:0,state:'playing',players:[p1,p2],enemies:[],bullets:[],worldRegion:()=>4,rng:()=>.5,event(){},burst(){},spawnEnemy(){const e={};this.enemies.push(e);return e;}};}
function ambientTick(g,s){for(let i=0;i<Math.ceil(s/.02);i++){g.t+=.02;tickCityDefense(g,.02);}}
function cell(events=[]){return new CityFlakCell({id:'cell',x:0,y:0,faction:'entente',tuning:{...tuning,maxHp:600,cityScale:.7},emit:e=>events.push(e)});}
function network(w=960,h=700){const events=[],enc=createBossEncounter({id:'city',bossId:'flak-tower',x:0,y:0,faction:'entente',tuning:{...tuning,regionalViewWidth:w,regionalViewHeight:h},emit:e=>events.push(e)});enc.update(.65,frame);return{enc,events};}
test('ordinary city deploys two linked lights and two real guns, bounded to one sector',()=>{const g=ambient();spawnCityDefense(g);spawnCityDefense(g);assert.equal(g.enemies.length,4);for(const p of g.enemies.filter(e=>e.cityUnit==='pit'))assert.ok(p.cityLamp?.cityUnit==='light');});
test('illumination belongs to the pilot inside the beam, not the co-op camera',()=>{const g=ambient();spawnCityDefense(g);const lamp=g.enemies[0];g.players[0].x=lamp.x-220;g.players[0].y=lamp.y;lamp.scanPhase=0;for(let i=0;i<70;i++){const angle=lamp.scanBase+Math.sin((g.t+.02)*.22)*.95;g.players[0].x=lamp.x+Math.cos(angle)*220;g.players[0].y=lamp.y+Math.sin(angle)*220;g.t+=.02;tickCityDefense(g,.02);}assert.ok(g.players[0].illuminatedUntil>g.t);assert.equal(g.players[1].illuminatedUntil,0);});
test('city aim locks before firing and lamp destruction cancels the queued volley',()=>{const g=ambient();spawnCityDefense(g);const pit=g.enemies.find(e=>e.cityUnit==='pit'),lamp=pit.cityLamp;lamp.lit.set('p1',20);pit.fireT=0;tickCityDefense(g,.02);assert.ok(pit.cityShot);assert.equal(g.bullets.length,0);const aim=[pit.cityShot.x,pit.cityShot.y];g.players[0].x=140;tickCityDefense(g,.02);assert.deepEqual([pit.cityShot.x,pit.cityShot.y],aim);lamp.hp=0;ambientTick(g,1);assert.equal(pit.cityShot,null);assert.equal(g.bullets.length,0);});
test('clouds cancel lock; surviving linked gun fires one three-round warning volley',()=>{const g=ambient();spawnCityDefense(g);const pit=g.enemies.find(e=>e.cityUnit==='pit'),lamp=pit.cityLamp;lamp.lit.set('p1',20);pit.fireT=0;tickCityDefense(g,.02);g.players[0].cloudConceal=1;tickCityDefense(g,.02);assert.equal(pit.cityShot,null);g.players[0].cloudConceal=0;lamp.lit.set('p1',20);pit.fireT=0;tickCityDefense(g,.02);ambientTick(g,CITY_DEFENSE.warning+.02);assert.equal(g.bullets.length,3);assert.ok(g.bullets.every(b=>b.hazardRegion===4&&b.enemy));});
test('boss phase, London and pause prevent ambient city attacks and clock advancement',()=>{const g=ambient();spawnCityDefense(g);const pit=g.enemies[1];pit.cityShot={id:'p1',x:0,y:0,remaining:.5};g.state='paused';tickCityDefense(g,.04);assert.equal(pit.cityShot.remaining,.5);g.state='playing';g.stageBoss={stages:{phase:'boss'}};tickCityDefense(g,.02);assert.equal(pit.cityShot,null);g.worldRegion=()=>11;g.stageBoss=null;ambientTick(g,2);assert.equal(g.bullets.length,0);assert.equal(g._citySpawned,false);});
test('cleared city sector reappears after cooldown without exceeding four live installations',()=>{const g=ambient();tickCityDefense(g,.02);g.enemies.forEach(e=>e.hp=0);ambientTick(g,4);assert.equal(g.enemies.filter(e=>e.hp>0).length,0);ambientTick(g,6);assert.equal(g.enemies.filter(e=>e.hp>0).length,4);});
for(const [w,h] of [[390,844],[1280,800]])test(`four city towers fit ${w}x${h} and conserve the host HP budget`,()=>{const {enc,events}=network(w,h);assert.equal(enc.bodies.size,4);assert.equal([...enc.bodies.values()].reduce((n,b)=>n+b.hp,0),tuning.maxHp);for(const b of enc.bodies.values()){assert.ok(Math.abs(b.x)+190*b.regionalScale<w/2);assert.ok(Math.abs(b.y)+190*b.regionalScale<h/2);assert.ok([...b.parts.values()].every(p=>p.maxHp<=b.maxHp*.16));}assert.ok(!events.some(e=>e.type==='split'));});
test('two destroyed mounts open one tower core and transfer damage only once',()=>{const b=cell(),hp=b.hp;const ears=b.parts.get('ears');const r=b.hit({partId:'ears',damage:99999});assert.equal(r.damage,ears.maxHp);assert.equal(b.hp,hp-ears.maxHp*.8);assert.equal(b.coreVulnerable,false);b.hit({partId:'gun-bl',damage:99999});assert.equal(b.coreVulnerable,true);assert.equal(b.locateHit({x:0,y:0}).partId,null);});
test('destroying horns cancels pending tracked shell and fixed blind fire does not follow pilots',()=>{const e=[],b=cell(e);assert.ok(b.planShell(130,170));b.hit({partId:'ears',damage:9999});assert.equal(b.shellLock,null);assert.equal(b.planShell(400,400),false);b.timers.set('siege',0);b.update(.02,{...frame,players:[{id:'p',alive:true,x:430,y:-260}]});assert.equal(b.shellLock.mode,'blind');assert.ok(Math.abs(b.shellLock.x)<1e-6);assert.equal(b.shellLock.y,250*b.regionalScale);});
test('city artillery turns without snapping, then fires from its rendered muzzle at the locked point',()=>{const e=[],b=cell(e),p=b.parts.get('siege');b.planShell(120,150);const target=[b.shellLock.x,b.shellLock.y];for(let i=0;i<260&&!e.some(e=>e.visual==='city-flak-shell');i++){const before=p.angle;b.update(.02,frame);assert.ok(Math.abs(p.angle-before)<=.85*.02+1e-9);}const shell=e.find(e=>e.visual==='city-flak-shell');assert.ok(shell);assert.deepEqual([shell.x,shell.y],target);const muzzle=b.muzzle(p);assert.ok(Math.hypot(shell.sourceX-muzzle.x,shell.sourceY-muzzle.y)<1e-8);assert.equal(shell.warning,1.35);});
test('destroyed tower weapons stop all attacks, and a surviving core can be destroyed',()=>{const e=[],b=cell(e);for(const p of b.parts.values())b.hit({partId:p.id,damage:99999});e.length=0;for(let i=0;i<1600;i++)b.update(.02,frame);assert.equal(e.some(e=>e.type==='hazard'||e.type==='spawn-minefield'),false);assert.ok(b.hp>0);assert.equal(b.hitAt({x:0,y:0,damage:9999}).bodyDefeated,true);});
test('each dead city tower remains visible as a wreck before the other three are defeated',()=>{const f=fixture({stageIndex:4,teamFaction:'central'});f.addon.startBoss({x:400,y:300});step(f,.7);const first=[...f.addon.stages.encounter.bodies.values()][0];for(const p of first.parts.values())first.hit({partId:p.id,damage:9999});first.hit({damage:9999});assert.equal(f.addon.stages.encounter.completed,false);const bodies=[];return import('../headon-stageboss-render.js?v=somme20261001').then(({renderStageBossLayer})=>{renderStageBossLayer(f.addon,{drawBody:b=>bodies.push(b),drawPart(){},drawHazard(){}});assert.equal(bodies.length,4);assert.ok(bodies.find(b=>b.x===first.x&&b.y===first.y).destroying);});});
test('Drachen drift shares its transform with hulls, mine mounts and gun launches',()=>{const events=[],b=new DrachenMineNet({id:'d',x:0,y:0,tuning,emit:e=>events.push(e),rng:()=>.37});b.update(.5,frame);assert.ok(b.cityRigOffsets.some(o=>o[0]!==0));for(const p of b.parts.values())assert.equal(b.locateHit({x:p.x,y:p.y}).partId,p.id);for(let i=0;i<3;i++){const q=b.point(...DRACHEN_MINES[i][0],i);assert.equal(b.locateHit(q).partId,'rig-'+i);}for(let j=0;j<400;j++)b.update(.02,frame);assert.ok(events.some(e=>e.type==='spawn-minefield'));});
test('Drachen fastest-loop waves leave a real corridor through earlier queued mines and keep regenerating after losing two rigs',()=>{const events=[],b=new DrachenMineNet({id:'d',x:0,y:0,tuning:{...tuning,patternMultiplier:3},emit:e=>events.push(e),rng:()=>.37});b.hit({partId:'airship-0',damage:9999});b.hit({partId:'airship-1',damage:9999});let lane;for(let i=0;i<2000;i++){b.update(.02,frame);while(events.length){const e=events.shift();if(e.type==='city-mine-lane')lane=e;if(e.type==='spawn-minefield'){assert.ok(Math.abs(e.points[0].x-lane.x)>=lane.width/2);assert.equal(e.rigIndex,2);assert.equal(e.maxMines,26);}}}assert.ok(b.netWave>=10);assert.ok(b.parts.get('airship-2').hp>0);});
test('London apron keeps its original geometry and stationary motion',()=>{const b=new LondonApron({id:'l',x:3,y:5,tuning});const pose=[b.x,b.y,b.cityArtScale,...[...b.parts.values()].flatMap(p=>[p.x,p.y])];for(let i=0;i<400;i++)b.update(.02,frame);assert.deepEqual([b.x,b.y,b.cityArtScale,...[...b.parts.values()].flatMap(p=>[p.x,p.y])],pose);assert.equal(b.cityRigOffsets,undefined);});
test('city encounter pause freezes drift and queued artillery; ordinary stage IDs remain distinct',()=>{const f=fixture({stageIndex:4});f.addon.startBoss({x:0,y:0});step(f,1);const b=[...f.addon.stages.encounter.bodies.values()][0],before=JSON.stringify([b.cityRigOffsets,b.mineQueue,f.addon.time]);f.frame.paused=true;step(f,1);assert.equal(JSON.stringify([b.cityRigOffsets,b.mineQueue,f.addon.time]),before);assert.equal(f.addon.stages.bossId,'drachen-net');const london=fixture({stageIndex:11});assert.equal(london.addon.stages.bossId,'gotha-squadron');});
