import test from 'node:test';
import assert from 'node:assert/strict';
globalThis.Image??=class{set src(v){this._src=v;queueMicrotask(()=>this.onload?.())}};
globalThis.document??={createElement:()=>({getContext:()=>null})};
const {CoopGame}=await import('../coop-engine.js?v=485');
const {enableStageBoss,beginStageBossFrame,endStageBossFrame}=await import('../stageboss-host.js?v=485');
const {spawnCityDefense,tickCityDefense}=await import('../city-defense.js?v=485');
const {fixture,step}=await import('./stageboss-fixture94.mjs');
function game(){const g=new CoopGame([{pilot:'baron'},{pilot:'voss'}],{rng:()=>.5});enableStageBoss(g,{teamFaction:g.teamFaction,heavyHp:1.65});g.stageBoss.stages.stageIndex=4;g.region=4;for(const p of g.players)p.invuln=9999;return g;}
test('co-op own update runs city defense once and never draws ordinary fire from installations',()=>{const g=game();g.update(.02,{});assert.equal(g.enemies.filter(e=>e.cityUnit).length,4);assert.equal(g._citySerial,1);const units=g.enemies.filter(e=>e.cityUnit),before=g.bullets.length;for(const e of units)g.fireEnemy(e);assert.equal(g.bullets.length,before);const t=g.t;g.pause();g.update(.04,{});assert.equal(g.t,t);});
test('real host conserves scaled HP once, opens every core and clears only after all towers die',()=>{const g=game(),enc=g.stageBoss.startBoss({x:0,y:0}),budget=enc.maxHpBudget;for(let i=0;i<35;i++)endStageBossFrame(g,.02);assert.equal(enc.bodies.size,4);assert.equal([...enc.bodies.values()].reduce((n,b)=>n+b.hp,0),budget);const cells=[...enc.bodies.values()];for(let i=0;i<4;i++){const b=cells[i];b.hit({partId:'ears',damage:99999});b.hit({partId:'siege',damage:99999});b.hit({damage:99999});assert.equal(enc.completed,i===3);}assert.equal(g.stageBoss.hazards.pool.count,0);});
test('host mine corridor removes earlier blocking mines without chaining them into a blast',()=>{const g=game();g.teamFaction='entente';g.stageBoss.dispose();g.stageBoss=null;enableStageBoss(g,{teamFaction:'entente'});g.stageBoss.stages.stageIndex=4;const enc=g.stageBoss.startBoss({x:0,y:0}),b=[...enc.bodies.values()][0];g.hostileMinefields=[{encounterId:enc.id,mines:[{x:0,y:0,targetX:0,hp:18,dead:false,chainHandled:false},{x:200,y:0,targetX:200,hp:18,dead:false,chainHandled:false}]}];const fx=g.combatFX.length;b.command('city-mine-lane',{x:0,width:110});assert.ok(g.hostileMinefields[0].mines[0].dead);assert.ok(g.hostileMinefields[0].mines[0].chainHandled);assert.equal(g.hostileMinefields[0].mines[1].dead,false);assert.equal(g.combatFX.length,fx);});
test('real host mines deploy from a live rig, settle after warning, cap at 26 and clean on disposal',()=>{const g=game();g.stageBoss.dispose();g.stageBoss=null;enableStageBoss(g,{teamFaction:'entente'});g.stageBoss.stages.stageIndex=4;const enc=g.stageBoss.startBoss({x:0,y:0}),b=[...enc.bodies.values()][0];const ctx={players:[{id:'p1',alive:true,x:0,y:180}],bounds:{left:-480,right:480,top:-350,bottom:350}};for(let i=0;i<1700;i++){g.t+=.02;b.update(.02,ctx);g.updateHazards(.02);beginStageBossFrame(g,.02);assert.ok(g.hostileMinefields.reduce((n,f)=>n+f.mines.filter(m=>!m.dead).length,0)<=26);}assert.ok(g.hostileMinefields.length>0);assert.ok(g.hostileMinefields.some(f=>f.mines.some(m=>!m.dead&&!m.deploying)));g.stageBoss.dispose();assert.equal(g.hostileMinefields.length,0);});
test('city shell activation has one sprite impact and no duplicate generic host blast',()=>{const g=game(),enc=g.stageBoss.startBoss({x:0,y:0});for(let i=0;i<35;i++)endStageBossFrame(g,.02);const b=[...enc.bodies.values()][0];const old=g.combatFX.length;b.hazard('circle',{x:200,y:200,radius:40,warning:.1,duration:.48,once:true,visual:'city-flak-shell'});g.stageBoss.hazards.update(.12,{players:[]});assert.equal(g.combatFX.length,old);});
for(const faction of ['central','entente'])test(`city ${faction} loop-3 battle remains bounded through 120 seconds`,()=>{const f=fixture({teamFaction:faction,stageIndex:4});f.hooks.getTuning=()=>({maxHp:4500,partHp:500,damage:18,bulletSpeed:270,patternMultiplier:3,projectileDensity:2,regionalViewWidth:390,regionalViewHeight:844});f.addon.startBoss({x:400,y:300});step(f,120);assert.equal(f.addon.hazards.pool.dropped,0);assert.ok(f.addon.hazards.pool.count<220);f.addon.dispose();assert.equal(f.addon.hazards.pool.count,0);});
