import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,step} from './stageboss-fixture94.mjs';
import {createGallipoliRoute,gallipoliPoint,tickGallipoliRoute,GALLIPOLI_ROUTE} from '../gallipoli-route.js';
import {gallipoliMuzzle,gallipoliObjective,GALLIPOLI_PARTS,GALLIPOLI_SECTORS,GALLIPOLI_EXTENTS} from '../gallipoli-boss.js';
const battle=(team='entente')=>{const f=fixture({teamFaction:team,stageIndex:14});f.addon.startBoss({x:0,y:0});f.b=[...f.addon.stages.encounter.bodies.values()][0];return f;};
const destroy=(f,id)=>f.addon.hit({bodyId:f.b.id,partId:id,damage:1e9,faction:f.addon.stages.teamFaction});
const capture=(f,id)=>{for(const p of GALLIPOLI_SECTORS.find(s=>s.id===id).guards)destroy(f,p);step(f,.1);};
test('Gallipoli is a single stationary 2558-wide siege boss with 13 distinct defenses and opposing faction',()=>{for(const team of ['central','entente']){const f=battle(team);assert.equal(f.b.kind,'gallipoli-fortress');assert.notEqual(f.b.faction,team);assert.equal(f.b.parts.size,13);assert.equal(f.addon.stages.encounter.bodies.size,1);assert.equal(GALLIPOLI_EXTENTS.halfWidth*2,2558);step(f,30);assert.equal(f.b.x,0);assert.equal(f.b.y,0);}});
test('Entry protects every installation, then swept bullets hit each authored mount',()=>{const f=battle();for(const p of GALLIPOLI_PARTS)assert.equal(destroy(f,p.id).damage,0);step(f,5.1);for(const p of GALLIPOLI_PARTS)assert.deepEqual(f.b.locateHit({x:p.x,y:p.y+5,previousX:p.x,previousY:p.y-5}),{partId:p.id});});
test('Command battery is immediately hittable after entry and does not require occupation',()=>{const f=battle();step(f,5.1);assert.deepEqual(f.b.locateHit({x:0,y:0}),{partId:null});const r=f.b.hit({damage:1e9});assert(r.commandDestroyed);assert(!r.bodyDefeated);assert.equal(f.b.captured.size,0);assert.equal(f.b.hp,f.b.maxHp*.75);assert.equal(f.b.locateHit({x:0,y:0}),null);assert([...f.b.parts.values()].some(p=>!p.destroyed));});
test('Every destroyed installation repairs after 18 seconds with warning and two seconds firing grace',()=>{const f=battle();step(f,5.1);destroy(f,'left');const p=f.b.parts.get('left'),hp=f.b.hp;step(f,14.9);assert(p.destroyed);assert(!p.repairWarned);step(f,.2);assert(p.repairWarned);step(f,2.8);assert(p.destroyed);step(f,.2);assert(!p.destroyed);assert.equal(p.hp,p.maxHp);assert.equal(f.b.hp,hp+p.maxHp);assert(p.repairGrace>1.8);assert(f.log.cues.some(e=>e.phase==='gallipoli-repair-warning'));assert(f.log.cues.some(e=>e.phase==='gallipoli-repaired'));});
test('Repeated repair cannot overfill HP, supply explosions only count actual local damage once',()=>{const f=battle();step(f,5.1);for(let i=0;i<4;i++){const before=f.b.hp,p=f.b.parts.get('left');destroy(f,'ammo-west');assert.equal(p.hp,p.maxHp*.65);assert(Math.abs(before-f.b.hp-(f.b.parts.get('ammo-west').maxHp+2*p.maxHp*.35))<1e-6);const after=f.b.hp;destroy(f,'ammo-west');assert.equal(f.b.hp,after);assert.throws(()=>f.b.hit({partId:'left',damage:NaN}));assert.equal(f.b.hp,after);destroy(f,'left');destroy(f,'west-howitzer');step(f,18.1);assert(f.b.hp<=f.b.maxHp+1e-6);assert(Math.abs(f.b.hp-f.b.maxHp)<1e-6);}});
test('Command destruction cancels pending central fire, repairs and future sorties; remaining guns still attack',()=>{const f=battle();step(f,5.1);destroy(f,'left');f.b.planCentral({x:500,y:-500});f.b.hit({damage:1e9});assert.equal(f.b.pendingAttack,null);assert.equal(f.b.parts.get('left').repairRemaining,0);const count=f.log.minions.length;step(f,50);assert(f.b.parts.get('left').destroyed);assert.equal(f.log.minions.length,count);assert(!f.b.dead);const shots=[];f.addon.hazards.pool.visit(h=>shots.push(h));assert(f.log.cues.some(e=>e.type==='muzzle'&&e.partId));});
test('Disabled sectors can reactivate but losing all defenses never auto-unlocks or kills command',()=>{const f=battle();step(f,5.1);capture(f,'west');assert(f.b.captured.has('west'));step(f,18.1);assert(!f.b.captured.has('west'));for(const p of f.b.parts.values())destroy(f,p.id);step(f,.1);assert.equal(f.b.captured.size,3);assert(!f.b.commandDestroyed);assert(!f.b.dead);assert.equal(f.b.commandHp,f.b.commandMaxHp);});
test('Cross salvo waits for barrel alignment and then brackets the captured player instead of a permanent safe centre',()=>{
 const f=battle();step(f,5.1);f.b.planCoastal(f.frame.players[0]);const plan=f.b.pendingAttack;assert(plan);
 for(const source of plan.sources){const p=f.b.parts.get(source.id);p.angle=Math.atan2(source.target.y-p.y,source.target.x-p.x)+Math.PI;}
 const n=f.log.cues.filter(e=>e.type==='muzzle').length;f.b.fireIfAligned();assert.equal(f.log.cues.filter(e=>e.type==='muzzle').length,n);
 const target=f.frame.players[0];assert(plan.sources.some(s=>s.shots.some(h=>Math.hypot(h.x-target.x,h.y-target.y)<=h.radius+12)));
 for(const source of plan.sources)for(const h of source.shots){assert(h.warning>=1.8);const escaped={x:target.x,y:target.y-180*((h.delay||0)+h.warning)};assert(Math.hypot(h.x-escaped.x,h.y-escaped.y)>h.radius+12);}
});
test('Aligned coastal salvos lock their world coordinates after the player turns',()=>{
 const f=battle();step(f,5.1);f.b.planCoastal(f.frame.players[0]);const frozen=f.b.pendingAttack.sources.map(s=>s.shots.map(h=>[h.x,h.y]));
 f.frame.players[0].x+=700;f.frame.players[0].y-=250;
 assert.deepEqual(f.b.pendingAttack.sources.map(s=>s.shots.map(h=>[h.x,h.y])),frozen);
 for(const s of f.b.pendingAttack.sources){const p=f.b.parts.get(s.id);p.angle=Math.atan2(s.target.y-p.y,s.target.x-p.x);}
 f.b.fireIfAligned(.05);assert(f.addon.hazards.pool.count>0);
});
test('Every artillery type has a full barrel muzzle, objective follows nearest remaining defense',()=>{const f=battle();for(const p of f.b.parts.values())if(p.kind==='gun'||p.kind==='aa')for(const a of [0,Math.PI/2,Math.PI]){p.angle=a;const m=gallipoliMuzzle(f.b,p);assert(Math.abs(Math.atan2(m.y-p.y,m.x-p.x)-a)<1e-8);assert(Math.abs(Math.hypot(m.x-p.x,m.y-p.y)-(p.kind==='aa'?92:p.art==='twin'?168:162))<1e-8);}assert.equal(gallipoliObjective(f.b,-1290,160).id,'left');step(f,5.1);capture(f,'west');assert.notEqual(gallipoliObjective(f.b,-1290,160).sector,'west');});
test('Compressed Gallipoli route reaches coast, trenches and fortress early while preserving 7200-wide lateral freedom',()=>{assert.deepEqual({shore:GALLIPOLI_ROUTE.shore,cliff:GALLIPOLI_ROUTE.cliff,fort:GALLIPOLI_ROUTE.fort,bossLimit:GALLIPOLI_ROUTE.bossLimit},{shore:2800,cliff:4000,fort:8000,bossLimit:10800});const g={x:10,y:20,a:-Math.PI/2,stageBoss:{stages:{stageIndex:14,phase:'explore'}},events:[],event(t,m){this.events.push(m)}};g.gallipoliRoute=createGallipoliRoute(g);const r=g.gallipoliRoute;for(let i=0;i<100;i++)tickGallipoliRoute(g);assert.equal(r.maxForward,0);Object.assign(g,gallipoliPoint(r,7600,3000));tickGallipoliRoute(g);assert.equal(r.maxForward,7600);assert.equal(g.events.length,4);assert(Math.abs(g.x-r.x-3000)<1e-8);tickGallipoliRoute(g);assert.equal(g.events.length,4);g.players=[g,{...gallipoliPoint(r,15000,-10000)}];tickGallipoliRoute(g);assert(Math.abs(g.players[1].x-r.x+3600)<1e-8);assert.equal(g.players[1].y,r.y-10800);g.stageBoss.stages.stageIndex=0;tickGallipoliRoute(g);assert.equal(g.gallipoliRoute,null);});
test('Any destruction order completes only after command and all offensive batteries are dead, with optional facilities cleaned up',()=>{for(const order of ['command-first','command-last']){const f=battle();step(f,5.1);if(order==='command-first')f.b.hit({damage:1e9});for(const p of f.b.parts.values())if(p.kind==='gun'||p.kind==='aa')destroy(f,p.id);if(order==='command-last'){assert(!f.b.dead);f.b.hit({damage:1e9});}assert(f.b.dead);assert.equal(f.b.hp,0);assert([...f.b.parts.values()].every(p=>p.destroyed));assert.equal(f.log.cues.filter(e=>e.type==='body-defeated').length,1);step(f,40);assert.equal(f.b.hp,0);}});
test('Turrets continuously slew by shortest angle at bounded speed and freeze while paused',()=>{const f=battle();step(f,5.1);const p=f.b.parts.get('left');p.angle=0;f.frame.players[0]={id:'p',alive:true,x:p.x,y:p.y+500};f.frame.players.length=1;step(f,.1);assert(p.angle>0&&p.angle<=.071);const before=p.angle;f.frame.paused=true;step(f,5);assert.equal(p.angle,before);});
test('All weapons gone leaves independent central salvos alive at high loop speed with safe windows',()=>{const f=battle();step(f,5.1);for(const p of f.b.parts.values())destroy(f,p.id);f.b.t.patternMultiplier=3;f.b.centralClock=8;step(f,9);assert(!f.b.commandDestroyed);assert(f.log.cues.some(e=>e.type==='muzzle'&&!e.partId));assert(!f.b.dead);assert.equal(f.addon.hazards.pool.dropped,0);});
test('Single fixed hangar launches faction-specific interceptors repeatedly with four-aircraft cap and resumes after losses',()=>{for(const team of ['central','entente']){const f=battle(team);step(f,50);assert.equal(f.log.minions.length,4);for(const m of f.log.minions){assert.equal(m.plane,f.b.faction==='central'?'eindecker':'nieuport11');assert.equal(m.behavior,'gallipoli-interceptor');assert.equal(m.x,-359);assert.equal(m.y,-168);}f.log.minions.pop();step(f,3);assert.equal(f.log.minions.length,4);}});
test('Destroying a queued gun removes its plan permanently, even after repair',()=>{const f=battle();step(f,5.1);f.b.planCoastal(f.frame.players[0]);const id=f.b.pendingAttack.sources[0].id;destroy(f,id);assert(!f.b.pendingAttack.sources.some(s=>s.id===id));});

test('Coastal crossfire selects opposing wings; citadel takes over without locking damage order',()=>{const f=battle();step(f,5.1);f.b.planCoastal(f.frame.players[0]);assert.deepEqual(f.b.pendingAttack.sources.filter(s=>f.b.parts.get(s.id).kind==='gun').map(s=>f.b.parts.get(s.id).sector),['west','east']);f.b.pendingAttack=null;capture(f,'west');capture(f,'east');assert.equal(f.b.defensePhase,2);f.b.planCoastal(f.frame.players[0]);assert(f.b.pendingAttack.sources.filter(s=>f.b.parts.get(s.id).kind==='gun').every(s=>f.b.parts.get(s.id).sector==='citadel'));assert.deepEqual(f.b.locateHit({x:0,y:0}),{partId:null});});
test('Twin guns use a rapid pair and howitzers a slower pair, local ammunition removes second shells',()=>{const f=battle();step(f,5.1);f.b.batteryCursor=0;f.b.planCoastal(f.frame.players[0]);const twin=f.b.pendingAttack.sources[0];assert(Math.abs(twin.shots[1].delay-twin.shots[0].delay-.24)<1e-8);f.b.batteryCursor=1;f.b.planCoastal(f.frame.players[0]);const howitzer=f.b.pendingAttack.sources[0];assert.equal(f.b.parts.get(howitzer.id).art,'howitzer');assert(Math.abs(howitzer.shots[1].delay-howitzer.shots[0].delay-.85)<1e-8);destroy(f,'ammo-west');f.b.planCoastal(f.frame.players[0]);assert.equal(f.b.pendingAttack.sources.find(s=>f.b.parts.get(s.id).sector==='west').shots.length,1);destroy(f,'observer');f.b.planCoastal(f.frame.players[0]);assert(f.b.pendingAttack.sources.filter(s=>f.b.parts.get(s.id).kind==='gun').every(s=>s.shots.every(h=>h.warning===2.3)));});
test('Each delayed shell gets its own aligned muzzle and no future shot survives destruction',()=>{const f=battle();step(f,5.1);f.b.planCoastal(f.frame.players[0]);const attack=f.b.pendingAttack,commands=[],emit=f.b.emit;f.b.emit=e=>{if(e.type==='hazard'&&e.kind!=='projectile')commands.push(e);emit(e);};for(const s of attack.sources){const p=f.b.parts.get(s.id);p.angle=Math.atan2(s.target.y-p.y,s.target.x-p.x);}f.b.fireIfAligned();assert.equal(commands.length,1);const source=attack.sources[0],first=commands[0],mount=f.b.parts.get(source.id),m=gallipoliMuzzle(f.b,mount,-1);assert.equal(first.sourceX,m.x);assert.equal(first.sourceY,m.y);assert.equal(first.delay,0);destroy(f,source.id);step(f,1.3);assert.equal(commands.filter(h=>h.kind!=='projectile'&&h.tag.endsWith(':'+source.id)).length,1);assert(f.log.cues.filter(e=>e.type==='muzzle').length>=commands.length);});
const finalPlan=(f)=>{f.b.pendingAttack=null;f.b.planFinal(f.frame.players[0]);return f.b.pendingAttack;};
const alignFinal=(f)=>{for(const s of f.b.pendingAttack?.sources||[]){if(s.id){const p=f.b.parts.get(s.id);p.angle=Math.atan2(s.target.y-p.y,s.target.x-p.x);}else f.b.coreAngle=Math.atan2(s.target.y,s.target.x);}};
test('Last barrage omits destroyed sectors and command, preserves independent central attacks',()=>{for(const removed of [[],['west'],['east','citadel'],['west','east','citadel']])for(const commandDead of [false,true]){const f=battle();step(f,5.1);for(const sector of removed)capture(f,sector);if(commandDead)f.b.hit({damage:1e9});if(f.b.dead)continue;const a=finalPlan(f);assert(a);for(const s of a.sources){if(s.id)assert(!removed.includes(f.b.parts.get(s.id).sector));else assert(!commandDead);}assert.equal(a.sources.some(s=>s.id===null),!commandDead);if(removed.length===3)assert.deepEqual(a.sources.map(s=>s.id),[null]);for(const source of a.sources)for(const h of source.shots)assert(h.warning>=2&&Number.isFinite(h.x)&&Number.isFinite(h.y));}});
test('Last barrage uses west/east/citadel timing and strong central finish, then a real quiet recovery',()=>{const f=battle();step(f,5.1);const a=finalPlan(f);assert.deepEqual(a.sources.map(s=>s.id?f.b.parts.get(s.id).sector:'command'),['west','east','citadel','command']);assert.deepEqual(a.sources.map(s=>s.shots[0].delay),[1,2.15,3.3,4.5]);alignFinal(f);f.b.fireIfAligned();const launched=[],emit=f.b.emit;f.b.emit=e=>{if(e.type==='hazard')launched.push({...e,at:f.b.clock});emit(e);};step(f,9);assert.equal(launched.filter(h=>h.kind!=='projectile').length,7);assert.equal(launched.filter(h=>h.kind==='projectile').length,24);const bySector=sector=>launched.find(h=>sector==='command'?h.tag.endsWith(':central'):f.b.parts.get(h.tag.split(':').at(-1))?.sector===sector).at;assert(bySector('west')<bySector('east'));assert(bySector('east')<bySector('citadel'));assert(bySector('citadel')<bySector('command'));assert(f.b.recoveryRemaining>0);assert(f.log.cues.some(e=>e.phase==='gallipoli-recovery'));const n=launched.length;step(f,.5);assert.equal(launched.length,n);assert.equal(f.addon.hazards.pool.count,0);});
test('Command destruction during last barrage removes its queued finish and cancels repairs, not surviving wing shots',()=>{const f=battle();step(f,5.1);finalPlan(f);alignFinal(f);f.b.fireIfAligned();f.b.hit({damage:1e9});assert(f.b.pendingAttack.sources.every(s=>s.id));const events=[],emit=f.b.emit;f.b.emit=e=>{events.push(e);emit(e);};step(f,7);assert(!events.some(e=>e.type==='hazard'&&e.tag.endsWith(':central')));assert(events.some(e=>e.type==='muzzle'&&e.partId));assert.equal(f.log.minions.length,0);});
test('Low defense actually triggers last barrage; repaired facilities never rejoin its old queue',()=>{const f=battle();step(f,5.1);f.b.hit({damage:1e9});capture(f,'west');capture(f,'citadel');destroy(f,'ammo-east');step(f,.1);assert.equal(f.b.defensePhase,3);assert.equal(f.b.pendingAttack?.kind,'final');const id=f.b.pendingAttack.sources[0].id;destroy(f,id);assert(!f.b.pendingAttack.sources.some(s=>s.id===id));});
test('Approach shells leave fixed authored batteries while the compressed shoreline and fortress anchor stay unchanged',()=>{const f=fixture({teamFaction:'entente',stageIndex:14}),g={x:0,y:0,a:-Math.PI/2,stageBoss:f.addon,event(){}};g.gallipoliRoute=createGallipoliRoute(g);const r=g.gallipoliRoute;for(const forward of [2200,4300,6500]){Object.assign(g,gallipoliPoint(r,forward));for(let i=0;i<40;i++)tickGallipoliRoute(g,.05);}const shells=[];f.addon.hazards.pool.visit(h=>shells.push({...h}));assert.equal(shells.length,3);assert.equal(r.preview.y,-8000);for(const h of shells){assert.equal(h.visual,'gallipoli-shell');assert(Number.isFinite(h.sourceX)&&Number.isFinite(h.sourceY));assert(h.sourceY<-7000);assert(h.warning>=2.6);}assert.equal(r.preview.parts.size,13);const preview=r.preview;tickGallipoliRoute(g,.05);assert.equal(r.preview,preview);f.addon.startBoss({x:0,y:-8000});tickGallipoliRoute(g,.05);assert.equal(f.addon.hazards.pool.count,0);f.addon.stages.stageIndex=0;tickGallipoliRoute(g);assert.equal(g.gallipoliRoute,null);});
test('Authored repair blend progresses wreck to damaged to intact without restoring a dead command facility',async()=>{const {gallipoliRepairBlend}=await import('../gallipoli-view.js');assert.deepEqual(gallipoliRepairBlend({destroyed:true,repairRemaining:3},false),{from:2,to:1,amount:0});assert.deepEqual(gallipoliRepairBlend({destroyed:true,repairRemaining:1.5},false),{from:2,to:1,amount:1});assert.equal(gallipoliRepairBlend({destroyed:true,repairRemaining:1.5},true),null);assert.deepEqual(gallipoliRepairBlend({destroyed:false,repairGrace:2},false),{from:1,to:0,amount:0});assert.deepEqual(gallipoliRepairBlend({destroyed:false,repairGrace:1},false),{from:1,to:0,amount:0});assert.equal(gallipoliRepairBlend({destroyed:false,repairGrace:0},false),null);});
test('Gallipoli defeat completes once, transitions normally and a fresh attempt restores all defenses',()=>{const f=battle();step(f,5.1);f.b.hit({damage:1e9});for(const p of f.b.parts.values())if(p.kind==='gun'||p.kind==='aa')destroy(f,p.id);step(f,3.2,{advance:true});assert.equal(f.log.clears.length,1);assert.notEqual(f.addon.stages.stageIndex,14);assert.equal(f.addon.hazards.pool.count,0);const retry=battle();assert.equal(retry.b.entryAge,0);assert.equal(retry.b.commandDestroyed,false);assert.equal(retry.b.parts.size,13);assert([...retry.b.parts.values()].every(p=>!p.destroyed&&p.hp===p.maxHp&&p.repairRemaining===0));});
