import test from 'node:test';import assert from 'node:assert/strict';
globalThis.Image=class {set src(v){queueMicrotask(()=>this.onload?.());}};globalThis.document={createElement:()=>({getContext:()=>null})};
const {Game}=await import('../engine.js?v=tame3'),{CoopGame}=await import('../coop-engine.js?v=tame3');
const {updateNavalFleet,fireSurfaceExchange,SHIP_TYPES}=await import('../fleet-naval1.js?v=tame3');

const {fixture,step}=await import('./stageboss-fixture94.mjs');
const {recordShipWake}=await import('../naval-water.js?v=tame3');
function game(mode,region,faction='entente'){const pilot=faction==='central'?'baron':'fonck',g=mode==='solo'?new Game(faction==='central'?'fokker':'spad',pilot,()=>.5):new CoopGame([{pilot},{pilot}],{rng:()=>.5});g.region=region;g.worldRegion=()=>g.region;g.invuln=Infinity;for(const p of g.players||[])p.invuln=Infinity;return g;}
test('All three seas spawn opposite mortal fleets, ally hulls never enter enemy collision lists',()=>{for(const mode of ['solo','coop'])for(const region of [1,7,16])for(const faction of ['central','entente']){const g=game(mode,region,faction);g.spawnMovingFleet(faction==='central'?'entente':'central');g.spawnMovingFleet(faction);assert.equal(g.friendlyShips.length,2);assert.equal(g.enemies.filter(e=>e.movingShip).length,2);assert(g.friendlyShips.every(e=>!g.enemies.includes(e)&&e.faction===faction));assert(g.enemies.filter(e=>e.movingShip).every(e=>e.speed===0&&e.stationary));}});
test('Both fleets exchange aimed shells with real HP loss, without player damage or kill credit',()=>{for(const mode of ['solo','coop']){const g=game(mode,1),enemy=g.spawnMovingFleet()[0],ally=g.spawnMovingFleet('entente')[0];enemy.x=200;enemy.y=0;ally.x=0;ally.y=0;const hp=enemy.hp,ahp=ally.hp,playerHp=g.hp,kills=g.kills;assert(fireSurfaceExchange(g,ally,SHIP_TYPES[ally.shipClass]));assert(fireSurfaceExchange(g,enemy,SHIP_TYPES[enemy.shipClass]));for(let i=0;i<30;i++)updateNavalFleet(g,.04);assert(enemy.hp<hp);assert(ally.hp<ahp);assert.equal(g.hp,playerHp);assert.equal(g.kills,kills);assert(g.navalExchanges.length<=24);}});
test('Native solo and coop update move ships exactly once and preserve pause',()=>{for(const mode of ['solo','coop']){const g=game(mode,1),ship=g.spawnMovingFleet()[0];g.nextHeavyAt=Infinity;g.nextBossAt=Infinity;ship.driveVelocity=ship.sailingSpeed;const x=ship.x,y=ship.y;g.update(.04,{});assert(Math.hypot(ship.x-x,ship.y-y)<=ship.sailingSpeed*.0401);assert(ship.wakeTrail.length);const frozen=JSON.stringify([ship.x,ship.y,ship.waterTime,g.navalExchanges]);g.state='paused';g.update(.5,{});assert.equal(JSON.stringify([ship.x,ship.y,ship.waterTime,g.navalExchanges]),frozen);}});
test('Land transition clears friendly hulls and ship-only rounds',()=>{const g=game('solo',16);g.spawnMovingFleet();g.spawnMovingFleet('entente');g.navalExchanges=[{age:0,duration:3}];g.region=0;updateNavalFleet(g,.04);assert.equal(g.friendlyShips.length,0);assert.equal(g.navalExchanges.length,0);});
test('Wake history is world anchored and bounded; render cadence cannot drive it',()=>{const b={x:0,y:0,hullYaw:0};for(let i=0;i<500;i++){b.x=i; b.y=-i*5;recordShipWake(b,.04,300);}assert(b.wakeTrail.length<=24);assert(b.wakeTrail.every(p=>Number.isFinite(p.x)&&p.y<0));});
test('Destroyed observer has monotonic death age and no further attacks; survivors retreat separately',()=>{const f=fixture({stageIndex:16});f.addon.startBoss({x:0,y:0});step(f,5.1);const a=[...f.addon.stages.encounter.bodies.values()].at(-1);a.hit({damage:1e9});assert(a.dead);assert(!a.retreating);step(f,3);assert(a.deathAge>=2.65);const clock=a.launchClock;step(f,1);assert.equal(a.launchClock,clock);});
test('Sea regulars use faction appropriate floatplanes frequently, land rosters remain unchanged',()=>{for(const faction of ['entente','central']){const g=game('solo',16,faction);for(let i=0;i<8;i++)g.spawnEnemy(i%2?'hunter':'bomber');const sea=g.enemies.filter(e=>!e.bossPilot&&!e.heavyBomber);assert(sea.some(e=>['ff33','lohner_l','hansa_brandenburg_cc','hb_w29','macchi_m3','macchi_m5'].includes(e.escortPlane)));const land=game('solo',0,faction);land.spawnEnemy('scout');assert(!['ff33','macchi_m3'].includes(land.enemies.at(-1).escortPlane));}});
