import test from 'node:test';import assert from 'node:assert/strict';
import {hullOverlap,bossHullRect} from '../adriatic-boss-layout.js?v=coop1';
import {fleetHull,surfaceTraffic,resolveSurfaceSpacing,vacantShipPose} from '../naval-spacing.js?v=coop1';
import {fixture,step} from './stageboss-fixture94.mjs';
const ship=(x=0,y=0,a=0)=>({x,y,a,course:a,hp:100,movingShip:true,hullWidth:40,hullLength:150,driveVelocity:20});
function clear(g){const s=surfaceTraffic(g);for(let i=0;i<s.length;i++)for(let j=i+1;j<s.length;j++)assert.equal(hullOverlap(fleetHull(s[i]),fleetHull(s[j]),1),null);for(const e of s)for(const b of g.stageBoss?.stages?.encounter?.bodies.values()||[])if(bossHullRect(b))assert.equal(hullOverlap(fleetHull(e),bossHullRect(b),1),null);}
test('Full rotated allied and hostile hulls cannot overlap in dense contacts',()=>{for(const angle of [0,.3,Math.PI/2,2.2]){const g={enemies:[ship(0,0,angle),ship(5,5,-angle),ship(10,0,1)],friendlyShips:[ship(0,5,.4),ship(0,0,2)]};resolveSurfaceSpacing(g);clear(g);}});
test('Spawn placement rejects occupied hull space for either faction',()=>{const g={enemies:[ship()],friendlyShips:[ship(0,200)]},candidate=ship();assert(vacantShipPose(g,candidate));g.friendlyShips.push(candidate);clear(g);});
test('Fleet traffic yields to full Jutland boss rectangles and airship is excluded',()=>{const b={x:0,y:0,width:254,height:940,hullYaw:.5,jutlandBoss:true},g={enemies:[ship()],friendlyShips:[ship(0,100)],stageBoss:{stages:{encounter:{bodies:new Map([['b',b]])}}}};resolveSurfaceSpacing(g);clear(g);assert.equal(b.x,0);assert.equal(b.y,0);assert.equal(bossHullRect({...b,jutlandAirship:true,kind:'jutland-observer'}),null);});
test('Jutland capital ships separate after movement and maintain rotated mounts',()=>{const f=fixture({stageIndex:16});f.addon.startBoss({x:0,y:0});const ships=[...f.addon.stages.encounter.bodies.values()].filter(b=>!b.jutlandAirship);for(const b of ships){b.x=0;b.y=0;b.hullYaw=.4;}step(f,.05);for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)assert.equal(hullOverlap(bossHullRect(ships[i]),bossHullRect(ships[j]),1),null);for(const b of ships)for(const p of b.parts.values())assert(Math.abs(p.x-(p.localX*Math.cos(b.hullYaw)-p.localY*Math.sin(b.hullYaw)))<1e-8);});
