import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,PILOT_PLANES,angleDiff} from '../engine.js?v=sink4';
import {CoopGame} from '../coop-engine.js?v=sink4';
import {signatureState,advancePilotSignature} from '../pilot-signature-state.js?v=sink4';
import {createPilotSignatureRenderer} from '../pilot-signature-renderer.js?v=sink4';

const ids=['huffzky','mckeever','jacobs','hawker','berthold','udet','goering','nungesser','barker'];
function session(id,coop=false){const g=coop?new CoopGame([{pilot:id},{pilot:id}],{rng:()=>.5}):new Game(PILOT_PLANES[id],id,()=>.5),p=g.players?.[0]||g;
 for(const k of ['spawn','nextBossAt','_zeppelinSchedule','nextHeavyAt','eventTimer','allyTimer','flakTimer','regionThreat','gustTimer','supplyTimer','fieldUnitTimer','gasTimer','patrolTimer'])g[k]=Infinity;
 Object.assign(p,{x:0,y:0,a:0,invuln:0,need:Infinity,speed:0,baseSpeed:0,fire:0});if(g.players)Object.assign(g.players[1],{x:1500,y:1500,fire:Infinity});
 const tick=(n=1,input={})=>{for(let i=0;i<n;i++){if(coop){g.t+=.02;g.updatePlayer(p,.02,input);g.updateSupport(.02);g.updateOrdnance(.02);}else g.update(.02,input);}};
 const enemy=(x,y)=>{const e={x,y,a:0,hp:100000,maxHp:100000,speed:0,fire:Infinity,type:'hunter',wobble:0};g.enemies.push(e);return e;};return{g,p,tick,enemy};}
for(const coop of [false,true]){
 const mode=coop?'coop':'solo';
 test(`${mode} all nine activate, expire and keep finite firing/movement`,()=>{for(const id of ids){const {g,p,tick,enemy}=session(id,coop);enemy(180,20);enemy(-180,-20);assert.ok(p.skill(),id);assert.equal(p.skill(),false);tick(360,{steer:.2});for(const key of ['x','y','a','hp','rate','turn','roundsFired'])assert.ok(Number.isFinite(p[key]),id+key);assert.equal(p.skillTime,0,id);assert.ok(p.roundsFired>0,id);assert.ok(g.bullets.every(b=>[b.x,b.y,b.vx,b.vy].every(Number.isFinite)),id);}});
 test(`${mode} Huffzky acquires rear arc then fires four strong bursts without forced spin`,()=>{const {g,p,tick,enemy}=session('huffzky',coop);const rear=enemy(-220,20);enemy(180,0);tick(8);assert.equal(g.bullets.filter(b=>b.pilotRear).length,0);tick(8);assert.ok(g.bullets.some(b=>b.pilotRear));p.cooldown=0;p.reverseBursts=0;p.skill();tick(140);assert.equal(p.reverseBursts,4);assert.ok(Math.abs(angleDiff(p.a,0))<.3);const b=g.bullets.find(b=>b.pilotRear)||{pilotRear:true,ownerId:p.id};p.specialRoundImpact(b,rear);assert.ok(rear.pilotSuppressedUntil>g.t);});
 test(`${mode} McKeever owns different front/rear targets; no forced turn; rear never fires into front arc`,()=>{const {g,p,tick,enemy}=session('mckeever',coop);const fore=enemy(200,80),aft=enemy(-220,-80);p.skill();tick(35);assert.equal(p.nineFrontTarget,fore);assert.equal(p.nineRearTarget,aft);assert.equal(p.a,0);assert.ok(g.bullets.some(b=>b.vx>0));assert.ok(g.bullets.some(b=>b.pilotRear&&b.vx<0));aft.hp=0;tick(2);assert.equal(p.nineRearTarget,null);assert.ok(g.bullets.filter(b=>b.pilotRear).every(b=>b.vx<0));});
 test(`${mode} Jacobs pressure requires actual shots; active fan converges and preserves total payload`,()=>{const {g,p,tick,enemy}=session('jacobs',coop);const e=enemy(200,0);p.fire=Infinity;tick(60);assert.ok(!(e.pilotSuppressedUntil>g.t));p.fire=0;tick(60);assert.ok(e.pilotSuppressedUntil>g.t);assert.equal(p.normalGunMultiplier(),1);p.skill();g.bullets=[];const make=()=>({x:23,y:0,vx:520,vy:0,life:1,gun:0,damage:12,enemy:false,ownerId:p.id,hit:new Set()});const b=p.applySpecialRound(make(),null);assert.equal(g.bullets.length,2);assert.ok(Math.abs(Math.atan2(g.bullets[0].vy,g.bullets[0].vx))>.1);assert.equal(g.bullets.reduce((s,b)=>s+b.damage,0)+b.damage,12);e.x=60;g.bullets=[];p.applySpecialRound(make(),null);assert.ok(Math.abs(Math.atan2(g.bullets[0].vy,g.bullets[0].vx))<.04);});
 test(`${mode} Hawker kill links muzzle, consumes ammo and preserves player heading`,()=>{const {p,tick,enemy}=session('hawker',coop);const next=enemy(160,100);p.skill();p.kills++;const a=p.a,ammo=p.ammo[0];tick(4);assert.equal(p.hawkerNext,next);assert.ok(p.gunDirection(0)>a);assert.equal(p.a,a);assert.ok(p.ammo[0]<ammo);assert.ok(!p.unlimitedAmmo);});
 test(`${mode} Berthold records accepted damage, suppresses recoil and fires exactly one ending salvo`,()=>{const {g,p,tick}=session('berthold',coop);const hit=n=>coop?g.hitPlayer(p,n):p.hit(n);p.skill();p.gustDisorient=1;p.cannonRecoil129=.2;const hp=p.hp;hit(60);assert.equal(p.hp,hp-60);assert.ok(p.heldDamage>0);const held=p.heldDamage;hit(10);assert.equal(p.heldDamage,held);p.fire=Infinity;tick(10);assert.equal(p.gustDisorient,0);p.skillTime=.1;tick();assert.equal(g.bullets.filter(b=>b.ironSalvo).length,5);tick(3);assert.equal(g.bullets.filter(b=>b.ironSalvo).length,5);});
 test(`${mode} Udet sustained-fire sparks and reload reset; controlled acrobatics retain firing`,()=>{const {p,tick,enemy}=session('udet',coop);enemy(220,80);tick(260);assert.ok(p.fxOverheat>.7);p.reloadTime=1;tick();assert.equal(p.fxOverheat,0);assert.equal(p.udetDanger,false);p.reloadTime=0;p.skill();const a=p.a,ammo=p.ammo[0];tick(20,{steer:1});assert.ok(Math.abs(angleDiff(p.a,a))>.4);assert.ok(p.ammo[0]<ammo);assert.equal(p.udetBoost,0);assert.equal(p.invuln,0);});
 test(`${mode} Goering actual left/right crossfire preserves focus and ordinary wing damage`,()=>{const {g,p,tick,enemy}=session('goering',coop);const focus=enemy(350,0);p.whiteFocus=null;p.skill();const next=enemy(20,150);tick(100);const wings=g.allies.filter(a=>a.life>0&&(a.ownerId===undefined||a.ownerId===p.id));assert.ok(wings.some(a=>a.y>80)&&wings.some(a=>a.y<-80));assert.equal(p.whiteFocus,focus);const shots=g.bullets.filter(b=>b.ally);assert.ok(shots.length);assert.ok(shots.every(b=>b.damage<=p.supportPower(coop?7.44:5)+1e-8));p.whiteFocus.hp=0;tick();assert.equal(p.whiteFocus,next);});
 test(`${mode} Nungesser intercepts incoming rounds with death FX; near misses tear and expiry releases fog`,()=>{const {g,p,tick}=session('nungesser',coop);p.hp=15;p.skill();const hp=p.hp,b={x:25,y:0,vx:-300,vy:0,life:1,enemy:true,damage:10};g.bullets.push(b);tick();assert.equal(b.life,0);assert.ok(p.hp>=hp);assert.ok(signatureState(p).effects.some(e=>e.kind==='deathDeflect'));p.skillTime=0;p.invuln=0;g.bullets.push({x:35,y:25,vx:20,vy:0,life:1,enemy:true,damage:10});tick();assert.ok(p.deathFogTear>0);assert.ok(signatureState(p).effects.some(e=>e.kind==='deathRelease'));});
 test(`${mode} Barker reaches one HP and retains damage after Last Stand without a death explosion`,()=>{const {g,p,tick}=session('barker',coop);p.skill();for(let i=0;i<5;i++){p.invuln=0;coop?g.hitPlayer(p,50):p.hit(50);}assert.equal(p.hp,1);assert.equal(p.barkerStacks,5);assert.equal(p.barkerDamageStage,5);p.skillTime=.01;tick(2);assert.ok(p.barkerScarStage>=5);assert.equal(p.state,'playing');assert.equal(p.status==='downed',false);});
}
for(const coop of [false,true]){
 test(`duo equipment conserves ammo and rear mount (${coop?'coop':'solo'})`,()=>{const {g,p,tick,enemy}=session('mckeever',coop);enemy(-200,10);p.shots=3;p.freeVolleyShots=1;tick(40);assert.ok(p.ammo[1]<=p.weapon.belt);const b=g.bullets.find(b=>b.pilotRear);assert.ok(b);const origins=signatureState(p).effects.filter(e=>e.kind==='rearBurst');assert.ok(origins.every(e=>e.x<p.x));p.unlimitedAmmo=true;tick();const ammo=[...p.ammo];tick(30);assert.deepEqual(p.ammo,ammo);});
 test(`Berthold needs hits during this activation (${coop?'coop':'solo'})`,()=>{const {g,p,tick}=session('berthold',coop);p.heldDamage=80;p.skill();p.skillTime=.1;tick(7);assert.equal(g.bullets.filter(b=>b.ironSalvo).length,0);});
 test(`enhanced White Flight spreads once then returns (${coop?'coop':'solo'})`,()=>{const {p,enemy}=session('goering',coop);enemy(350,0);p.skillEnhanced=true;p.skill();const a={slot:0};let prev=0;for(let i=1;i<=67;i++){p.skillTime=p.nineDuration-i*.1;const pos=p.wingFormationTarget(a),spread=Math.abs(pos.y);assert.ok(spread<=180+1e-8);if(p.skillTime<1)assert.ok(spread<=prev+1e-8);prev=spread;}assert.ok(prev<20);});
 test(`fast hostile round expires at actual Nungesser contact (${coop?'coop':'solo'})`,()=>{const {g,p}=session('nungesser',coop);p.skill();const b={x:100,y:0,vx:5000,vy:0,life:1,enemy:true,damage:80};g.resolveHostileRound(b,-100,0);assert.equal(b.life,0);const fx=signatureState(p).effects.find(e=>e.kind==='deathDeflect');assert.ok(fx);assert.ok(Math.abs(fx.x-p.x)<20);});
}
test('coop duo revival resets gun axes and permits no forward rear burst',()=>{const {g,p,tick,enemy}=session('mckeever',true);p.nineRearAim=0;p.nineFrontAim=Math.PI;g.downPlayer(p);g.revive(p);assert.equal(p.nineRearAim,p.a+Math.PI);assert.equal(p.nineFrontAim,p.a);p.x=p.y=0;p.a=0;p.speed=p.baseSpeed=0;enemy(-200,0);tick(30);assert.ok(g.bullets.some(b=>b.pilotRear));assert.ok(g.bullets.filter(b=>b.pilotRear).every(b=>b.vx<0));});
function context(){const c={globalAlpha:1,save(){},restore(){},translate(){},rotate(){},scale(){},measureText(){return{width:6}},strokeText(){},fillText(){}};return c;}
test('nine-pilot FX use authored textures, bounded cues, no coffin or common trails',()=>{for(const id of ids){const {p}=session(id);p.skill();Object.assign(p,{hp:10,muzzleFlash:.05,nineRearFlash:.1,nineRearAim:Math.PI,fxOverheat:1,barkerDamageStage:5,barkerStacks:5});const s=signatureState(p);advancePilotSignature(p,.04);const keys=[],marks=[];const draw=createPilotSignatureRenderer({fx(c,key,...args){keys.push(key);assert.ok(args.every(Number.isFinite));return true},icon(){},insignia(c,key){marks.push(key);return true}});draw(context(),p,0,0);draw(context(),p,0,0,'front');assert.ok(s.effects.length<=32,id);assert.ok(!keys.some(k=>['windStreak','vaporTrail'].includes(k)),id);if(id==='nungesser')assert.ok(!marks.includes('blackHeart'));}});
