import test from 'node:test';import assert from 'node:assert/strict';
import {ParisGun,LIncomparable,Fliegerzug} from '../headon-stageboss-patterns.js?v=ui5';
import {BossHazards,contains} from '../headon-stageboss-hazards.js';
import {Game} from '../engine.js?v=ui5';import {CoopGame} from '../coop-engine.js?v=ui5';
import {enableStageBoss,beginStageBossFrame,endStageBossFrame} from '../stageboss-host.js?v=ui5';

import {fixture,step} from './stageboss-fixture94.mjs';
const tuning={maxHp:2400,partHp:288,damage:18,bulletSpeed:270,warningSeconds:1.55,railCycle:7.45,shellCount:5};
const frame={players:[{id:'p1',alive:true,x:-80,y:130,vx:30,vy:0,radius:12},{id:'p2',alive:true,x:90,y:130,vx:0,vy:0,radius:12}],bounds:{left:-480,right:480,top:-400,bottom:400}};
function boss(Type){const events=[],b=new Type({id:'b',x:0,y:-460,faction:Type===ParisGun?'central':'entente',tuning:{...tuning,...(Type===LIncomparable?{warningSeconds:1.85,railCycle:8.05}:{})},emit:e=>events.push(e)});return{b,events};}
function run(b,seconds,ctx=frame){for(let i=0;i<Math.ceil(seconds/.02);i++)b.update(.02,ctx);}
function aim(b,ctx=frame){b.rail129.velocity=0;b.rail129.target=null;b.rail129.enter('aim');b.update(.02,ctx);}
function expose(b){for(const id of b.railCarOrder)b.hit({partId:id,damage:999999});}
for(const Type of [ParisGun,LIncomparable]){
 test(`${Type.name}: original tail spawn, distinct car spacing and measured hit ellipses`,()=>{const {b}=boss(Type);assert.equal(b.y+b.parts.get('car-rear').y,5);assert.equal(b.parts.get('car-middle').y-b.parts.get('car-front').y,375);for(const id of b.railCarOrder){const p=b.parts.get(id);assert.equal(b.locateHit({x:b.x,y:b.y+p.y}).partId,p.hittable?id:'absorb');}assert.equal(b.locateHit({x:b.x+120,y:b.y+750}),null);});
 test(`${Type.name}: sequential parts drain the one shared HP budget and preserve a finishable core`,()=>{const {b}=boss(Type);const first=b.hp;assert.equal(b.hit({partId:'car-middle',damage:999999}).damage,0);assert.equal(b.hp,first);for(const id of b.railCarOrder){const p=b.parts.get(id),before=b.hp;b.hit({partId:id,damage:999999});assert.ok(Math.abs(b.hp-(before-p.maxHp))<1e-8);assert.equal(b.hit({partId:id,damage:500}).damage,0);}assert.ok(Math.abs(b.hp-b.maxHp*.4)<1e-8);assert.equal(b.coreVulnerable,true);b.hit({damage:999999});assert.equal(b.phase,'runaway');assert.equal(b.hp,b.maxHp*.28);assert.equal(b.hit({damage:100}).damage,0);run(b,3.3);assert.equal(b.phase,'derailed');assert.equal(b.hit({damage:999999}).bodyDefeated,true);assert.equal(b.locateHit({x:b.x,y:b.y}),null);});
 test(`${Type.name}: fixed rail stops motion, still fires and shortens the later derail`,()=>{const {b,events}=boss(Type),target={...b.rail129.railTarget};assert.equal(b.locateHit({...target}).partId,'rail');b.hit({partId:'rail',damage:999999});run(b,.8);const stopped=[b.x,b.y];events.length=0;run(b,20);assert.deepEqual([b.x,b.y],stopped);assert.deepEqual(b.rail129.railTarget,target);assert.ok(events.some(e=>e.visual==='rail-shell'));expose(b);b.hit({damage:999999});run(b,.92);assert.equal(b.phase,'derailed');});
 test(`${Type.name}: wrecks remain world-fixed and cannot be backed through`,()=>{const {b}=boss(Type);run(b,.7);b.hit({partId:'car-rear',damage:999999});const p=b.parts.get('car-rear'),start={...p.detachedPose};run(b,2);const settled={...p.detachedPose};for(let i=0;i<1500;i++){b.update(.02,frame);for(const q of [...b.parts.values()].filter(q=>q.kind==='rail-car'&&!q.destroyed))assert.ok(Math.abs(b.y+q.y-p.detachedPose.y)>=359.99);}assert.ok(p.detachedPose.age>31);assert.ok(Math.abs(p.detachedPose.y-start.y)<20);assert.ok(Math.abs(p.detachedPose.y-settled.y)<.03);assert.ok(Math.abs(p.y-(p.detachedPose.y-b.y))<1e-9);});
 test(`${Type.name}: observer destruction interrupts only unfired aim and restores the full warning`,()=>{const {b,events}=boss(Type);b.hit({partId:'car-rear',damage:999999});aim(b);const old={...b.aimPlan.target};run(b,.8);b.hit({partId:'car-middle',damage:999999});assert.equal(b.aimPlan,null);assert.equal(b.rail129.target,null);events.length=0;const far={...frame,players:frame.players.map(p=>({...p,x:900,y:900}))};run(b,b.rail129.c.aimSeconds-.05,far);assert.equal(events.some(e=>e.visual==='rail-shell'),false);assert.equal(b.aimPlan.blind,true);assert.deepEqual([b.aimPlan.target.x,b.aimPlan.target.y],[old.x,old.y]);run(b,.1,far);assert.ok(events.some(e=>e.visual==='rail-shell'));});
}
test('Bruno commits all five shell points during aim and alternates marching/cross orders',()=>{const {b,events}=boss(ParisGun);aim(b);const points=b.aimPlan.points.map(p=>({...p}));run(b,3,{...frame,players:frame.players.map(p=>({...p,x:450,y:350}))});const shots=events.filter(e=>e.visual==='rail-shell');assert.equal(shots.length,5);assert.deepEqual(shots.map(e=>({x:e.x,y:e.y})),points);assert.ok(shots.every(e=>e.warning===.85));aim(b);assert.equal(b.aimPlan.mode,'cross');assert.equal(b.aimPlan.points.length,5);assert.notDeepEqual(b.aimPlan.points,points);});
test('rear gun gives a committed warning and is permanently silenced by its car loss',()=>{const {b,events}=boss(ParisGun);run(b,1.62);assert.ok(b.aaPlan);const angle=b.aaPlan.angle;run(b,.5,{...frame,players:frame.players.map(p=>({...p,x:400,y:-400}))});const shells=events.filter(e=>e.visual==='rail-mg');assert.equal(shells.length,3);assert.ok(Math.abs(Math.atan2(shells[1].vy,shells[1].vx)-angle)<1e-8);b.hit({partId:'car-rear',damage:999999});events.length=0;run(b,15);assert.equal(events.some(e=>e.visual==='rail-mg'),false);});
test('ammo loss slows reload once without changing the supplied aim or main shell count',()=>{for(const Type of [ParisGun,LIncomparable]){const {b,events}=boss(Type),base=b.baseReload,warning=b.rail129.c.aimSeconds;expose(b);assert.equal(b.rail129.c.reloadSeconds,base*1.6);aim(b);run(b,3);assert.equal(b.rail129.c.aimSeconds,warning);assert.equal(events.filter(e=>e.visual==='rail-shell').length,Type===ParisGun?5:1);assert.equal(events.filter(e=>e.type==='ammo-cookoff').length,1);}});
test('L’Incomparable fires one stationary center hit, swept shock ring and persistent smoke in order',()=>{const {b,events}=boss(LIncomparable);aim(b);run(b,1.9);const hazards=events.filter(e=>e.type==='hazard'&&e.kind==='circle');assert.deepEqual(hazards.map(e=>e.visual),['rail-shell','rural-rail-shock','rural-rail-smoke']);assert.deepEqual(hazards.map(e=>[e.delay,e.warning,e.duration]),[[0,.02,.65],[.28,.55,.4],[.5,.04,1.8]]);assert.ok(hazards.every(e=>!e.vx&&!e.vy));assert.ok(b.recovery>0);assert.equal(b.rail129.c.aimSeconds,1.85);});
test('L’Incomparable reload armor window deals more damage and broken rail prolongs the opening',()=>{const {b}=boss(LIncomparable);expose(b);let before=b.hp;b.hit({damage:10});const loaded=before-b.hp;aim(b);run(b,1.9);before=b.hp;b.hit({damage:10});assert.ok(Math.abs((before-b.hp)/loaded-1.35/.35)<1e-8);const beforeRecovery=b.recovery;b.hit({partId:'rail',damage:999999});b.update(.02,frame);assert.equal(b.rail129.c.reloadSeconds,b.baseReload*1.6*1.4);assert.ok(b.recovery>beforeRecovery);});
test('part damage never heals a core below its reserve',()=>{const {b}=boss(ParisGun);b.hp=50;b.hit({partId:'car-rear',damage:20});assert.ok(b.hp<=50);});
function hazards(){const hits=[],h=new BossHazards({capacity:2,onDamage:(id,damage)=>hits.push({id,damage}),onStatus(){},onBarrierContact(){}});return{h,hits};}
const ring={encounterId:'e',bossId:'b',kind:'circle',x:0,y:0,damage:10,delay:0,warning:0,duration:.4,once:true,radius:245,radiusStart:92,radiusLimit:245,ringSpeed:382.5,ringWidth:42,visual:'rural-rail-shock'};
test('expanding shock has a safe inner area and sweeps outer pilots once at low frame rates',()=>{const {h,hits}=hazards();const wave=h.spawn(ring),players=[{id:'inside',alive:true,x:30,y:0,radius:10},{id:'middle',alive:true,x:150,y:0,radius:10},{id:'edge',alive:true,x:230,y:0,radius:10},{id:'outside',alive:true,x:270,y:0,radius:10}];h.update(.25,{players});assert.deepEqual(hits.map(x=>x.id),['middle']);assert.equal(contains(wave,players[0]),false);h.update(.15,{players});assert.deepEqual(hits.map(x=>x.id),['middle','edge']);assert.equal(h.pool.count,0);});
test('a reused hazard pool slot never retains an old shock annulus or per-pilot hit set',()=>{const {h,hits}=hazards();h.spawn(ring);h.update(.5,{players:[{id:'p',alive:true,x:220,y:0}]});const circle=h.spawn({encounterId:'e',kind:'circle',x:0,y:0,damage:7,duration:.1,radius:245,once:true});assert.equal(circle.ringSpeed,0);assert.equal(circle.innerRadius,0);h.update(.1,{players:[{id:'p',alive:true,x:0,y:0}]});assert.deepEqual(hits.map(x=>x.damage),[10,7]);});
test('Cambrai carrier retains its own mechanics and geometry',()=>{const b=new Fliegerzug({id:'c',x:0,y:0,tuning,faction:'entente'});assert.equal(b.ruralRailBoss,undefined);assert.equal(b.railCarOrder.length,5);assert.equal(b.aimPlan,undefined);});
for(const coop of [false,true])for(const faction of ['central','entente'])test(`real ${coop?'co-op':'solo'} ${faction} rural host pauses and clears pending attacks`,()=>{
 const g=coop?new CoopGame(faction==='central'?[{pilot:'baron'},{pilot:'voss'}]:[{pilot:'fonck'},{pilot:'fonck'}],{rng:()=>.4}):new Game(faction==='central'?'albatros':'spad',faction==='central'?'baron':'fonck',()=>.4);
 g.viewWidth=390;g.viewHeight=844;g.region=0;enableStageBoss(g,{teamFaction:faction,heavyHp:coop?1.65:1});g.stageBoss.stages.stageIndex=0;for(const p of g.players||[g]){p.x=90;p.y=130;p.invuln=9999;}
 const enc=g.stageBoss.startBoss({x:0,y:-460}),b=[...enc.bodies.values()][0];b.rail129.enter('aim');for(let i=0;i<10;i++){g.t+=.02;beginStageBossFrame(g,.02);endStageBossFrame(g,.02);}assert.ok(b.aimPlan);g.state='paused';const before=JSON.stringify([b.x,b.y,b.aimPlan,b.rail129.time,b.aaPlan]);beginStageBossFrame(g,.5);assert.equal(JSON.stringify([b.x,b.y,b.aimPlan,b.rail129.time,b.aaPlan]),before);g.state='playing';for(let i=0;i<120;i++){g.t+=.02;beginStageBossFrame(g,.02);endStageBossFrame(g,.02);}assert.ok(g.stageBoss.hazards.pool.count>0);g.stageBoss.dispose();assert.equal(g.stageBoss.hazards.pool.count,0);assert.equal(b.aimPlan,null);assert.equal(b.barrage,null);
});
for(const faction of ['central','entente'])test(`${faction}: 120-second mobile battle keeps pool bounded and valid after rail/car losses`,()=>{const f=fixture({stageIndex:0,teamFaction:faction});f.hooks.getTuning=()=>({...tuning,patternMultiplier:3,regionalViewWidth:390,regionalViewHeight:844});f.addon.startBoss({x:400,y:300});const b=[...f.addon.stages.encounter.bodies.values()][0];b.hit({partId:'car-rear',damage:999999});b.hit({partId:'rail',damage:999999});step(f,120);assert.equal(f.addon.hazards.pool.dropped,0);assert.ok(f.addon.hazards.pool.count<40);assert.ok([b.x,b.y,b.hp].every(Number.isFinite));f.addon.dispose();assert.equal(f.addon.hazards.pool.count,0);});
