import test from 'node:test';import assert from 'node:assert/strict';
import {createBossEncounter} from '../headon-stageboss-patterns.js?v=r5';
import {armorRotate,armorGunMuzzle,armorAngleDelta,TRENCH_ARMOR_LAYOUT} from '../trench-armor-layout.js?v=r5';
import {treadFrame,drawArmorTreads,prepareArmorTreads,TREAD_PROFILES,TREAD_FRAMES} from '../trench-armor-render.js?v=r5';
import {fixture,step} from './stageboss-fixture94.mjs';
const tuning={maxHp:2400,partHp:280,damage:18,bulletSpeed:270,geometryScale:2.025,projectileDensity:.85,patternMultiplier:1};
const frame={players:[{id:'p1',alive:true,x:100,y:180,vx:40,vy:0,radius:12},{id:'p2',alive:true,x:280,y:220,vx:0,vy:-20,radius:12}],bounds:{left:5,right:395,top:-422,bottom:422}};
function setup(kind='a7v-flak'){const events=[],enc=createBossEncounter({id:'trench-'+kind,bossId:kind,tuning,x:200,y:-160,rng:()=>.5,emit:e=>events.push(e)});return{enc,b:[...enc.bodies.values()][0],events};}
function run(f,seconds){for(let i=0;i<Math.ceil(seconds/.02);i++)f.enc.update(.02,frame);}
function drive(b,seconds,speed,turn=0,brake=false){for(let i=0;i<Math.ceil(seconds/.02);i++)b.drive(.02,speed,turn,undefined,brake);}
test('A7V visibly approaches before searchlight capture and its first warned guns',()=>{const f=setup();run(f,1.8);assert(f.b.entryAge<2);assert(f.b.driveDistance>15);assert(f.events.some(e=>e.type==='armor-entry'));assert(!f.events.some(e=>e.type==='hazard'));run(f,5);assert(f.events.some(e=>e.kind==='searchlight'));assert(f.events.some(e=>e.type==='charge-warning'));assert(f.events.some(e=>e.kind==='projectile'));});
test('A7V independent treads accelerate forward, reverse, brake and counter-rotate the real chassis',()=>{const {b}=setup();const y=b.y;drive(b,2,26);assert(b.y>y);assert(b.leftTrack.speed>0&&b.rightTrack.speed>0);assert(b.leftTrack.roll>0&&b.rightTrack.roll>0);drive(b,2,-23);assert(b.leftTrack.speed<0&&b.rightTrack.speed<0);drive(b,.4,0,0,true);assert.equal(b.leftTrack.speed,0);assert.equal(b.rightTrack.speed,0);const pose=[b.x,b.y,b.hullYaw];drive(b,2,0,.6);assert(Math.abs(b.hullYaw-pose[2])>.6);assert(Math.abs(b.x-pose[0])+Math.abs(b.y-pose[1])<1e-9);assert(b.leftTrack.speed>0&&b.rightTrack.speed<0);assert(b.trackMarks.length>0&&b.trackMarks.length<=80);});
test('A7V rotation keeps every casemate, muzzle and part collision in the same live transform',()=>{const f=setup(),b=f.b;drive(b,3,0,.6);b.aim(.02,frame.players);for(const id of b.gunIds){const gun=b.parts.get(id),q=armorRotate(gun.localX,gun.localY,b.hullYaw);assert(Math.hypot(gun.x-q.x,gun.y-q.y)<1e-9);assert.equal(b.locateHit({x:b.x+q.x,y:b.y+q.y}).partId,id);b.fireGun(gun);const m=armorGunMuzzle(b.kind,gun,b.hullYaw,tuning.geometryScale),cue=f.events.findLast(e=>e.type==='muzzle');assert(Math.hypot(cue.x-b.x-m.x,cue.y-b.y-m.y)<1e-9);for(const shot of f.events.filter(e=>e.tag==='a7v-'+id&&e.kind==='projectile'))assert(Math.abs(armorAngleDelta(Math.atan2(shot.vy,shot.vx)-b.hullYaw,gun.baseAngle))<=b.layout.gunArc+1e-9);}});
test('A7V phase gates at 70/35%, actual steel rotation and hunting-net recovery survive an oversized hit',()=>{const f=setup(),b=f.b;for(const id of ['front','rear'])b.hit({partId:id,damage:99999});b.hit({damage:99999});assert.equal(b.hp,b.maxHp*.7);assert.equal(b.combatPhase,2);b.hit({damage:99999});assert.equal(b.hp,b.maxHp*.35);assert.equal(b.combatPhase,3);b.hit({damage:99999});assert(b.hp>0);let spin=false,recovery=false;for(let i=0;i<600;i++){f.enc.update(.02,frame);spin||=b.rotation?.stage==='spin'&&Math.abs(b.angularVelocity)>.1;recovery||=b.tacticalState==='recovery';}assert(spin);assert(recovery);assert(f.events.some(e=>e.phase==='a7v-hunting-net'));assert(f.events.some(e=>e.visual==='aa-flak'&&e.warning>=1.2));b.hit({damage:99999});assert(b.dead);});
test('A7V broken tread freezes its own animation, limits turning, and two broken treads or engine stop the tank',()=>{const {b}=setup();drive(b,3,0,.6);b.hit({partId:'track-left',damage:99999});const roll=b.leftTrack.roll;b.drive(.02,0,.6);assert(Math.abs(b.angularVelocity)<=.14+1e-9);drive(b,2,0,.6);assert.equal(b.leftTrack.roll,roll);assert.equal(b.leftTrack.speed,0);assert(Math.abs(b.angularVelocity)<=.14+1e-9);b.hit({partId:'track-right',damage:99999});const pose=[b.x,b.y,b.hullYaw];drive(b,3,35,.6);assert.deepEqual([b.x,b.y,b.hullYaw],pose);assert(b.parts.get('engine-deck').hittable);b.hit({partId:'engine-deck',damage:99999});drive(b,2,35,.6);assert.equal(b.driveVelocity,0);});
test('A7V searchlight destruction clears only its attached beam and cancels future tracking',()=>{const f=fixture({stageIndex:2,teamFaction:'entente'});f.hooks.getTuning=()=>tuning;const e=f.addon.startBoss({x:200,y:-160}),b=[...e.bodies.values()][0];step(f,3);assert(f.addon.hazards.pool.count>0);b.hit({partId:'searchlight',damage:99999});step(f,8);const hazards=[];f.addon.hazards.pool.visit(h=>hazards.push(h));assert(!hazards.some(h=>h.kind==='searchlight'));assert(f.log.cues.some(e=>e.phase==='a7v-light-lost'));});
test('A7V destroyed port cancels a warned volley and disappears from rotating shot order',()=>{const f=setup(),b=f.b,gun=b.parts.get('left');b.scheduleGun(gun);b.hit({partId:'left',damage:99999});assert.equal(b.pendingVolley,null);f.events.length=0;run(f,20);assert(!f.events.some(e=>e.kind==='projectile'&&e.tag==='a7v-left'));});
for(const kind of ['a7v-flak','mark-v-cruiser'])test(kind+': registered hull ribbons follow drive phase and stop drawing destroyed belts',()=>{
 const f=setup(kind),b=f.b,calls=[],ctx=new Proxy({},{get:(_,k)=>(...args)=>calls.push([k,...args])});
 const hull={naturalWidth:640},pitch=TREAD_PROFILES[b.kind].pitch*.4;
 const makeCanvas=()=>({getContext:()=>({drawImage(){}})});
 const cache=prepareArmorTreads(hull,b.kind,makeCanvas);
 assert.equal(prepareArmorTreads(hull,b.kind,()=>{throw Error('cache rebuilt')}),cache);
 assert.equal(treadFrame(pitch/TREAD_FRAMES*1.1,b.kind),1);
 assert.equal(treadFrame(-pitch/TREAD_FRAMES*.9,b.kind),TREAD_FRAMES-1);
 assert.equal(treadFrame(pitch,b.kind),0);
 assert.equal(treadFrame(-pitch,b.kind),0);
 const model={assetKey:b.kind,parts:[...b.parts.values()],leftTrack:{roll:5,speed:0},rightTrack:{roll:-5,speed:0}};
 drawArmorTreads(ctx,model,hull);const draws=calls.filter(c=>c[0]==='drawImage');assert.equal(draws.length,2);
 assert.notEqual(draws[0][1],draws[1][1]);assert.notEqual(draws[0][2],draws[1][2]);
 assert(draws[0][6]<0&&draws[1][6]>0,'belts remain on opposite hull edges');
 assert(Object.values(cache).reduce((sum,r)=>sum+r.image.width*r.image.height*4,0)<1024*1024,'bounded mobile atlas memory');
 b.hit({partId:'track-left',damage:99999});calls.length=0;drawArmorTreads(ctx,model,hull);assert.equal(calls.filter(c=>c[0]==='drawImage').length,1);
 model.destroying=true;calls.length=0;drawArmorTreads(ctx,model,hull);assert.equal(calls.length,0);
});

test('Mark V entry advances on both belts, waits before warned alternating sponsons',()=>{const f=setup('mark-v-cruiser');run(f,2.2);assert(f.b.driveDistance>28);assert(!f.events.some(e=>e.kind==='projectile'));run(f,5);assert(f.events.some(e=>e.phase==='markv-entry'));assert(f.events.some(e=>e.type==='charge-warning'));for(const id of f.b.gunIds)assert(f.events.some(e=>e.kind==='projectile'&&e.tag===id));});
test('Mark V wide turn precedes braking, genuine counter-drive waltz and recovery',()=>{const f=setup('mark-v-cruiser'),b=f.b;b.entryAge=3;b.startWaltz(false);const seen=new Set(),start=[b.x,b.y,b.hullYaw];for(let i=0;i<600;i++){run(f,.02);seen.add(b.rotation?.stage);if(b.rotation?.stage==='spin'&&Math.abs(b.angularVelocity)>.2)assert(b.leftTrack.speed*b.rightTrack.speed<0);}assert(Math.hypot(b.x-start[0],b.y-start[1])>30);assert(Math.abs(b.hullYaw-start[2])>1);for(const state of ['arc','brake','spin','recover'])assert(seen.has(state));assert(f.events.some(e=>e.phase==='markv-steel-waltz'));});
test('Mark V 70/35 phases trigger landship acceleration, brake, pivot, breakthrough and counter window',()=>{const f=setup('mark-v-cruiser'),b=f.b;b.entryAge=3;b.hit({partId:'sponson-left',damage:99999});b.hit({damage:99999});assert.equal(b.combatPhase,2);b.hit({damage:99999});assert.equal(b.combatPhase,3);const seen=new Set();let top=0;for(let i=0;i<700;i++){run(f,.02);seen.add(b.rotation?.stage);top=Math.max(top,Math.abs(b.driveVelocity));}for(const state of ['windup','charge','brake','spin','breakthrough','recover'])assert(seen.has(state));assert(top>36);assert(f.events.some(e=>e.phase==='markv-runaway'));b.hit({damage:99999});assert(b.dead);});
test('Mark V port removal erases that rotating flank, every surviving round respects existing traverse limits',()=>{const f=setup('mark-v-cruiser'),b=f.b;b.entryAge=3;b.hit({partId:'sponson-left',damage:99999});f.events.length=0;b.startWaltz(true);for(let i=0;i<650;i++){const before=f.events.length;run(f,.02);for(const shot of f.events.slice(before).filter(e=>e.kind==='projectile'&&e.tag==='sponson-right'))assert(Math.abs(armorAngleDelta(Math.atan2(shot.vy,shot.vx)-b.hullYaw,0))<=b.layout.gunArc+.012);}assert(!f.events.some(e=>e.kind==='projectile'&&e.tag==='sponson-left'));assert(f.events.some(e=>e.kind==='projectile'&&e.tag==='sponson-right'));});
test('Mark V one broken belt reduces actual turn, both prevent rotation, engine reduces charge distance',()=>{const intact=setup('mark-v-cruiser').b,crippled=setup('mark-v-cruiser').b;crippled.coreVulnerable=true;crippled.parts.get('engine-deck').hittable=true;crippled.hit({partId:'engine-deck',damage:99999});const y=intact.y;drive(intact,4,58,.5);drive(crippled,4,58,.5);assert(Math.abs(crippled.y-y)<Math.abs(intact.y-y)*.35);assert(Math.abs(crippled.angularVelocity)<=.68*.18+.001);intact.hit({partId:'track-left',damage:99999});drive(intact,3,58,.5);assert(Math.abs(intact.angularVelocity)<=.14+.001);assert.equal(intact.leftTrack.speed,0);intact.hit({partId:'track-right',damage:99999});const yaw=intact.hullYaw;drive(intact,3,58,.5);assert.equal(intact.hullYaw,yaw);});
test('Mark V damaged-side guard turns the living sponson toward the pilot without snapping hull pose',()=>{const {b}=setup('mark-v-cruiser');b.combatPhase=3;b.hit({partId:'sponson-left',damage:99999});const p=[{alive:true,x:b.x+180,y:b.y+80}],old=b.hullYaw,error=()=>Math.abs(armorAngleDelta(Math.atan2(p[0].y-b.y,p[0].x-b.x),b.hullYaw));const initial=error();for(let i=0;i<300;i++)b.drive(.02,0,b.steering(p));assert(error()<initial);assert(Math.abs(b.hullYaw-old)<.32*6+.02);});
for(const kind of ['a7v-flak','mark-v-cruiser'])test(kind+': solo/coop mobile bounds, finite live mounts, pause and hazard/ground caps over two minutes',()=>{for(const playerCount of [1,2]){const f=fixture({stageIndex:2,teamFaction:kind==='a7v-flak'?'entente':'central'});f.hooks.getTuning=()=>tuning;f.frame.bounds={...frame.bounds};f.frame.players=frame.players.slice(0,playerCount);const e=f.addon.startBoss({x:200,y:-160}),b=[...e.bodies.values()][0];let max=0;for(let i=0;i<2400;i++){if(i===600){b.hit({partId:b.gunIds[0],damage:99999});if(kind==='a7v-flak')b.hit({partId:'rear',damage:99999});b.hit({damage:99999});}if(i===1200)b.hit({damage:99999});f.addon.tick(.05,f.frame);max=Math.max(max,f.addon.hazards.pool.count);assert(b.x>=frame.bounds.left-1&&b.x<=frame.bounds.right+1);assert(b.y>=frame.bounds.top-1&&b.y<=frame.bounds.bottom+1);for(const g of b.liveGuns())assert(Number.isFinite(g.angle)&&Number.isFinite(g.x)&&Number.isFinite(g.y));assert(b.trackMarks.length<=80);}assert(max<75,'bounded readable mobile hazard load: '+max);assert.equal(f.addon.hazards.pool.dropped||0,0);const frozen=JSON.stringify([b.x,b.y,b.hullYaw,b.leftTrack,b.rightTrack]);f.frame.paused=true;step(f,2);assert.equal(JSON.stringify([b.x,b.y,b.hullYaw,b.leftTrack,b.rightTrack]),frozen);}});

test('A7V ballistic flak cannot traverse through the hull or fire beyond its real gun arc',()=>{const f=setup(),b=f.b;drive(b,2,0,.5);for(const gun of b.liveGuns()){b.impact(gun,b.x+900,b.y+700);const h=f.events.findLast(e=>e.kind==='circle');const angle=Math.atan2(h.y-h.sourceY,h.x-h.sourceX);assert(Math.abs(armorAngleDelta(angle-b.hullYaw,gun.baseAngle))<=b.layout.gunArc+1e-9);assert.equal(h.sourcePartId,gun.id);}});

test('moving tank hull gun waits for its warning then launches at the live hull muzzle',()=>{const f=setup('mark-v-cruiser'),b=f.b;b.coreVulnerable=true;b.timers.set('hull-gun',0);b.hullGun(.05,frame.players,1);assert(b.hullShots.length);assert(!f.events.some(e=>e.kind==='projectile'));const saved=b.hullShots.map(s=>({...s}));drive(b,.7,30,.3);assert(!f.events.some(e=>e.kind==='projectile'));b.drive(.06,30,.3);const h=f.events.findLast(e=>e.kind==='projectile'),m=armorRotate(0,saved[0].localY*tuning.geometryScale,b.hullYaw);assert(h);assert(Math.hypot(h.x-b.x-m.x,h.y-b.y-m.y)<1e-9);});
