// Local branch gameplay QA; Test Lab stages repeatable native update/hit paths.
// Public main remains untouched. No claim of physical-device or unassisted play.
import {createRequire} from 'node:module';import {mkdirSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {createCoopRelay} from '../server/coop-relay.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright'),out=process.env.QA_OUTPUT||'/tmp/cambrai-qa';mkdirSync(out,{recursive:true});
const relay=createCoopRelay({staticRoot:process.env.QA_ROOT});await new Promise(r=>relay.server.listen(8787,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true,args:['--no-sandbox','--disable-background-timer-throttling']});const errors=[],resources=[],results=[],baseline=process.env.QA_BASELINE==='1';
async function step(page,seconds,hold=true){await page.evaluate(({seconds,hold})=>{const g=__HEADON_TEST__.debug();g.manualPaused=false;for(let i=0;i<Math.ceil(seconds/.02);i++){const b=g.stageBoss.stages.encounter?.bodies.values().next().value;for(const [j,p]of(g.players||[g]).entries()){p.invuln=Infinity;p.fire=p.motorCannonTimer=p.cow37Timer=Infinity;if(hold&&b){p.x=b.x+(g.viewWidth<=500?(j?45:30):(j?145:100));p.y=b.y+(b.kind==='fliegerzug'?620:-200);p.previousX=p.x;p.previousY=p.y;}}g.state='playing';g.update(.02,g.players?{p1:{inputMode:'gamepad',fireHeld:false,steer:0},p2:{inputMode:'gamepad',fireHeld:false,steer:0}}:{inputMode:'gamepad',fireHeld:false,steer:0});}g.state='paused';},{seconds,hold});}
async function probe(page){return page.evaluate(()=>{const g=__HEADON_TEST__.debug(),b=g.stageBoss.stages.encounter?.bodies.values().next().value;return {t:g.t,state:g.state,stageIndex:g.stageBoss.stages.stageIndex,kind:b?.kind,x:b?.x,y:b?.y,hp:b?.hp,phase:b?.phase,combatPhase:b?.combatPhase,finalRaid:b?.finalRaid,recovery:b?.raidRecovery||b?.recovery,core:b?.coreVulnerable,wheels:b?.wheelsAlive?.(),heading:b?.heading,velocity:b?.driveVelocity,finalDrive:b?.finalDrive,lock:b?.flakLock,parts:b?[...b.parts.values()].map(p=>({id:p.id,dead:p.destroyed,x:p.x,y:p.y})):[],bugs:g.enemies.filter(e=>e.bugDrone&&e.hp>0).map(e=>({x:e.x,y:e.y,port:e.launchPortId,targetX:e.bugTargetX,targetY:e.bugTargetY})),trace:g._cambraiTrace||[],hazards:g.stageBoss.hazards.pool.count,cleared:!b};});}
async function damage(page,id){await page.evaluate(id=>{const g=__HEADON_TEST__.debug(),b=g.stageBoss.stages.encounter.bodies.values().next().value;g.stageBoss.hit({bodyId:b.id,partId:id,damage:1e8,faction:g.teamFaction});},id);}
async function hp(page,f){await page.evaluate(f=>{const b=__HEADON_TEST__.debug().stageBoss.stages.encounter.bodies.values().next().value;b.hp=b.maxHp*f;},f);}
try{for(const pilot of process.env.QA_BOSS==='train'?['baron']:process.env.QA_BOSS==='treffas'?['fonck']:['baron','fonck'])for(const mobile of [false,true])for(const coop of [false,true]){if(process.env.QA_FILTER==='pc'&&(mobile||coop))continue;
 const label=(pilot==='baron'?'fliegerzug':'treffas')+'-'+(mobile?'mobile':'pc')+'-'+(coop?'coop':'solo'),context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1100,height:850},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1}),page=await context.newPage();page.on('pageerror',e=>errors.push({label,error:e.message}));page.on('console',m=>{if(m.type()==='error'&&!m.text().startsWith('Failed to load resource:'))errors.push({label,console:m.text(),location:m.location()});});
 page.on('response',r=>{if(r.status()>=400)resources.push({label,status:r.status(),url:r.url()});});
 await page.goto('http://127.0.0.1:8787/?headonTest=1&autostart=0');await page.waitForFunction(()=>!!window.__HEADON_TEST__,null,{timeout:90000});await page.evaluate(async()=>await(await import('./icons.js?v=r5')).iconsReady);
 const start=async boss=>{await page.evaluate(({boss,pilot,coop})=>{let seed=135;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};__HEADON_TEST__.start({region:8,pilot,coop:coop?(pilot==='baron'?'voss':'guynemer'):undefined,boss,freeze:true,invincible:true});const g=__HEADON_TEST__.debug();for(const k of ['spawn','eventTimer','nextBossAt','nextHeavyAt','_zeppelinSchedule','flakTimer','regionThreat','fieldUnitTimer','gasTimer','gustTimer','patrolTimer','supplyTimer','allyTimer'])g[k]=Infinity;g._cambraiTrace=[];const b=g.stageBoss.stages.encounter?.bodies.values().next().value;if(b){const native=b.emit;b.emit=function(e){if(e.type==='spawn-minion'&&e.minion==='bug'){const p=this.parts.get(e.launchPortId),q=this.carPoint(p),d=Math.hypot(e.passTargetX-q.x,e.passTargetY-q.y),a=Math.atan2(e.passTargetY-q.y,e.passTargetX-q.x),run=Math.min(64,d*.35);g._cambraiTrace.push({at:g.t,port:p.id,dead:p.destroyed,visible:this.launchVisible?.(p,{x:e.x,y:e.y}),offset:Math.hypot(e.x-q.x-Math.cos(a)*run,e.y-q.y-Math.sin(a)*run)});}native(e);};}},{boss,pilot,coop});await page.waitForFunction(()=>document.querySelector('#regionTransition').classList.contains('hidden'),null,{timeout:90000});await page.waitForFunction(()=>document.querySelector('#bossWarning').classList.contains('hidden'),null,{timeout:15000});await page.waitForTimeout(300);};
 const shot=async name=>{await page.waitForTimeout(80);await page.screenshot({path:out+'/'+label+'-'+name+'.png'});};
 await start(false);await page.evaluate(()=>{const g=__HEADON_TEST__.debug();g.stageStartTime=g.t-300;});await step(page,.02,false);await shot('approach');const entryRoute=[];for(let i=0;i<12;i++){await step(page,.3,false);entryRoute.push(await probe(page));}await page.waitForFunction(()=>document.querySelector('#bossWarning').classList.contains('hidden'),null,{timeout:15000});await shot('arrival');assert(entryRoute.some(s=>s.kind));await start(true);await step(page,.02);await shot('entry');await step(page,6);const phase1=await probe(page);await shot('phase1');await hp(page,.66);await step(page,5);const phase2=await probe(page);await shot('phase2');await hp(page,.38);await step(page,2.4);const final=await probe(page);await shot('final');
 if(process.env.QA_CAPTURE==='1'&&label.endsWith('pc-solo')){mkdirSync(out+'/'+label+'-frames',{recursive:true});for(let i=0;i<45;i++){await step(page,.12);await page.screenshot({path:out+'/'+label+'-frames/'+String(i).padStart(3,'0')+'.png'});}}
 await step(page,7);const afterRaid=await probe(page);await shot('recovery');
 if(pilot==='baron'){assert(afterRaid.trace.length,'native app must really launch aircraft');assert(afterRaid.trace.every(e=>!e.dead&&e.offset<1e-8&&(baseline||e.visible)));assert(baseline||afterRaid.combatPhase===3);await damage(page,'car-launch-a');await step(page,2);const before=(await probe(page)).trace.length;await step(page,7);assert((await probe(page)).trace.slice(before).every(e=>e.port!=='car-launch-a'));await shot('damage');await damage(page,'car-launch-b');await step(page,2);const count=(await probe(page)).trace.length;await step(page,7);assert.equal((await probe(page)).trace.length,count);await damage(page,'car-supply');await damage(page,'car-flak');await damage(page,'car-rear');assert((await probe(page)).core);await shot('core');await damage(page,null);assert.equal((await probe(page)).phase,'runaway');await step(page,4);assert.equal((await probe(page)).phase,'derailed');await shot('derailed');await damage(page,null);
 }else{await damage(page,'wheel-left');await damage(page,'rudder');await step(page,3);await shot('damage');await damage(page,'wheel-right');const stopped=await probe(page);await step(page,3);const fixed=await probe(page);assert.equal(fixed.wheels,0);assert.equal(fixed.x,stopped.x);assert.equal(fixed.y,stopped.y);await shot('emplacement');await damage(page,'turret');assert.equal((await probe(page)).lock,null);assert((await probe(page)).core);await shot('core');await damage(page,null);}
 await step(page,.1);await shot('defeat');await step(page,5);const transition=await probe(page);assert(transition.cleared);assert.notEqual(transition.stageIndex,8);await page.evaluate(()=>{const g=__HEADON_TEST__.debug();g.manualPaused=false;g.state='playing';});await page.waitForFunction(()=>document.querySelector('#regionTransition').classList.contains('hidden'),null,{timeout:90000});await page.waitForTimeout(300);await page.evaluate(()=>__HEADON_TEST__.debug().state='paused');await shot('next-region');
 // Restart is a new native encounter, then test ordinary keyboard/touch input.
 await start(true);await step(page,.1);const angle=await page.evaluate(()=>{const g=__HEADON_TEST__.debug();g.manualPaused=false;g.state='playing';return (g.players||[g])[0].a;});
 if(mobile){const stick=await page.locator('#stick').boundingBox();assert(stick);await page.locator('#stick').dispatchEvent('pointerdown',{pointerId:1,clientX:stick.x+stick.width*.9,clientY:stick.y+stick.height*.5});await page.waitForTimeout(500);await page.locator('#stick').dispatchEvent('pointerup',{pointerId:1});}else{await page.keyboard.down('KeyD');await page.waitForTimeout(500);await page.keyboard.up('KeyD');}
 assert(Math.abs(await page.evaluate(()=>{const g=__HEADON_TEST__.debug();return (g.players||[g])[0].a;})-angle)>.01);
 const pacing=await page.evaluate(()=>new Promise(resolve=>{let last=performance.now(),start=last;const times=[];function frame(now){times.push(now-last);last=now;if(now-start<3000)requestAnimationFrame(frame);else{times.shift();times.sort((a,b)=>a-b);resolve({frames:times.length,median:times[Math.floor(times.length*.5)],p95:times[Math.floor(times.length*.95)]});}}requestAnimationFrame(frame);}));
 results.push({label,phase1,phase2,final,afterRaid,pacing,clear:true,nextRegion:transition.stageIndex,restart:true,input:true});console.log('PASS',label,JSON.stringify({launches:afterRaid.trace.length,phase:afterRaid.combatPhase,pacing}));await context.close();
 }}finally{writeFileSync(out+'/results.json',JSON.stringify({baseline,results,errors,resources,limitations:['Test Lab stages native gameplay, not an unassisted full clear.','Mobile touch emulation, not a physical device.','Modified branch is local; public main was inspected separately.','Sound event routing checked; no audible listening verification.']},null,2));await browser.close();await relay.close();}
assert.equal(errors.length,0,JSON.stringify(errors));console.log('Actual app QA complete:',results.length,'scenarios');
